package cmd

import (
	"fmt"
	"strings"

	"github.com/footprintai/containarium/pkg/core/incus"
	"github.com/footprintai/containarium/pkg/version"
	"github.com/spf13/cobra"
)

// sidecarCmd is the parent for platform-sidecar operations. Per
// docs/PLATFORM-SIDECAR-DESIGN.md, each platform sidecar (otel today;
// log / scanner / audit later) gets a subcommand under here. The only
// operation today is `compose <username>`, which prints a ready-to-
// paste docker-compose snippet for the named LXC's identity.
//
// Read-only: prints to stdout. Never writes to tenant files. The
// operator pipes the output into their compose file themselves.
var sidecarCmd = &cobra.Command{
	Use:   "sidecar",
	Short: "Manage platform sidecars (otel, log, scanner, ...)",
	Long: `Manage Containarium's platform sidecar images.

Platform sidecars are small Docker images (otel-sidecar, log-sidecar,
…) that operators add to their LXC's docker-compose stack to layer
cross-cutting concerns (telemetry, logs, …) onto their apps. See
docs/PLATFORM-SIDECAR-DESIGN.md.`,
}

var sidecarOtelCmd = &cobra.Command{
	Use:   "otel",
	Short: "OTel (telemetry) sidecar operations",
}

var sidecarOtelComposeCmd = &cobra.Command{
	Use:   "compose <username>",
	Short: "Print a docker-compose snippet for the OTel sidecar",
	Long: `Print a ready-to-paste docker-compose snippet that adds the OTel
sidecar to the named LXC's compose stack.

The output uses ${VAR} interpolation against the LXC's environment so
the values stay in sync as Containarium re-stamps them
(ToggleMonitoring, MoveContainer adopt, etc.). The current literal
values are shown as comments for diagnostic / verification purposes.

Run this on the same host as the LXC — it reads the LXC's current
Incus config locally. No network calls.

Example:
  containarium sidecar otel compose alice >> docker-compose.yml

Then reference the sidecar from your app service:
  services:
    payment-api:
      network_mode: "service:payment-api-otel"
      depends_on: [payment-api-otel]`,
	Args: cobra.ExactArgs(1),
	RunE: runSidecarOtelCompose,
}

func init() {
	rootCmd.AddCommand(sidecarCmd)
	sidecarCmd.AddCommand(sidecarOtelCmd)
	sidecarOtelCmd.AddCommand(sidecarOtelComposeCmd)
}

func runSidecarOtelCompose(cmd *cobra.Command, args []string) error {
	username := args[0]
	containerName := username + "-container"

	client, err := incus.New()
	if err != nil {
		return fmt.Errorf("connect to Incus: %w", err)
	}
	cfg, _, err := client.GetRawInstance(containerName)
	if err != nil {
		return fmt.Errorf("get container %s: %w", containerName, err)
	}

	endpoint := cfg["environment.OTEL_EXPORTER_OTLP_ENDPOINT"]
	containerID := cfg["environment.CONTAINARIUM_CONTAINER_ID"]
	backendID := cfg["environment.CONTAINARIUM_BACKEND_ID"]
	tenantID := cfg["environment.CONTAINARIUM_TENANT_ID"]

	if endpoint == "" || containerID == "" || backendID == "" || tenantID == "" {
		return fmt.Errorf(
			"container %s is missing one or more required OTel env vars (monitoring not enabled?).\n"+
				"Enable with: containarium monitoring enable %s",
			containerName, username,
		)
	}

	// Sidecar image tag tracks the project version per
	// docs/PLATFORM-SIDECAR-DESIGN.md decision #4.
	imageTag := "v" + version.GetVersion()
	serviceName := username + "-otel"

	fmt.Print(renderOTelComposeSnippet(otelComposeInputs{
		ImageTag:            imageTag,
		ServiceName:         serviceName,
		Username:            username,
		ContainerEnvName:    containerID,
		BackendEnvValue:     backendID,
		TenantEnvValue:      tenantID,
		CollectorEnvValue:   endpoint,
	}))
	return nil
}

type otelComposeInputs struct {
	ImageTag          string
	ServiceName       string
	Username          string
	ContainerEnvName  string
	BackendEnvValue   string
	TenantEnvValue    string
	CollectorEnvValue string
}

// renderOTelComposeSnippet builds the compose YAML string. Pure
// function so it's trivially testable; the file-system / Incus calls
// live in the cobra Run handler.
func renderOTelComposeSnippet(in otelComposeInputs) string {
	var b strings.Builder
	fmt.Fprintf(&b, `# Generated by `+"`containarium sidecar otel compose %s`"+`.
# Paste this into the LXC's docker-compose.yml. The sidecar reads
# identity from compose ${VAR} interpolation against the LXC's env,
# which Containarium stamps via --monitoring; the values shown in
# comments below are what's currently stamped on this LXC.
#
# Reference the sidecar from each app service that should emit
# telemetry via:
#
#   services:
#     payment-api:
#       network_mode: "service:%s"
#       depends_on: [%s]
#       environment:
#         OTEL_EXPORTER_OTLP_ENDPOINT: http://localhost:4318
#         OTEL_SERVICE_NAME: payment-api   # per-service, tenant-controlled
#
# See docs/OTEL-AGENT-RELAY-DESIGN.md for the full pattern.

services:
  %s:
    image: ghcr.io/footprintai/containarium-otel-sidecar:%s
    restart: unless-stopped
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}    # currently: %s
      CONTAINARIUM_CONTAINER_ID:   ${CONTAINARIUM_CONTAINER_ID}      # currently: %s
      CONTAINARIUM_BACKEND_ID:     ${CONTAINARIUM_BACKEND_ID}        # currently: %s
      CONTAINARIUM_TENANT_ID:      ${CONTAINARIUM_TENANT_ID}         # currently: %s
      # Tenant-controlled; sidecar inserts service.version only if
      # this is set on the sidecar's env. Set per-app if you care
      # about canary / rollback metric breakdowns.
      SERVICE_VERSION: ${SERVICE_VERSION:-}
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:13133/"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
`,
		in.Username,
		in.ServiceName, in.ServiceName,
		in.ServiceName,
		in.ImageTag,
		in.CollectorEnvValue,
		in.ContainerEnvName,
		in.BackendEnvValue,
		in.TenantEnvValue,
	)
	return b.String()
}
