// VENDORED from Containarium-cloud: proto/containarium/cloud/v1/actuation_service.proto
// (cloud↔host actuation contract). Source of truth is the cloud repo; this copy
// lets the OSS daemon generate the host-side gRPC client WITHOUT depending on the
// private cloud Go module (which would break the public repo's go-mod-tidy CI gate
// + fork builds). Keep in sync with the cloud repo when the actuation contract
// changes. See docs/CLOUD-ACTUATION-CLIENT-DESIGN.md.
// actuation_service.proto — platform-daemon ⇄ cloud-daemon channel
// (host-side surface). See prd/cloud/container-actuation.md.
//
// Where host.proto carries the **registry** (sysadmin CRUD on the
// `hosts` table from the cloud operator's side), this proto carries
// the **runtime** (the platform-daemon's calls back to the cloud once
// it's registered).
//
// Auth is intentionally distinct: every RPC here is gated by the
// `host-bearer` metadata header (`HostBearerInterceptor` in
// internal/auth), not the user-facing JWT. The interceptor stamps
// the authenticated host's ID onto the context; handlers read it
// from ctx, not from request fields, so a malicious / buggy host
// can't masquerade as another by lying about its id in the body.
//
// Slice 1 ships **Heartbeat**. Slice 2 adds **ReportContainerState**
// (host's push of observed state). Slice 3 adds **WatchAssignments**
// — the cloud's push of desired state to the host over a server
// stream. Together these three RPCs are the full v1 actuation
// channel; the only remaining work is splitting `state` into
// desired/observed columns (separate migration) and wiring the
// scheduler to react to FAILED reports with reassignment.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: containarium/cloud/v1/actuation_service.proto

package cloudv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NetworkPolicyMode controls whether an org's egress policy is enforced or only
// observed on the host. Mirrors the OSS daemon's NetworkPolicyMode (the host's
// eBPF enforcer consumes it). Cross-org L2/L3 isolation is NOT this — that's the
// per-org bridge (data-isolation.md Layer 4). This policy is the EGRESS layer
// (allow-list + cloud-metadata block) the bridges don't provide.
type NetworkPolicyMode int32

const (
	NetworkPolicyMode_NETWORK_POLICY_MODE_UNSPECIFIED NetworkPolicyMode = 0 // host treats as LOG_ONLY
	NetworkPolicyMode_NETWORK_POLICY_MODE_LOG_ONLY    NetworkPolicyMode = 1 // observe + audit denied flows; drop nothing
	NetworkPolicyMode_NETWORK_POLICY_MODE_ENFORCE     NetworkPolicyMode = 2 // actually drop denied egress
)

// Enum value maps for NetworkPolicyMode.
var (
	NetworkPolicyMode_name = map[int32]string{
		0: "NETWORK_POLICY_MODE_UNSPECIFIED",
		1: "NETWORK_POLICY_MODE_LOG_ONLY",
		2: "NETWORK_POLICY_MODE_ENFORCE",
	}
	NetworkPolicyMode_value = map[string]int32{
		"NETWORK_POLICY_MODE_UNSPECIFIED": 0,
		"NETWORK_POLICY_MODE_LOG_ONLY":    1,
		"NETWORK_POLICY_MODE_ENFORCE":     2,
	}
)

func (x NetworkPolicyMode) Enum() *NetworkPolicyMode {
	p := new(NetworkPolicyMode)
	*p = x
	return p
}

func (x NetworkPolicyMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkPolicyMode) Descriptor() protoreflect.EnumDescriptor {
	return file_containarium_cloud_v1_actuation_service_proto_enumTypes[0].Descriptor()
}

func (NetworkPolicyMode) Type() protoreflect.EnumType {
	return &file_containarium_cloud_v1_actuation_service_proto_enumTypes[0]
}

func (x NetworkPolicyMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkPolicyMode.Descriptor instead.
func (NetworkPolicyMode) EnumDescriptor() ([]byte, []int) {
	return file_containarium_cloud_v1_actuation_service_proto_rawDescGZIP(), []int{0}
}

// HeartbeatRequest is intentionally empty for v1. The host's identity
// comes from the bearer; there's nothing else the cloud needs to
// know to bump last_heartbeat_at. Future fields (current observed
// state, host-side health flags) are additive.
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_containarium_cloud_v1_actuation_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_cloud_v1_actuation_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_containarium_cloud_v1_actuation_service_proto_rawDescGZIP(), []int{0}
}

type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server time when the heartbeat was recorded. Useful for hosts
	// that want to skew-correct their heartbeat scheduling against
	// the cloud's clock.
	ReceivedAt    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_containarium_cloud_v1_actuation_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_cloud_v1_actuation_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_containarium_cloud_v1_actuation_service_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatResponse) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

// ReportContainerStateRequest is a host's push of its current
// observation about a container it's been assigned.
type ReportContainerStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The container the host is reporting about. The host must hold a
	// live container_assignments row for this container; cross-host
	// reports collapse to NotFound for probe resistance (the calling
	// host can't tell whether the container exists on another host).
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// Observed state. Must match one of the AssignmentState* values
	// (pending / active / stopping / stopped). Empty rejected with
	// InvalidArgument; values outside the enum also InvalidArgument.
	State string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// When the host observed this state. Optional — defaults to the
	// server's clock at write time when zero. The server stamps its
	// own updated_at regardless; observed_at carries the host's view
	// for skew analysis but isn't currently used to gate writes.
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportContainerStateRequest) Reset() {
	*x = ReportContainerStateRequest{}
	mi := &file_containarium_cloud_v1_actuation_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportContainerStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportContainerStateRequest) ProtoMessage() {}

func (x *ReportContainerStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_cloud_v1_actuation_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportContainerStateRequest.ProtoReflect.Descriptor instead.
func (*ReportContainerStateRequest) Descriptor() ([]byte, []int) {
	return file_containarium_cloud_v1_actuation_service_proto_rawDescGZIP(), []int{2}
}

func (x *ReportContainerStateRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ReportContainerStateRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ReportContainerStateRequest) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

type ReportContainerStateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server time when the report was recorded.
	ReceivedAt    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportContainerStateResponse) Reset() {
	*x = ReportContainerStateResponse{}
	mi := &file_containarium_cloud_v1_actuation_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportContainerStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportContainerStateResponse) ProtoMessage() {}

func (x *ReportContainerStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_cloud_v1_actuation_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportContainerStateResponse.ProtoReflect.Descriptor instead.
func (*ReportContainerStateResponse) Descriptor() ([]byte, []int) {
	return file_containarium_cloud_v1_actuation_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReportContainerStateResponse) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

// WatchAssignmentsRequest carries no fields in v1 — the calling host's
// identity comes from the host-bearer header, and the response is
// always the full set of live assignments for that host.
type WatchAssignmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchAssignmentsRequest) Reset() {
	*x = WatchAssignmentsRequest{}
	mi := &file_containarium_cloud_v1_actuation_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchAssignmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchAssignmentsRequest) ProtoMessage() {}

func (x *WatchAssignmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_cloud_v1_actuation_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchAssignmentsRequest.ProtoReflect.Descriptor instead.
func (*WatchAssignmentsRequest) Descriptor() ([]byte, []int) {
	return file_containarium_cloud_v1_actuation_service_proto_rawDescGZIP(), []int{4}
}

// Assignment is the cloud's view of one container the host should be
// actuating. The fields needed to actually run the workload (name,
// image, capacity) are embedded so the host doesn't need a separate
// fetch round-trip.
type Assignment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-allocated id of the container_assignments row. Hosts use
	// this for idempotency / dedup across reconnects.
	AssignmentId string `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	// Container the assignment targets. Used by the host as the key
	// when calling ReportContainerState.
	ContainerId string `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// Host-observed state — what ReportContainerState last wrote
	// (pending / active / stopping / stopped). Echoed back to the
	// host so a freshly-connected daemon can see what the cloud
	// currently believes.
	State string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	// Cloud-driven user intent (running / stopped / deleted). The
	// host's reconciliation loop reads THIS field to decide whether
	// to start, stop, or tear down the container. Distinct from
	// `state` (observed) — see prd/cloud/container-actuation.md for
	// the desired_state vs observed_state split rationale.
	//
	// Slice 1 surfaces the field; the OSS daemon does not yet act
	// on it (cross-repo follow-up). Until then, this field is
	// informational — useful for the dashboard but the host keeps
	// running whatever it was already running.
	DesiredState string `protobuf:"bytes,4,opt,name=desired_state,json=desiredState,proto3" json:"desired_state,omitempty"`
	// Owning org (tenant) of this container. A host serves many orgs; the
	// host-side daemon uses this to (a) stamp the container's
	// `user.containarium.tenant` label so its per-tenant network-policy enforcer
	// can identify it (cloud containers are named `cld-<uuid>`, not
	// `<tenant>-container`), and (b) select which org's egress policy in
	// network_policies (on the batch) applies. See the OSS repo's
	// docs/security/NETWORK-ISOLATION-DESIGN.md "Cloud extension".
	OrgId string `protobuf:"bytes,5,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Container spec — embedded so the host doesn't need to fetch.
	Name     string `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	Image    string `protobuf:"bytes,11,opt,name=image,proto3" json:"image,omitempty"`
	RamMb    int32  `protobuf:"varint,12,opt,name=ram_mb,json=ramMb,proto3" json:"ram_mb,omitempty"`
	DiskGb   int32  `protobuf:"varint,13,opt,name=disk_gb,json=diskGb,proto3" json:"disk_gb,omitempty"`
	GpuCount int32  `protobuf:"varint,14,opt,name=gpu_count,json=gpuCount,proto3" json:"gpu_count,omitempty"`
	// Routes to expose for this container (hostname → container port). The host
	// registers each with its edge (Caddy) so the workload is reachable. Full set
	// for the container; empty = no inbound routes.
	Routes []*PortRoute `protobuf:"bytes,15,rep,name=routes,proto3" json:"routes,omitempty"`
	// Secret environment variables to inject into the container (name → value).
	// Carried so the host stamps them at create. EMPTY for now — the cloud has no
	// per-container secrets model yet; this is the forward contract the OSS host
	// already applies (as container env) once the cloud populates it.
	SecretEnv     map[string]string      `protobuf:"bytes,16,rep,name=secret_env,json=secretEnv,proto3" json:"secret_env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_containarium_cloud_v1_actuation_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_cloud_v1_actuation_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_containarium_cloud_v1_actuation_service_proto_rawDescGZIP(), []int{5}
}

func (x *Assignment) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *Assignment) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *Assignment) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Assignment) GetDesiredState() string {
	if x != nil {
		return x.DesiredState
	}
	return ""
}

func (x *Assignment) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Assignment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Assignment) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Assignment) GetRamMb() int32 {
	if x != nil {
		return x.RamMb
	}
	return 0
}

func (x *Assignment) GetDiskGb() int32 {
	if x != nil {
		return x.DiskGb
	}
	return 0
}

func (x *Assignment) GetGpuCount() int32 {
	if x != nil {
		return x.GpuCount
	}
	return 0
}

func (x *Assignment) GetRoutes() []*PortRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *Assignment) GetSecretEnv() map[string]string {
	if x != nil {
		return x.SecretEnv
	}
	return nil
}

func (x *Assignment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// PortRoute is one hostname→container-port exposure (mirrors the cloud Route
// model: Domain, TargetPort, Protocol).
type PortRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	TargetPort    int32                  `protobuf:"varint,2,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"` // "http" | "https" | "tcp"; empty defaults to http
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortRoute) Reset() {
	*x = PortRoute{}
	mi := &file_containarium_cloud_v1_actuation_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortRoute) ProtoMessage() {}

func (x *PortRoute) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_cloud_v1_actuation_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortRoute.ProtoReflect.Descriptor instead.
func (*PortRoute) Descriptor() ([]byte, []int) {
	return file_containarium_cloud_v1_actuation_service_proto_rawDescGZIP(), []int{6}
}

func (x *PortRoute) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *PortRoute) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *PortRoute) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

// NetworkPolicy is one org's egress policy, applied on the host by the eBPF
// network-policy enforcer to every container of that org. It is org-scoped, not
// per-container — all of an org's containers share it. The host writes it into
// its local NetworkPolicyStore keyed by org_id; the enforcer's reconcile loop
// then applies it unchanged.
type NetworkPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Org this policy applies to (matches Assignment.org_id).
	OrgId string `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Allow container↔container traffic within the same org. On a per-org bridge
	// this is effectively always true (every peer is same-org); carried for
	// completeness and for shared-bridge deployments.
	AllowIntraTenant bool `protobuf:"varint,2,opt,name=allow_intra_tenant,json=allowIntraTenant,proto3" json:"allow_intra_tenant,omitempty"`
	// Allowed egress destination CIDRs (e.g. "10.0.0.0/8", "1.2.3.4/32").
	EgressCidrs []string `protobuf:"bytes,3,rep,name=egress_cidrs,json=egressCidrs,proto3" json:"egress_cidrs,omitempty"`
	// Allowed egress domains (e.g. "api.github.com"); the host resolves these to
	// IPs on a refresh loop and folds them into the egress allow-set.
	EgressDomains []string `protobuf:"bytes,4,rep,name=egress_domains,json=egressDomains,proto3" json:"egress_domains,omitempty"`
	// Allow reaching the cloud metadata service (169.254.169.254). Default false:
	// denied even if egress_cidrs/egress_domains would cover it (it hands out the
	// instance's cloud credentials).
	AllowMetadata bool `protobuf:"varint,5,opt,name=allow_metadata,json=allowMetadata,proto3" json:"allow_metadata,omitempty"`
	// Enforcement mode. Unspecified is treated as LOG_ONLY.
	Mode          NetworkPolicyMode `protobuf:"varint,6,opt,name=mode,proto3,enum=containarium.cloud.v1.NetworkPolicyMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicy) Reset() {
	*x = NetworkPolicy{}
	mi := &file_containarium_cloud_v1_actuation_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicy) ProtoMessage() {}

func (x *NetworkPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_cloud_v1_actuation_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicy.ProtoReflect.Descriptor instead.
func (*NetworkPolicy) Descriptor() ([]byte, []int) {
	return file_containarium_cloud_v1_actuation_service_proto_rawDescGZIP(), []int{7}
}

func (x *NetworkPolicy) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *NetworkPolicy) GetAllowIntraTenant() bool {
	if x != nil {
		return x.AllowIntraTenant
	}
	return false
}

func (x *NetworkPolicy) GetEgressCidrs() []string {
	if x != nil {
		return x.EgressCidrs
	}
	return nil
}

func (x *NetworkPolicy) GetEgressDomains() []string {
	if x != nil {
		return x.EgressDomains
	}
	return nil
}

func (x *NetworkPolicy) GetAllowMetadata() bool {
	if x != nil {
		return x.AllowMetadata
	}
	return false
}

func (x *NetworkPolicy) GetMode() NetworkPolicyMode {
	if x != nil {
		return x.Mode
	}
	return NetworkPolicyMode_NETWORK_POLICY_MODE_UNSPECIFIED
}

// AssignmentBatch is a full-state snapshot, not a delta. Each batch
// replaces the host's understanding entirely — the cloud is the
// authority. v1 always sends the complete set so the host can
// converge with a single pass; future slices may introduce deltas
// once the protocol grows generation numbers per assignment.
type AssignmentBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full set of live assignments for the calling host.
	Assignments []*Assignment `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"`
	// Server time when this batch was assembled. Useful for hosts
	// diagnosing skew against their own clock; not currently used to
	// gate writes.
	GeneratedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	// Egress policy for every org with containers on this host (org-scoped). A
	// full snapshot like assignments — the host converges its NetworkPolicyStore
	// to exactly this set. Empty until the cloud authors policies; an org absent
	// here gets the host's default (deny-by-default in enforce, observe in
	// log_only). #315 cloud extension.
	NetworkPolicies []*NetworkPolicy `protobuf:"bytes,3,rep,name=network_policies,json=networkPolicies,proto3" json:"network_policies,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AssignmentBatch) Reset() {
	*x = AssignmentBatch{}
	mi := &file_containarium_cloud_v1_actuation_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignmentBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignmentBatch) ProtoMessage() {}

func (x *AssignmentBatch) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_cloud_v1_actuation_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignmentBatch.ProtoReflect.Descriptor instead.
func (*AssignmentBatch) Descriptor() ([]byte, []int) {
	return file_containarium_cloud_v1_actuation_service_proto_rawDescGZIP(), []int{8}
}

func (x *AssignmentBatch) GetAssignments() []*Assignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

func (x *AssignmentBatch) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *AssignmentBatch) GetNetworkPolicies() []*NetworkPolicy {
	if x != nil {
		return x.NetworkPolicies
	}
	return nil
}

var File_containarium_cloud_v1_actuation_service_proto protoreflect.FileDescriptor

const file_containarium_cloud_v1_actuation_service_proto_rawDesc = "" +
	"\n" +
	"-containarium/cloud/v1/actuation_service.proto\x12\x15containarium.cloud.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x12\n" +
	"\x10HeartbeatRequest\"P\n" +
	"\x11HeartbeatResponse\x12;\n" +
	"\vreceived_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\"\x93\x01\n" +
	"\x1bReportContainerStateRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12;\n" +
	"\vobserved_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\"[\n" +
	"\x1cReportContainerStateResponse\x12;\n" +
	"\vreceived_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\"\x19\n" +
	"\x17WatchAssignmentsRequest\"\xa1\x04\n" +
	"\n" +
	"Assignment\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12#\n" +
	"\rdesired_state\x18\x04 \x01(\tR\fdesiredState\x12\x15\n" +
	"\x06org_id\x18\x05 \x01(\tR\x05orgId\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\v \x01(\tR\x05image\x12\x15\n" +
	"\x06ram_mb\x18\f \x01(\x05R\x05ramMb\x12\x17\n" +
	"\adisk_gb\x18\r \x01(\x05R\x06diskGb\x12\x1b\n" +
	"\tgpu_count\x18\x0e \x01(\x05R\bgpuCount\x128\n" +
	"\x06routes\x18\x0f \x03(\v2 .containarium.cloud.v1.PortRouteR\x06routes\x12O\n" +
	"\n" +
	"secret_env\x18\x10 \x03(\v20.containarium.cloud.v1.Assignment.SecretEnvEntryR\tsecretEnv\x129\n" +
	"\n" +
	"updated_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a<\n" +
	"\x0eSecretEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\tPortRoute\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x1f\n" +
	"\vtarget_port\x18\x02 \x01(\x05R\n" +
	"targetPort\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"\x83\x02\n" +
	"\rNetworkPolicy\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12,\n" +
	"\x12allow_intra_tenant\x18\x02 \x01(\bR\x10allowIntraTenant\x12!\n" +
	"\fegress_cidrs\x18\x03 \x03(\tR\vegressCidrs\x12%\n" +
	"\x0eegress_domains\x18\x04 \x03(\tR\regressDomains\x12%\n" +
	"\x0eallow_metadata\x18\x05 \x01(\bR\rallowMetadata\x12<\n" +
	"\x04mode\x18\x06 \x01(\x0e2(.containarium.cloud.v1.NetworkPolicyModeR\x04mode\"\xe6\x01\n" +
	"\x0fAssignmentBatch\x12C\n" +
	"\vassignments\x18\x01 \x03(\v2!.containarium.cloud.v1.AssignmentR\vassignments\x12=\n" +
	"\fgenerated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12O\n" +
	"\x10network_policies\x18\x03 \x03(\v2$.containarium.cloud.v1.NetworkPolicyR\x0fnetworkPolicies*{\n" +
	"\x11NetworkPolicyMode\x12#\n" +
	"\x1fNETWORK_POLICY_MODE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cNETWORK_POLICY_MODE_LOG_ONLY\x10\x01\x12\x1f\n" +
	"\x1bNETWORK_POLICY_MODE_ENFORCE\x10\x022\xc1\x03\n" +
	"\x10ActuationService\x12\x82\x01\n" +
	"\tHeartbeat\x12'.containarium.cloud.v1.HeartbeatRequest\x1a(.containarium.cloud.v1.HeartbeatResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/actuation/heartbeat\x12\xb9\x01\n" +
	"\x14ReportContainerState\x122.containarium.cloud.v1.ReportContainerStateRequest\x1a3.containarium.cloud.v1.ReportContainerStateResponse\"8\x82\xd3\xe4\x93\x022:\x01*\"-/v1/actuation/containers/{container_id}/state\x12l\n" +
	"\x10WatchAssignments\x12..containarium.cloud.v1.WatchAssignmentsRequest\x1a&.containarium.cloud.v1.AssignmentBatch0\x01BJZHgithub.com/footprintai/containarium/pkg/pb/containarium/cloud/v1;cloudv1b\x06proto3"

var (
	file_containarium_cloud_v1_actuation_service_proto_rawDescOnce sync.Once
	file_containarium_cloud_v1_actuation_service_proto_rawDescData []byte
)

func file_containarium_cloud_v1_actuation_service_proto_rawDescGZIP() []byte {
	file_containarium_cloud_v1_actuation_service_proto_rawDescOnce.Do(func() {
		file_containarium_cloud_v1_actuation_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_containarium_cloud_v1_actuation_service_proto_rawDesc), len(file_containarium_cloud_v1_actuation_service_proto_rawDesc)))
	})
	return file_containarium_cloud_v1_actuation_service_proto_rawDescData
}

var file_containarium_cloud_v1_actuation_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_containarium_cloud_v1_actuation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_containarium_cloud_v1_actuation_service_proto_goTypes = []any{
	(NetworkPolicyMode)(0),               // 0: containarium.cloud.v1.NetworkPolicyMode
	(*HeartbeatRequest)(nil),             // 1: containarium.cloud.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),            // 2: containarium.cloud.v1.HeartbeatResponse
	(*ReportContainerStateRequest)(nil),  // 3: containarium.cloud.v1.ReportContainerStateRequest
	(*ReportContainerStateResponse)(nil), // 4: containarium.cloud.v1.ReportContainerStateResponse
	(*WatchAssignmentsRequest)(nil),      // 5: containarium.cloud.v1.WatchAssignmentsRequest
	(*Assignment)(nil),                   // 6: containarium.cloud.v1.Assignment
	(*PortRoute)(nil),                    // 7: containarium.cloud.v1.PortRoute
	(*NetworkPolicy)(nil),                // 8: containarium.cloud.v1.NetworkPolicy
	(*AssignmentBatch)(nil),              // 9: containarium.cloud.v1.AssignmentBatch
	nil,                                  // 10: containarium.cloud.v1.Assignment.SecretEnvEntry
	(*timestamppb.Timestamp)(nil),        // 11: google.protobuf.Timestamp
}
var file_containarium_cloud_v1_actuation_service_proto_depIdxs = []int32{
	11, // 0: containarium.cloud.v1.HeartbeatResponse.received_at:type_name -> google.protobuf.Timestamp
	11, // 1: containarium.cloud.v1.ReportContainerStateRequest.observed_at:type_name -> google.protobuf.Timestamp
	11, // 2: containarium.cloud.v1.ReportContainerStateResponse.received_at:type_name -> google.protobuf.Timestamp
	7,  // 3: containarium.cloud.v1.Assignment.routes:type_name -> containarium.cloud.v1.PortRoute
	10, // 4: containarium.cloud.v1.Assignment.secret_env:type_name -> containarium.cloud.v1.Assignment.SecretEnvEntry
	11, // 5: containarium.cloud.v1.Assignment.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 6: containarium.cloud.v1.NetworkPolicy.mode:type_name -> containarium.cloud.v1.NetworkPolicyMode
	6,  // 7: containarium.cloud.v1.AssignmentBatch.assignments:type_name -> containarium.cloud.v1.Assignment
	11, // 8: containarium.cloud.v1.AssignmentBatch.generated_at:type_name -> google.protobuf.Timestamp
	8,  // 9: containarium.cloud.v1.AssignmentBatch.network_policies:type_name -> containarium.cloud.v1.NetworkPolicy
	1,  // 10: containarium.cloud.v1.ActuationService.Heartbeat:input_type -> containarium.cloud.v1.HeartbeatRequest
	3,  // 11: containarium.cloud.v1.ActuationService.ReportContainerState:input_type -> containarium.cloud.v1.ReportContainerStateRequest
	5,  // 12: containarium.cloud.v1.ActuationService.WatchAssignments:input_type -> containarium.cloud.v1.WatchAssignmentsRequest
	2,  // 13: containarium.cloud.v1.ActuationService.Heartbeat:output_type -> containarium.cloud.v1.HeartbeatResponse
	4,  // 14: containarium.cloud.v1.ActuationService.ReportContainerState:output_type -> containarium.cloud.v1.ReportContainerStateResponse
	9,  // 15: containarium.cloud.v1.ActuationService.WatchAssignments:output_type -> containarium.cloud.v1.AssignmentBatch
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_containarium_cloud_v1_actuation_service_proto_init() }
func file_containarium_cloud_v1_actuation_service_proto_init() {
	if File_containarium_cloud_v1_actuation_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_containarium_cloud_v1_actuation_service_proto_rawDesc), len(file_containarium_cloud_v1_actuation_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_containarium_cloud_v1_actuation_service_proto_goTypes,
		DependencyIndexes: file_containarium_cloud_v1_actuation_service_proto_depIdxs,
		EnumInfos:         file_containarium_cloud_v1_actuation_service_proto_enumTypes,
		MessageInfos:      file_containarium_cloud_v1_actuation_service_proto_msgTypes,
	}.Build()
	File_containarium_cloud_v1_actuation_service_proto = out.File
	file_containarium_cloud_v1_actuation_service_proto_goTypes = nil
	file_containarium_cloud_v1_actuation_service_proto_depIdxs = nil
}
