#!/bin/bash
set -euo pipefail

# Sentinel VM startup script — minimal setup
# Only installs the containarium binary and runs it in sentinel mode.
# No Incus, no Caddy, no ZFS — just networking and the binary.

exec 1> >(logger -s -t containarium-sentinel-startup) 2>&1
echo "=== Containarium Sentinel Startup ==="

# Template variables
ADMIN_USERS="${join(",", admin_users)}"
CONTAINARIUM_BINARY_URL="${containarium_binary_url}"
SPOT_VM_NAME="${spot_vm_name}"
ZONE="${zone}"
PROJECT_ID="${project_id}"

# System update (minimal)
apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq curl fail2ban > /dev/null

# Harden SSH — sshd listens on port 2222 ONLY (management/IAP access)
# Port 22 is now owned by sshpiper (SSH reverse proxy with fail-to-ban)
cat > /etc/ssh/sshd_config.d/containarium.conf <<EOF
PasswordAuthentication no
PubkeyAuthentication yes
PermitRootLogin no
EOF
# Set sshd to port 2222 only — port 22 is reserved for sshpiper
sed -i '/^Port /d' /etc/ssh/sshd_config
echo "Port 2222" >> /etc/ssh/sshd_config
# Ubuntu 24.04 uses systemd socket activation — override ssh.socket too
mkdir -p /etc/systemd/system/ssh.socket.d
cat > /etc/systemd/system/ssh.socket.d/override.conf <<EOF
[Socket]
ListenStream=
ListenStream=0.0.0.0:2222
ListenStream=[::]:2222
EOF
systemctl daemon-reload
systemctl restart ssh.socket || true
systemctl restart ssh || systemctl restart sshd || true

# Create admin users
IFS=',' read -ra USERS <<< "$ADMIN_USERS"
for username in "$${USERS[@]}"; do
    username=$(echo "$username" | xargs)
    if [ -z "$username" ]; then continue; fi
    if ! id "$username" &>/dev/null; then
        useradd -m -s /bin/bash -G sudo "$username"
        echo "$username ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/"$username"
        chmod 440 /etc/sudoers.d/"$username"
        mkdir -p /home/"$username"/.ssh
        chmod 700 /home/"$username"/.ssh
        chown -R "$username":"$username" /home/"$username"/.ssh
    fi
done

# Install sshpiper — SSH reverse proxy with built-in fail-to-ban
# sshpiper sits on port 22, sees real client IPs, and bans after failed auths
echo "==> Installing sshpiper..."
SSHPIPER_VERSION="v1.5.3"
if [ ! -f /usr/local/bin/sshpiperd ]; then
    cd /tmp
    curl -fsSL "https://github.com/tg123/sshpiper/releases/download/$${SSHPIPER_VERSION}/sshpiperd_with_plugins_linux_x86_64.tar.gz" \
      -o sshpiper.tar.gz
    tar xzf sshpiper.tar.gz
    mv sshpiperd /usr/local/bin/sshpiperd
    chmod +x /usr/local/bin/sshpiperd
    # Plugins are separate binaries (yaml, failtoban, etc.)
    cp plugins/* /usr/local/bin/
    chmod +x /usr/local/bin/yaml /usr/local/bin/failtoban
    rm -rf sshpiper.tar.gz plugins LICENSE README.md
    echo "sshpiper $${SSHPIPER_VERSION} installed"
else
    echo "sshpiper already installed"
fi

# Generate sshpiper host key + upstream key for authenticating to spot VM
mkdir -p /etc/sshpiper/users
if [ ! -f /etc/sshpiper/host_key ]; then
    ssh-keygen -t ed25519 -f /etc/sshpiper/host_key -N ""
    echo "sshpiper host key generated"
fi
if [ ! -f /etc/sshpiper/upstream_key ]; then
    ssh-keygen -t ed25519 -f /etc/sshpiper/upstream_key -N ""
    echo "sshpiper upstream key generated"
fi

# Create sshpiper systemd service
cat > /etc/systemd/system/sshpiper.service <<'EOF'
[Unit]
Description=SSHPiper reverse proxy
After=network.target

[Service]
ExecStart=/usr/local/bin/sshpiperd \
  -i /etc/sshpiper/host_key \
  -p 22 \
  --drop-hostkeys-message \
  yaml \
  --config /etc/sshpiper/config.yaml \
  -- \
  failtoban \
  --max-failures 3 \
  --ban-duration 1h
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable sshpiper
# sshpiper will be started after config.yaml is generated by the sentinel key sync
echo "sshpiper service installed (will start after config is generated)"

# Download containarium binary
if [ -n "$CONTAINARIUM_BINARY_URL" ]; then
    echo "Downloading containarium from $CONTAINARIUM_BINARY_URL"
    curl -fsSL "$CONTAINARIUM_BINARY_URL" -o /usr/local/bin/containarium
    chmod +x /usr/local/bin/containarium
    echo "Containarium version: $(/usr/local/bin/containarium version 2>/dev/null || echo 'unknown')"
fi

# Install and start sentinel service
if [ -f /usr/local/bin/containarium ]; then
    /usr/local/bin/containarium sentinel service install \
        --spot-vm "$SPOT_VM_NAME" \
        --zone "$ZONE" \
        --project "$PROJECT_ID"
    echo "Sentinel service installed and running"
else
    echo "WARNING: containarium binary not found, sentinel not started"
fi

echo "=== Sentinel Startup Complete ==="
