// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: containarium/v1/agent.proto

package containariumv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentSkillService_ListAgentSkills_FullMethodName   = "/containarium.v1.AgentSkillService/ListAgentSkills"
	AgentSkillService_GetAgentSkill_FullMethodName     = "/containarium.v1.AgentSkillService/GetAgentSkill"
	AgentSkillService_RunAgentSkill_FullMethodName     = "/containarium.v1.AgentSkillService/RunAgentSkill"
	AgentSkillService_SendAgentTask_FullMethodName     = "/containarium.v1.AgentSkillService/SendAgentTask"
	AgentSkillService_EnqueueAgentTask_FullMethodName  = "/containarium.v1.AgentSkillService/EnqueueAgentTask"
	AgentSkillService_LeaseAgentTask_FullMethodName    = "/containarium.v1.AgentSkillService/LeaseAgentTask"
	AgentSkillService_CompleteAgentTask_FullMethodName = "/containarium.v1.AgentSkillService/CompleteAgentTask"
	AgentSkillService_StartAgentWorker_FullMethodName  = "/containarium.v1.AgentSkillService/StartAgentWorker"
)

// AgentSkillServiceClient is the client API for AgentSkillService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentSkillService manages and runs individual packaged agents.
type AgentSkillServiceClient interface {
	// ListAgentSkills returns all available skills (built-in + registered).
	ListAgentSkills(ctx context.Context, in *ListAgentSkillsRequest, opts ...grpc.CallOption) (*ListAgentSkillsResponse, error)
	// GetAgentSkill returns a single skill definition by id.
	GetAgentSkill(ctx context.Context, in *GetAgentSkillRequest, opts ...grpc.CallOption) (*GetAgentSkillResponse, error)
	// RunAgentSkill launches a single skill in a box and runs one task against
	// it. The agent's JWT is minted with exactly the skill's allowed_scopes.
	RunAgentSkill(ctx context.Context, in *RunAgentSkillRequest, opts ...grpc.CallOption) (*RunAgentSkillResponse, error)
	// SendAgentTask delegates a task to a running peer agent over A2A and returns
	// the peer's artifact. Phase 1 establishes the transport; Phase 2 adds the
	// allowed_peers / network-policy enforcement around it. (Server impl: #569.)
	SendAgentTask(ctx context.Context, in *SendAgentTaskRequest, opts ...grpc.CallOption) (*SendAgentTaskResponse, error)
	// EnqueueAgentTask places a task on the queue for the given skill and returns
	// its id. Producer side of the pull model.
	EnqueueAgentTask(ctx context.Context, in *EnqueueAgentTaskRequest, opts ...grpc.CallOption) (*EnqueueAgentTaskResponse, error)
	// LeaseAgentTask hands the caller the next visible task (optionally filtered
	// to one skill), making it invisible for lease_seconds. Returns has_task=false
	// when the queue is empty. Worker poll side of the pull model.
	LeaseAgentTask(ctx context.Context, in *LeaseAgentTaskRequest, opts ...grpc.CallOption) (*LeaseAgentTaskResponse, error)
	// CompleteAgentTask reports a leased task's result (artifact or error) and
	// removes it from the queue. Rejected (accepted=false) if the lease token is
	// stale — i.e. the lease already expired and the task was redelivered.
	CompleteAgentTask(ctx context.Context, in *CompleteAgentTaskRequest, opts ...grpc.CallOption) (*CompleteAgentTaskResponse, error)
	// StartAgentWorker provisions (or reuses) a skill's box and launches the
	// in-box runtime in poll mode: a long-lived worker that leases tasks for the
	// skill, runs them, and reports back — the consumer side of the pull model.
	// The daemon mints a SEPARATE queue credential (a JWT scoped to agents:run,
	// distinct from the skill's in-box token) and seeds it so the box can reach
	// the queue endpoints; the worker resolves the daemon URL from its default
	// route (the backend host) at launch.
	StartAgentWorker(ctx context.Context, in *StartAgentWorkerRequest, opts ...grpc.CallOption) (*StartAgentWorkerResponse, error)
}

type agentSkillServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentSkillServiceClient(cc grpc.ClientConnInterface) AgentSkillServiceClient {
	return &agentSkillServiceClient{cc}
}

func (c *agentSkillServiceClient) ListAgentSkills(ctx context.Context, in *ListAgentSkillsRequest, opts ...grpc.CallOption) (*ListAgentSkillsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentSkillsResponse)
	err := c.cc.Invoke(ctx, AgentSkillService_ListAgentSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSkillServiceClient) GetAgentSkill(ctx context.Context, in *GetAgentSkillRequest, opts ...grpc.CallOption) (*GetAgentSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentSkillResponse)
	err := c.cc.Invoke(ctx, AgentSkillService_GetAgentSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSkillServiceClient) RunAgentSkill(ctx context.Context, in *RunAgentSkillRequest, opts ...grpc.CallOption) (*RunAgentSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunAgentSkillResponse)
	err := c.cc.Invoke(ctx, AgentSkillService_RunAgentSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSkillServiceClient) SendAgentTask(ctx context.Context, in *SendAgentTaskRequest, opts ...grpc.CallOption) (*SendAgentTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendAgentTaskResponse)
	err := c.cc.Invoke(ctx, AgentSkillService_SendAgentTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSkillServiceClient) EnqueueAgentTask(ctx context.Context, in *EnqueueAgentTaskRequest, opts ...grpc.CallOption) (*EnqueueAgentTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueAgentTaskResponse)
	err := c.cc.Invoke(ctx, AgentSkillService_EnqueueAgentTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSkillServiceClient) LeaseAgentTask(ctx context.Context, in *LeaseAgentTaskRequest, opts ...grpc.CallOption) (*LeaseAgentTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaseAgentTaskResponse)
	err := c.cc.Invoke(ctx, AgentSkillService_LeaseAgentTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSkillServiceClient) CompleteAgentTask(ctx context.Context, in *CompleteAgentTaskRequest, opts ...grpc.CallOption) (*CompleteAgentTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteAgentTaskResponse)
	err := c.cc.Invoke(ctx, AgentSkillService_CompleteAgentTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSkillServiceClient) StartAgentWorker(ctx context.Context, in *StartAgentWorkerRequest, opts ...grpc.CallOption) (*StartAgentWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartAgentWorkerResponse)
	err := c.cc.Invoke(ctx, AgentSkillService_StartAgentWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentSkillServiceServer is the server API for AgentSkillService service.
// All implementations must embed UnimplementedAgentSkillServiceServer
// for forward compatibility.
//
// AgentSkillService manages and runs individual packaged agents.
type AgentSkillServiceServer interface {
	// ListAgentSkills returns all available skills (built-in + registered).
	ListAgentSkills(context.Context, *ListAgentSkillsRequest) (*ListAgentSkillsResponse, error)
	// GetAgentSkill returns a single skill definition by id.
	GetAgentSkill(context.Context, *GetAgentSkillRequest) (*GetAgentSkillResponse, error)
	// RunAgentSkill launches a single skill in a box and runs one task against
	// it. The agent's JWT is minted with exactly the skill's allowed_scopes.
	RunAgentSkill(context.Context, *RunAgentSkillRequest) (*RunAgentSkillResponse, error)
	// SendAgentTask delegates a task to a running peer agent over A2A and returns
	// the peer's artifact. Phase 1 establishes the transport; Phase 2 adds the
	// allowed_peers / network-policy enforcement around it. (Server impl: #569.)
	SendAgentTask(context.Context, *SendAgentTaskRequest) (*SendAgentTaskResponse, error)
	// EnqueueAgentTask places a task on the queue for the given skill and returns
	// its id. Producer side of the pull model.
	EnqueueAgentTask(context.Context, *EnqueueAgentTaskRequest) (*EnqueueAgentTaskResponse, error)
	// LeaseAgentTask hands the caller the next visible task (optionally filtered
	// to one skill), making it invisible for lease_seconds. Returns has_task=false
	// when the queue is empty. Worker poll side of the pull model.
	LeaseAgentTask(context.Context, *LeaseAgentTaskRequest) (*LeaseAgentTaskResponse, error)
	// CompleteAgentTask reports a leased task's result (artifact or error) and
	// removes it from the queue. Rejected (accepted=false) if the lease token is
	// stale — i.e. the lease already expired and the task was redelivered.
	CompleteAgentTask(context.Context, *CompleteAgentTaskRequest) (*CompleteAgentTaskResponse, error)
	// StartAgentWorker provisions (or reuses) a skill's box and launches the
	// in-box runtime in poll mode: a long-lived worker that leases tasks for the
	// skill, runs them, and reports back — the consumer side of the pull model.
	// The daemon mints a SEPARATE queue credential (a JWT scoped to agents:run,
	// distinct from the skill's in-box token) and seeds it so the box can reach
	// the queue endpoints; the worker resolves the daemon URL from its default
	// route (the backend host) at launch.
	StartAgentWorker(context.Context, *StartAgentWorkerRequest) (*StartAgentWorkerResponse, error)
	mustEmbedUnimplementedAgentSkillServiceServer()
}

// UnimplementedAgentSkillServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentSkillServiceServer struct{}

func (UnimplementedAgentSkillServiceServer) ListAgentSkills(context.Context, *ListAgentSkillsRequest) (*ListAgentSkillsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgentSkills not implemented")
}
func (UnimplementedAgentSkillServiceServer) GetAgentSkill(context.Context, *GetAgentSkillRequest) (*GetAgentSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentSkill not implemented")
}
func (UnimplementedAgentSkillServiceServer) RunAgentSkill(context.Context, *RunAgentSkillRequest) (*RunAgentSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunAgentSkill not implemented")
}
func (UnimplementedAgentSkillServiceServer) SendAgentTask(context.Context, *SendAgentTaskRequest) (*SendAgentTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendAgentTask not implemented")
}
func (UnimplementedAgentSkillServiceServer) EnqueueAgentTask(context.Context, *EnqueueAgentTaskRequest) (*EnqueueAgentTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnqueueAgentTask not implemented")
}
func (UnimplementedAgentSkillServiceServer) LeaseAgentTask(context.Context, *LeaseAgentTaskRequest) (*LeaseAgentTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaseAgentTask not implemented")
}
func (UnimplementedAgentSkillServiceServer) CompleteAgentTask(context.Context, *CompleteAgentTaskRequest) (*CompleteAgentTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteAgentTask not implemented")
}
func (UnimplementedAgentSkillServiceServer) StartAgentWorker(context.Context, *StartAgentWorkerRequest) (*StartAgentWorkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartAgentWorker not implemented")
}
func (UnimplementedAgentSkillServiceServer) mustEmbedUnimplementedAgentSkillServiceServer() {}
func (UnimplementedAgentSkillServiceServer) testEmbeddedByValue()                           {}

// UnsafeAgentSkillServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentSkillServiceServer will
// result in compilation errors.
type UnsafeAgentSkillServiceServer interface {
	mustEmbedUnimplementedAgentSkillServiceServer()
}

func RegisterAgentSkillServiceServer(s grpc.ServiceRegistrar, srv AgentSkillServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentSkillServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentSkillService_ServiceDesc, srv)
}

func _AgentSkillService_ListAgentSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentSkillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSkillServiceServer).ListAgentSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSkillService_ListAgentSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSkillServiceServer).ListAgentSkills(ctx, req.(*ListAgentSkillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentSkillService_GetAgentSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSkillServiceServer).GetAgentSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSkillService_GetAgentSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSkillServiceServer).GetAgentSkill(ctx, req.(*GetAgentSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentSkillService_RunAgentSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunAgentSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSkillServiceServer).RunAgentSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSkillService_RunAgentSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSkillServiceServer).RunAgentSkill(ctx, req.(*RunAgentSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentSkillService_SendAgentTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendAgentTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSkillServiceServer).SendAgentTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSkillService_SendAgentTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSkillServiceServer).SendAgentTask(ctx, req.(*SendAgentTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentSkillService_EnqueueAgentTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueAgentTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSkillServiceServer).EnqueueAgentTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSkillService_EnqueueAgentTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSkillServiceServer).EnqueueAgentTask(ctx, req.(*EnqueueAgentTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentSkillService_LeaseAgentTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaseAgentTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSkillServiceServer).LeaseAgentTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSkillService_LeaseAgentTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSkillServiceServer).LeaseAgentTask(ctx, req.(*LeaseAgentTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentSkillService_CompleteAgentTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteAgentTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSkillServiceServer).CompleteAgentTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSkillService_CompleteAgentTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSkillServiceServer).CompleteAgentTask(ctx, req.(*CompleteAgentTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentSkillService_StartAgentWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAgentWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSkillServiceServer).StartAgentWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentSkillService_StartAgentWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSkillServiceServer).StartAgentWorker(ctx, req.(*StartAgentWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentSkillService_ServiceDesc is the grpc.ServiceDesc for AgentSkillService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentSkillService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "containarium.v1.AgentSkillService",
	HandlerType: (*AgentSkillServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAgentSkills",
			Handler:    _AgentSkillService_ListAgentSkills_Handler,
		},
		{
			MethodName: "GetAgentSkill",
			Handler:    _AgentSkillService_GetAgentSkill_Handler,
		},
		{
			MethodName: "RunAgentSkill",
			Handler:    _AgentSkillService_RunAgentSkill_Handler,
		},
		{
			MethodName: "SendAgentTask",
			Handler:    _AgentSkillService_SendAgentTask_Handler,
		},
		{
			MethodName: "EnqueueAgentTask",
			Handler:    _AgentSkillService_EnqueueAgentTask_Handler,
		},
		{
			MethodName: "LeaseAgentTask",
			Handler:    _AgentSkillService_LeaseAgentTask_Handler,
		},
		{
			MethodName: "CompleteAgentTask",
			Handler:    _AgentSkillService_CompleteAgentTask_Handler,
		},
		{
			MethodName: "StartAgentWorker",
			Handler:    _AgentSkillService_StartAgentWorker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "containarium/v1/agent.proto",
}

const (
	CrewService_ListCrews_FullMethodName  = "/containarium.v1.CrewService/ListCrews"
	CrewService_GetCrew_FullMethodName    = "/containarium.v1.CrewService/GetCrew"
	CrewService_RunCrew_FullMethodName    = "/containarium.v1.CrewService/RunCrew"
	CrewService_GetCrewRun_FullMethodName = "/containarium.v1.CrewService/GetCrewRun"
)

// CrewServiceClient is the client API for CrewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CrewService runs collaborating sets of skills bound to a task purpose.
type CrewServiceClient interface {
	// ListCrews returns all available crews.
	ListCrews(ctx context.Context, in *ListCrewsRequest, opts ...grpc.CallOption) (*ListCrewsResponse, error)
	// GetCrew returns a single crew definition by id.
	GetCrew(ctx context.Context, in *GetCrewRequest, opts ...grpc.CallOption) (*GetCrewResponse, error)
	// RunCrew launches a crew against an input: validates the topology against the
	// union of member skills' allowed_peers, provisions each skill's box, compiles
	// per-agent network policy, threads one trace_id through every hop, and
	// returns the run handle.
	RunCrew(ctx context.Context, in *RunCrewRequest, opts ...grpc.CallOption) (*RunCrewResponse, error)
	// GetCrewRun returns the status and artifact of a crew run.
	GetCrewRun(ctx context.Context, in *GetCrewRunRequest, opts ...grpc.CallOption) (*GetCrewRunResponse, error)
}

type crewServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCrewServiceClient(cc grpc.ClientConnInterface) CrewServiceClient {
	return &crewServiceClient{cc}
}

func (c *crewServiceClient) ListCrews(ctx context.Context, in *ListCrewsRequest, opts ...grpc.CallOption) (*ListCrewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCrewsResponse)
	err := c.cc.Invoke(ctx, CrewService_ListCrews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crewServiceClient) GetCrew(ctx context.Context, in *GetCrewRequest, opts ...grpc.CallOption) (*GetCrewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCrewResponse)
	err := c.cc.Invoke(ctx, CrewService_GetCrew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crewServiceClient) RunCrew(ctx context.Context, in *RunCrewRequest, opts ...grpc.CallOption) (*RunCrewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunCrewResponse)
	err := c.cc.Invoke(ctx, CrewService_RunCrew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crewServiceClient) GetCrewRun(ctx context.Context, in *GetCrewRunRequest, opts ...grpc.CallOption) (*GetCrewRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCrewRunResponse)
	err := c.cc.Invoke(ctx, CrewService_GetCrewRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrewServiceServer is the server API for CrewService service.
// All implementations must embed UnimplementedCrewServiceServer
// for forward compatibility.
//
// CrewService runs collaborating sets of skills bound to a task purpose.
type CrewServiceServer interface {
	// ListCrews returns all available crews.
	ListCrews(context.Context, *ListCrewsRequest) (*ListCrewsResponse, error)
	// GetCrew returns a single crew definition by id.
	GetCrew(context.Context, *GetCrewRequest) (*GetCrewResponse, error)
	// RunCrew launches a crew against an input: validates the topology against the
	// union of member skills' allowed_peers, provisions each skill's box, compiles
	// per-agent network policy, threads one trace_id through every hop, and
	// returns the run handle.
	RunCrew(context.Context, *RunCrewRequest) (*RunCrewResponse, error)
	// GetCrewRun returns the status and artifact of a crew run.
	GetCrewRun(context.Context, *GetCrewRunRequest) (*GetCrewRunResponse, error)
	mustEmbedUnimplementedCrewServiceServer()
}

// UnimplementedCrewServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCrewServiceServer struct{}

func (UnimplementedCrewServiceServer) ListCrews(context.Context, *ListCrewsRequest) (*ListCrewsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCrews not implemented")
}
func (UnimplementedCrewServiceServer) GetCrew(context.Context, *GetCrewRequest) (*GetCrewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCrew not implemented")
}
func (UnimplementedCrewServiceServer) RunCrew(context.Context, *RunCrewRequest) (*RunCrewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunCrew not implemented")
}
func (UnimplementedCrewServiceServer) GetCrewRun(context.Context, *GetCrewRunRequest) (*GetCrewRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCrewRun not implemented")
}
func (UnimplementedCrewServiceServer) mustEmbedUnimplementedCrewServiceServer() {}
func (UnimplementedCrewServiceServer) testEmbeddedByValue()                     {}

// UnsafeCrewServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrewServiceServer will
// result in compilation errors.
type UnsafeCrewServiceServer interface {
	mustEmbedUnimplementedCrewServiceServer()
}

func RegisterCrewServiceServer(s grpc.ServiceRegistrar, srv CrewServiceServer) {
	// If the following call panics, it indicates UnimplementedCrewServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CrewService_ServiceDesc, srv)
}

func _CrewService_ListCrews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCrewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrewServiceServer).ListCrews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrewService_ListCrews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrewServiceServer).ListCrews(ctx, req.(*ListCrewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrewService_GetCrew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCrewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrewServiceServer).GetCrew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrewService_GetCrew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrewServiceServer).GetCrew(ctx, req.(*GetCrewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrewService_RunCrew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunCrewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrewServiceServer).RunCrew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrewService_RunCrew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrewServiceServer).RunCrew(ctx, req.(*RunCrewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CrewService_GetCrewRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCrewRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrewServiceServer).GetCrewRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrewService_GetCrewRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrewServiceServer).GetCrewRun(ctx, req.(*GetCrewRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CrewService_ServiceDesc is the grpc.ServiceDesc for CrewService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrewService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "containarium.v1.CrewService",
	HandlerType: (*CrewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCrews",
			Handler:    _CrewService_ListCrews_Handler,
		},
		{
			MethodName: "GetCrew",
			Handler:    _CrewService_GetCrew_Handler,
		},
		{
			MethodName: "RunCrew",
			Handler:    _CrewService_RunCrew_Handler,
		},
		{
			MethodName: "GetCrewRun",
			Handler:    _CrewService_GetCrewRun_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "containarium/v1/agent.proto",
}
