// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: containarium/v1/backup.proto

package containariumv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BackupDestination is where a logical dump is stored *off* the database
// host. The whole point of the feature is getting the data off-box, so a
// destination is always required — there is no "stay on the same disk"
// option (a dump that shares a failure domain with the database it came
// from is not a backup; see docs/DB-BACKUP-OPERATIONS.md).
type BackupDestination int32

const (
	// Unset — the daemon rejects a create with this value.
	BackupDestination_BACKUP_DESTINATION_UNSPECIFIED BackupDestination = 0
	// A backup directory on the daemon host, distinct from the container's
	// own data disk. Survives container/disk loss but NOT host loss — use
	// for dev or as a staging tier in front of an off-host copy.
	BackupDestination_BACKUP_DESTINATION_LOCAL BackupDestination = 1
	// A Google Cloud Storage bucket, written via the host's `gcloud`
	// (`gcloud storage cp`). True off-host durability; the recommended
	// production destination.
	BackupDestination_BACKUP_DESTINATION_GCS BackupDestination = 2
)

// Enum value maps for BackupDestination.
var (
	BackupDestination_name = map[int32]string{
		0: "BACKUP_DESTINATION_UNSPECIFIED",
		1: "BACKUP_DESTINATION_LOCAL",
		2: "BACKUP_DESTINATION_GCS",
	}
	BackupDestination_value = map[string]int32{
		"BACKUP_DESTINATION_UNSPECIFIED": 0,
		"BACKUP_DESTINATION_LOCAL":       1,
		"BACKUP_DESTINATION_GCS":         2,
	}
)

func (x BackupDestination) Enum() *BackupDestination {
	p := new(BackupDestination)
	*p = x
	return p
}

func (x BackupDestination) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackupDestination) Descriptor() protoreflect.EnumDescriptor {
	return file_containarium_v1_backup_proto_enumTypes[0].Descriptor()
}

func (BackupDestination) Type() protoreflect.EnumType {
	return &file_containarium_v1_backup_proto_enumTypes[0]
}

func (x BackupDestination) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackupDestination.Descriptor instead.
func (BackupDestination) EnumDescriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{0}
}

// BackupRecord is the metadata index entry for one stored dump. The dump
// itself lives at `location`; this record is persisted as a small JSON
// sidecar in the daemon's backup directory so `ListBackups` works without
// a database dependency (the thing we are backing up may itself be down).
type BackupRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable identifier: "<username>-<database>-<UTC timestamp>"
	// (e.g. "alice-app-20260605T130405Z"). Used by Get/Restore/Delete.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Tenant (username) whose container's database was dumped.
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// Logical database name that was dumped.
	Database string `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	// RFC3339 UTC timestamp of when the dump completed.
	CreatedAt string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Size of the compressed custom-format dump, in bytes.
	SizeBytes int64 `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// SHA-256 of the dump bytes, for integrity verification on restore.
	Sha256 string `protobuf:"bytes,6,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// Where the dump is stored.
	Destination BackupDestination `protobuf:"varint,7,opt,name=destination,proto3,enum=containarium.v1.BackupDestination" json:"destination,omitempty"`
	// Concrete location of the dump: a host path for LOCAL, a gs:// URI
	// for GCS.
	Location string `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	// Database engine. "postgres" is the only engine in v1.
	Engine        string `protobuf:"bytes,9,opt,name=engine,proto3" json:"engine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupRecord) Reset() {
	*x = BackupRecord{}
	mi := &file_containarium_v1_backup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRecord) ProtoMessage() {}

func (x *BackupRecord) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRecord.ProtoReflect.Descriptor instead.
func (*BackupRecord) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{0}
}

func (x *BackupRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BackupRecord) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BackupRecord) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *BackupRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *BackupRecord) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *BackupRecord) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *BackupRecord) GetDestination() BackupDestination {
	if x != nil {
		return x.Destination
	}
	return BackupDestination_BACKUP_DESTINATION_UNSPECIFIED
}

func (x *BackupRecord) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *BackupRecord) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

// PgConnection carries the connection parameters pg_dump / pg_restore use
// *inside the container*. Defaults target a per-container local Postgres
// reached over loopback. db_password is never logged and is passed to the
// child process via the PGPASSWORD environment variable, not argv.
type PgConnection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Logical database to dump or restore into. Required.
	Database string `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// Postgres role. Defaults to "postgres" when empty.
	User string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// Password for the role. Optional (empty for trust/peer auth or when a
	// PGPASSFILE is configured in the container). Never logged.
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// Host as seen from *inside* the container. Defaults to "127.0.0.1".
	Host string `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	// Port. Defaults to 5432 when zero.
	Port          int32 `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PgConnection) Reset() {
	*x = PgConnection{}
	mi := &file_containarium_v1_backup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PgConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PgConnection) ProtoMessage() {}

func (x *PgConnection) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PgConnection.ProtoReflect.Descriptor instead.
func (*PgConnection) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{1}
}

func (x *PgConnection) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *PgConnection) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *PgConnection) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *PgConnection) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *PgConnection) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// CreateBackupRequest dumps a container's database and stores it at the
// chosen destination.
type CreateBackupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant (username) whose container holds the database.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// Connection parameters for pg_dump inside the container.
	Connection *PgConnection `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	// Where to store the dump.
	Destination BackupDestination `protobuf:"varint,3,opt,name=destination,proto3,enum=containarium.v1.BackupDestination" json:"destination,omitempty"`
	// For GCS: the destination bucket/prefix, e.g. "gs://my-backups/pg".
	// Ignored for LOCAL. The object key is appended as "<id>.dump".
	GcsBucket     string `protobuf:"bytes,4,opt,name=gcs_bucket,json=gcsBucket,proto3" json:"gcs_bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBackupRequest) Reset() {
	*x = CreateBackupRequest{}
	mi := &file_containarium_v1_backup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBackupRequest) ProtoMessage() {}

func (x *CreateBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBackupRequest.ProtoReflect.Descriptor instead.
func (*CreateBackupRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBackupRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateBackupRequest) GetConnection() *PgConnection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *CreateBackupRequest) GetDestination() BackupDestination {
	if x != nil {
		return x.Destination
	}
	return BackupDestination_BACKUP_DESTINATION_UNSPECIFIED
}

func (x *CreateBackupRequest) GetGcsBucket() string {
	if x != nil {
		return x.GcsBucket
	}
	return ""
}

type CreateBackupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operator-facing summary.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// The committed backup record.
	Record        *BackupRecord `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBackupResponse) Reset() {
	*x = CreateBackupResponse{}
	mi := &file_containarium_v1_backup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBackupResponse) ProtoMessage() {}

func (x *CreateBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBackupResponse.ProtoReflect.Descriptor instead.
func (*CreateBackupResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBackupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateBackupResponse) GetRecord() *BackupRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

// ListBackupsRequest enumerates stored backups, newest first.
type ListBackupsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional tenant filter. Empty lists backups for all tenants
	// (admin view).
	Username      string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupsRequest) Reset() {
	*x = ListBackupsRequest{}
	mi := &file_containarium_v1_backup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsRequest) ProtoMessage() {}

func (x *ListBackupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsRequest.ProtoReflect.Descriptor instead.
func (*ListBackupsRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{4}
}

func (x *ListBackupsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ListBackupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*BackupRecord        `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupsResponse) Reset() {
	*x = ListBackupsResponse{}
	mi := &file_containarium_v1_backup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsResponse) ProtoMessage() {}

func (x *ListBackupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsResponse.ProtoReflect.Descriptor instead.
func (*ListBackupsResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{5}
}

func (x *ListBackupsResponse) GetRecords() []*BackupRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

// GetBackupRequest fetches a single backup record by ID.
type GetBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackupRequest) Reset() {
	*x = GetBackupRequest{}
	mi := &file_containarium_v1_backup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackupRequest) ProtoMessage() {}

func (x *GetBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackupRequest.ProtoReflect.Descriptor instead.
func (*GetBackupRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{6}
}

func (x *GetBackupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *BackupRecord          `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackupResponse) Reset() {
	*x = GetBackupResponse{}
	mi := &file_containarium_v1_backup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackupResponse) ProtoMessage() {}

func (x *GetBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackupResponse.ProtoReflect.Descriptor instead.
func (*GetBackupResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{7}
}

func (x *GetBackupResponse) GetRecord() *BackupRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

// RestoreBackupRequest streams a stored dump back into a container's
// database via pg_restore. Destructive: with `clean` set it drops and
// recreates objects before loading.
type RestoreBackupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Backup to restore.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Connection parameters for pg_restore inside the target container.
	// If connection.database is empty, the backup record's database is
	// used (restore in place).
	Connection *PgConnection `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	// Pass --clean --if-exists to pg_restore (drop objects before
	// recreating). Off by default so a restore into a fresh database
	// does not error on missing objects.
	Clean         bool `protobuf:"varint,3,opt,name=clean,proto3" json:"clean,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreBackupRequest) Reset() {
	*x = RestoreBackupRequest{}
	mi := &file_containarium_v1_backup_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreBackupRequest) ProtoMessage() {}

func (x *RestoreBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreBackupRequest.ProtoReflect.Descriptor instead.
func (*RestoreBackupRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{8}
}

func (x *RestoreBackupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RestoreBackupRequest) GetConnection() *PgConnection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *RestoreBackupRequest) GetClean() bool {
	if x != nil {
		return x.Clean
	}
	return false
}

type RestoreBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreBackupResponse) Reset() {
	*x = RestoreBackupResponse{}
	mi := &file_containarium_v1_backup_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreBackupResponse) ProtoMessage() {}

func (x *RestoreBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreBackupResponse.ProtoReflect.Descriptor instead.
func (*RestoreBackupResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{9}
}

func (x *RestoreBackupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// DeleteBackupRequest removes a stored dump and its index entry.
type DeleteBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBackupRequest) Reset() {
	*x = DeleteBackupRequest{}
	mi := &file_containarium_v1_backup_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackupRequest) ProtoMessage() {}

func (x *DeleteBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackupRequest.ProtoReflect.Descriptor instead.
func (*DeleteBackupRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteBackupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBackupResponse) Reset() {
	*x = DeleteBackupResponse{}
	mi := &file_containarium_v1_backup_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackupResponse) ProtoMessage() {}

func (x *DeleteBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_backup_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackupResponse.ProtoReflect.Descriptor instead.
func (*DeleteBackupResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_backup_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteBackupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_containarium_v1_backup_proto protoreflect.FileDescriptor

const file_containarium_v1_backup_proto_rawDesc = "" +
	"\n" +
	"\x1ccontainarium/v1/backup.proto\x12\x0fcontainarium.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xa6\x02\n" +
	"\fBackupRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bdatabase\x18\x03 \x01(\tR\bdatabase\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\x06 \x01(\tR\x06sha256\x12D\n" +
	"\vdestination\x18\a \x01(\x0e2\".containarium.v1.BackupDestinationR\vdestination\x12\x1a\n" +
	"\blocation\x18\b \x01(\tR\blocation\x12\x16\n" +
	"\x06engine\x18\t \x01(\tR\x06engine\"\x82\x01\n" +
	"\fPgConnection\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x05R\x04port\"\xd5\x01\n" +
	"\x13CreateBackupRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12=\n" +
	"\n" +
	"connection\x18\x02 \x01(\v2\x1d.containarium.v1.PgConnectionR\n" +
	"connection\x12D\n" +
	"\vdestination\x18\x03 \x01(\x0e2\".containarium.v1.BackupDestinationR\vdestination\x12\x1d\n" +
	"\n" +
	"gcs_bucket\x18\x04 \x01(\tR\tgcsBucket\"g\n" +
	"\x14CreateBackupResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x125\n" +
	"\x06record\x18\x02 \x01(\v2\x1d.containarium.v1.BackupRecordR\x06record\"0\n" +
	"\x12ListBackupsRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"N\n" +
	"\x13ListBackupsResponse\x127\n" +
	"\arecords\x18\x01 \x03(\v2\x1d.containarium.v1.BackupRecordR\arecords\"\"\n" +
	"\x10GetBackupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x11GetBackupResponse\x125\n" +
	"\x06record\x18\x01 \x01(\v2\x1d.containarium.v1.BackupRecordR\x06record\"{\n" +
	"\x14RestoreBackupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12=\n" +
	"\n" +
	"connection\x18\x02 \x01(\v2\x1d.containarium.v1.PgConnectionR\n" +
	"connection\x12\x14\n" +
	"\x05clean\x18\x03 \x01(\bR\x05clean\"1\n" +
	"\x15RestoreBackupResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"%\n" +
	"\x13DeleteBackupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14DeleteBackupResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*q\n" +
	"\x11BackupDestination\x12\"\n" +
	"\x1eBACKUP_DESTINATION_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18BACKUP_DESTINATION_LOCAL\x10\x01\x12\x1a\n" +
	"\x16BACKUP_DESTINATION_GCS\x10\x022\xb3\t\n" +
	"\rBackupService\x12\x90\x02\n" +
	"\fCreateBackup\x12$.containarium.v1.CreateBackupRequest\x1a%.containarium.v1.CreateBackupResponse\"\xb2\x01\x92A\x98\x01\n" +
	"\aBackups\x12\x0fCreate a backup\x1a|Runs pg_dump inside the tenant's container and stores the dump at the chosen off-host destination (local backup dir or GCS).\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/backups\x12\xd3\x01\n" +
	"\vListBackups\x12#.containarium.v1.ListBackupsRequest\x1a$.containarium.v1.ListBackupsResponse\"y\x92Ac\n" +
	"\aBackups\x12\fList backups\x1aJLists stored backup records (newest first), optionally filtered by tenant.\x82\xd3\xe4\x93\x02\r\x12\v/v1/backups\x12\xb8\x01\n" +
	"\tGetBackup\x12!.containarium.v1.GetBackupRequest\x1a\".containarium.v1.GetBackupResponse\"d\x92AI\n" +
	"\aBackups\x12\fGet a backup\x1a0Returns the metadata for a single stored backup.\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/backups/{id}\x12\x88\x02\n" +
	"\rRestoreBackup\x12%.containarium.v1.RestoreBackupRequest\x1a&.containarium.v1.RestoreBackupResponse\"\xa7\x01\x92A\x80\x01\n" +
	"\aBackups\x12\x10Restore a backup\x1acStreams a stored dump back into a container's database via pg_restore. Destructive when clean=true.\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/backups/{id}/restore\x12\xf2\x01\n" +
	"\fDeleteBackup\x12$.containarium.v1.DeleteBackupRequest\x1a%.containarium.v1.DeleteBackupResponse\"\x94\x01\x92Ay\n" +
	"\aBackups\x12\x0fDelete a backup\x1a]Deletes a stored dump and its metadata. Retention enforcement is the caller's responsibility.\x82\xd3\xe4\x93\x02\x12*\x10/v1/backups/{id}BKZIgithub.com/footprintai/containarium/pkg/pb/containarium/v1;containariumv1b\x06proto3"

var (
	file_containarium_v1_backup_proto_rawDescOnce sync.Once
	file_containarium_v1_backup_proto_rawDescData []byte
)

func file_containarium_v1_backup_proto_rawDescGZIP() []byte {
	file_containarium_v1_backup_proto_rawDescOnce.Do(func() {
		file_containarium_v1_backup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_containarium_v1_backup_proto_rawDesc), len(file_containarium_v1_backup_proto_rawDesc)))
	})
	return file_containarium_v1_backup_proto_rawDescData
}

var file_containarium_v1_backup_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_containarium_v1_backup_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_containarium_v1_backup_proto_goTypes = []any{
	(BackupDestination)(0),        // 0: containarium.v1.BackupDestination
	(*BackupRecord)(nil),          // 1: containarium.v1.BackupRecord
	(*PgConnection)(nil),          // 2: containarium.v1.PgConnection
	(*CreateBackupRequest)(nil),   // 3: containarium.v1.CreateBackupRequest
	(*CreateBackupResponse)(nil),  // 4: containarium.v1.CreateBackupResponse
	(*ListBackupsRequest)(nil),    // 5: containarium.v1.ListBackupsRequest
	(*ListBackupsResponse)(nil),   // 6: containarium.v1.ListBackupsResponse
	(*GetBackupRequest)(nil),      // 7: containarium.v1.GetBackupRequest
	(*GetBackupResponse)(nil),     // 8: containarium.v1.GetBackupResponse
	(*RestoreBackupRequest)(nil),  // 9: containarium.v1.RestoreBackupRequest
	(*RestoreBackupResponse)(nil), // 10: containarium.v1.RestoreBackupResponse
	(*DeleteBackupRequest)(nil),   // 11: containarium.v1.DeleteBackupRequest
	(*DeleteBackupResponse)(nil),  // 12: containarium.v1.DeleteBackupResponse
}
var file_containarium_v1_backup_proto_depIdxs = []int32{
	0,  // 0: containarium.v1.BackupRecord.destination:type_name -> containarium.v1.BackupDestination
	2,  // 1: containarium.v1.CreateBackupRequest.connection:type_name -> containarium.v1.PgConnection
	0,  // 2: containarium.v1.CreateBackupRequest.destination:type_name -> containarium.v1.BackupDestination
	1,  // 3: containarium.v1.CreateBackupResponse.record:type_name -> containarium.v1.BackupRecord
	1,  // 4: containarium.v1.ListBackupsResponse.records:type_name -> containarium.v1.BackupRecord
	1,  // 5: containarium.v1.GetBackupResponse.record:type_name -> containarium.v1.BackupRecord
	2,  // 6: containarium.v1.RestoreBackupRequest.connection:type_name -> containarium.v1.PgConnection
	3,  // 7: containarium.v1.BackupService.CreateBackup:input_type -> containarium.v1.CreateBackupRequest
	5,  // 8: containarium.v1.BackupService.ListBackups:input_type -> containarium.v1.ListBackupsRequest
	7,  // 9: containarium.v1.BackupService.GetBackup:input_type -> containarium.v1.GetBackupRequest
	9,  // 10: containarium.v1.BackupService.RestoreBackup:input_type -> containarium.v1.RestoreBackupRequest
	11, // 11: containarium.v1.BackupService.DeleteBackup:input_type -> containarium.v1.DeleteBackupRequest
	4,  // 12: containarium.v1.BackupService.CreateBackup:output_type -> containarium.v1.CreateBackupResponse
	6,  // 13: containarium.v1.BackupService.ListBackups:output_type -> containarium.v1.ListBackupsResponse
	8,  // 14: containarium.v1.BackupService.GetBackup:output_type -> containarium.v1.GetBackupResponse
	10, // 15: containarium.v1.BackupService.RestoreBackup:output_type -> containarium.v1.RestoreBackupResponse
	12, // 16: containarium.v1.BackupService.DeleteBackup:output_type -> containarium.v1.DeleteBackupResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_containarium_v1_backup_proto_init() }
func file_containarium_v1_backup_proto_init() {
	if File_containarium_v1_backup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_containarium_v1_backup_proto_rawDesc), len(file_containarium_v1_backup_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_containarium_v1_backup_proto_goTypes,
		DependencyIndexes: file_containarium_v1_backup_proto_depIdxs,
		EnumInfos:         file_containarium_v1_backup_proto_enumTypes,
		MessageInfos:      file_containarium_v1_backup_proto_msgTypes,
	}.Build()
	File_containarium_v1_backup_proto = out.File
	file_containarium_v1_backup_proto_goTypes = nil
	file_containarium_v1_backup_proto_depIdxs = nil
}
