// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: containarium/v1/config.proto

package containariumv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GPU vendor enum
type GPUVendor int32

const (
	GPUVendor_GPU_VENDOR_UNSPECIFIED GPUVendor = 0
	GPUVendor_GPU_VENDOR_NVIDIA      GPUVendor = 1
	GPUVendor_GPU_VENDOR_AMD         GPUVendor = 2
	GPUVendor_GPU_VENDOR_INTEL       GPUVendor = 3
)

// Enum value maps for GPUVendor.
var (
	GPUVendor_name = map[int32]string{
		0: "GPU_VENDOR_UNSPECIFIED",
		1: "GPU_VENDOR_NVIDIA",
		2: "GPU_VENDOR_AMD",
		3: "GPU_VENDOR_INTEL",
	}
	GPUVendor_value = map[string]int32{
		"GPU_VENDOR_UNSPECIFIED": 0,
		"GPU_VENDOR_NVIDIA":      1,
		"GPU_VENDOR_AMD":         2,
		"GPU_VENDOR_INTEL":       3,
	}
)

func (x GPUVendor) Enum() *GPUVendor {
	p := new(GPUVendor)
	*p = x
	return p
}

func (x GPUVendor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GPUVendor) Descriptor() protoreflect.EnumDescriptor {
	return file_containarium_v1_config_proto_enumTypes[0].Descriptor()
}

func (GPUVendor) Type() protoreflect.EnumType {
	return &file_containarium_v1_config_proto_enumTypes[0]
}

func (x GPUVendor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GPUVendor.Descriptor instead.
func (GPUVendor) EnumDescriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{0}
}

// GPU model enum (common datacenter and workstation GPUs)
type GPUModel int32

const (
	GPUModel_GPU_MODEL_UNSPECIFIED GPUModel = 0
	// NVIDIA Consumer
	GPUModel_GPU_MODEL_NVIDIA_RTX_4090    GPUModel = 100
	GPUModel_GPU_MODEL_NVIDIA_RTX_4080    GPUModel = 101
	GPUModel_GPU_MODEL_NVIDIA_RTX_4070_TI GPUModel = 102
	GPUModel_GPU_MODEL_NVIDIA_RTX_4070    GPUModel = 103
	GPUModel_GPU_MODEL_NVIDIA_RTX_3090    GPUModel = 104
	GPUModel_GPU_MODEL_NVIDIA_RTX_3080    GPUModel = 105
	GPUModel_GPU_MODEL_NVIDIA_RTX_5090    GPUModel = 106
	GPUModel_GPU_MODEL_NVIDIA_RTX_5080    GPUModel = 107
	// NVIDIA Datacenter
	GPUModel_GPU_MODEL_NVIDIA_A100 GPUModel = 200
	GPUModel_GPU_MODEL_NVIDIA_A10  GPUModel = 201
	GPUModel_GPU_MODEL_NVIDIA_A10G GPUModel = 202
	GPUModel_GPU_MODEL_NVIDIA_H100 GPUModel = 203
	GPUModel_GPU_MODEL_NVIDIA_H200 GPUModel = 204
	GPUModel_GPU_MODEL_NVIDIA_L4   GPUModel = 205
	GPUModel_GPU_MODEL_NVIDIA_L40  GPUModel = 206
	GPUModel_GPU_MODEL_NVIDIA_L40S GPUModel = 207
	GPUModel_GPU_MODEL_NVIDIA_T4   GPUModel = 208
	GPUModel_GPU_MODEL_NVIDIA_V100 GPUModel = 209
	GPUModel_GPU_MODEL_NVIDIA_B200 GPUModel = 210
	// AMD
	GPUModel_GPU_MODEL_AMD_MI300X      GPUModel = 300
	GPUModel_GPU_MODEL_AMD_MI250X      GPUModel = 301
	GPUModel_GPU_MODEL_AMD_RX_7900_XTX GPUModel = 302
	// Intel
	GPUModel_GPU_MODEL_INTEL_MAX_1550 GPUModel = 400
	GPUModel_GPU_MODEL_INTEL_ARC_A770 GPUModel = 401
)

// Enum value maps for GPUModel.
var (
	GPUModel_name = map[int32]string{
		0:   "GPU_MODEL_UNSPECIFIED",
		100: "GPU_MODEL_NVIDIA_RTX_4090",
		101: "GPU_MODEL_NVIDIA_RTX_4080",
		102: "GPU_MODEL_NVIDIA_RTX_4070_TI",
		103: "GPU_MODEL_NVIDIA_RTX_4070",
		104: "GPU_MODEL_NVIDIA_RTX_3090",
		105: "GPU_MODEL_NVIDIA_RTX_3080",
		106: "GPU_MODEL_NVIDIA_RTX_5090",
		107: "GPU_MODEL_NVIDIA_RTX_5080",
		200: "GPU_MODEL_NVIDIA_A100",
		201: "GPU_MODEL_NVIDIA_A10",
		202: "GPU_MODEL_NVIDIA_A10G",
		203: "GPU_MODEL_NVIDIA_H100",
		204: "GPU_MODEL_NVIDIA_H200",
		205: "GPU_MODEL_NVIDIA_L4",
		206: "GPU_MODEL_NVIDIA_L40",
		207: "GPU_MODEL_NVIDIA_L40S",
		208: "GPU_MODEL_NVIDIA_T4",
		209: "GPU_MODEL_NVIDIA_V100",
		210: "GPU_MODEL_NVIDIA_B200",
		300: "GPU_MODEL_AMD_MI300X",
		301: "GPU_MODEL_AMD_MI250X",
		302: "GPU_MODEL_AMD_RX_7900_XTX",
		400: "GPU_MODEL_INTEL_MAX_1550",
		401: "GPU_MODEL_INTEL_ARC_A770",
	}
	GPUModel_value = map[string]int32{
		"GPU_MODEL_UNSPECIFIED":        0,
		"GPU_MODEL_NVIDIA_RTX_4090":    100,
		"GPU_MODEL_NVIDIA_RTX_4080":    101,
		"GPU_MODEL_NVIDIA_RTX_4070_TI": 102,
		"GPU_MODEL_NVIDIA_RTX_4070":    103,
		"GPU_MODEL_NVIDIA_RTX_3090":    104,
		"GPU_MODEL_NVIDIA_RTX_3080":    105,
		"GPU_MODEL_NVIDIA_RTX_5090":    106,
		"GPU_MODEL_NVIDIA_RTX_5080":    107,
		"GPU_MODEL_NVIDIA_A100":        200,
		"GPU_MODEL_NVIDIA_A10":         201,
		"GPU_MODEL_NVIDIA_A10G":        202,
		"GPU_MODEL_NVIDIA_H100":        203,
		"GPU_MODEL_NVIDIA_H200":        204,
		"GPU_MODEL_NVIDIA_L4":          205,
		"GPU_MODEL_NVIDIA_L40":         206,
		"GPU_MODEL_NVIDIA_L40S":        207,
		"GPU_MODEL_NVIDIA_T4":          208,
		"GPU_MODEL_NVIDIA_V100":        209,
		"GPU_MODEL_NVIDIA_B200":        210,
		"GPU_MODEL_AMD_MI300X":         300,
		"GPU_MODEL_AMD_MI250X":         301,
		"GPU_MODEL_AMD_RX_7900_XTX":    302,
		"GPU_MODEL_INTEL_MAX_1550":     400,
		"GPU_MODEL_INTEL_ARC_A770":     401,
	}
)

func (x GPUModel) Enum() *GPUModel {
	p := new(GPUModel)
	*p = x
	return p
}

func (x GPUModel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GPUModel) Descriptor() protoreflect.EnumDescriptor {
	return file_containarium_v1_config_proto_enumTypes[1].Descriptor()
}

func (GPUModel) Type() protoreflect.EnumType {
	return &file_containarium_v1_config_proto_enumTypes[1]
}

func (x GPUModel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GPUModel.Descriptor instead.
func (GPUModel) EnumDescriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{1}
}

// BackendType represents the type of backend instance
type BackendType int32

const (
	BackendType_BACKEND_TYPE_UNSPECIFIED BackendType = 0
	BackendType_BACKEND_TYPE_GCP         BackendType = 1
	BackendType_BACKEND_TYPE_TUNNEL      BackendType = 2
)

// Enum value maps for BackendType.
var (
	BackendType_name = map[int32]string{
		0: "BACKEND_TYPE_UNSPECIFIED",
		1: "BACKEND_TYPE_GCP",
		2: "BACKEND_TYPE_TUNNEL",
	}
	BackendType_value = map[string]int32{
		"BACKEND_TYPE_UNSPECIFIED": 0,
		"BACKEND_TYPE_GCP":         1,
		"BACKEND_TYPE_TUNNEL":      2,
	}
)

func (x BackendType) Enum() *BackendType {
	p := new(BackendType)
	*p = x
	return p
}

func (x BackendType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackendType) Descriptor() protoreflect.EnumDescriptor {
	return file_containarium_v1_config_proto_enumTypes[2].Descriptor()
}

func (BackendType) Type() protoreflect.EnumType {
	return &file_containarium_v1_config_proto_enumTypes[2]
}

func (x BackendType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackendType.Descriptor instead.
func (BackendType) EnumDescriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{2}
}

// Config represents the system-wide configuration for Containarium
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Incus configuration
	Incus *IncusConfig `protobuf:"bytes,1,opt,name=incus,proto3" json:"incus,omitempty"`
	// Default resource limits for new containers
	DefaultResources *ResourceLimits `protobuf:"bytes,2,opt,name=default_resources,json=defaultResources,proto3" json:"default_resources,omitempty"`
	// Default container image
	DefaultImage string `protobuf:"bytes,3,opt,name=default_image,json=defaultImage,proto3" json:"default_image,omitempty"`
	// Enable Docker support by default
	DefaultDockerEnabled bool `protobuf:"varint,4,opt,name=default_docker_enabled,json=defaultDockerEnabled,proto3" json:"default_docker_enabled,omitempty"`
	// Network configuration
	Network *NetworkConfig `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	// Storage configuration
	Storage *StorageConfig `protobuf:"bytes,6,opt,name=storage,proto3" json:"storage,omitempty"`
	// Security configuration
	Security      *SecurityConfig `protobuf:"bytes,7,opt,name=security,proto3" json:"security,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_containarium_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetIncus() *IncusConfig {
	if x != nil {
		return x.Incus
	}
	return nil
}

func (x *Config) GetDefaultResources() *ResourceLimits {
	if x != nil {
		return x.DefaultResources
	}
	return nil
}

func (x *Config) GetDefaultImage() string {
	if x != nil {
		return x.DefaultImage
	}
	return ""
}

func (x *Config) GetDefaultDockerEnabled() bool {
	if x != nil {
		return x.DefaultDockerEnabled
	}
	return false
}

func (x *Config) GetNetwork() *NetworkConfig {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *Config) GetStorage() *StorageConfig {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *Config) GetSecurity() *SecurityConfig {
	if x != nil {
		return x.Security
	}
	return nil
}

// IncusConfig contains Incus-specific configuration
type IncusConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Incus socket path (default: /var/lib/incus/unix.socket)
	SocketPath string `protobuf:"bytes,1,opt,name=socket_path,json=socketPath,proto3" json:"socket_path,omitempty"`
	// Project name to use (default: default)
	Project string `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	// Remote name (default: local)
	Remote string `protobuf:"bytes,3,opt,name=remote,proto3" json:"remote,omitempty"`
	// Timeout for Incus operations in seconds
	TimeoutSeconds int32 `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IncusConfig) Reset() {
	*x = IncusConfig{}
	mi := &file_containarium_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncusConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncusConfig) ProtoMessage() {}

func (x *IncusConfig) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncusConfig.ProtoReflect.Descriptor instead.
func (*IncusConfig) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *IncusConfig) GetSocketPath() string {
	if x != nil {
		return x.SocketPath
	}
	return ""
}

func (x *IncusConfig) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *IncusConfig) GetRemote() string {
	if x != nil {
		return x.Remote
	}
	return ""
}

func (x *IncusConfig) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// NetworkConfig contains network-related configuration
type NetworkConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network bridge name (default: incusbr0)
	BridgeName string `protobuf:"bytes,1,opt,name=bridge_name,json=bridgeName,proto3" json:"bridge_name,omitempty"`
	// Subnet for container IPs (e.g., "10.0.3.0/24")
	Subnet string `protobuf:"bytes,2,opt,name=subnet,proto3" json:"subnet,omitempty"`
	// DHCP range start
	DhcpRangeStart string `protobuf:"bytes,3,opt,name=dhcp_range_start,json=dhcpRangeStart,proto3" json:"dhcp_range_start,omitempty"`
	// DHCP range end
	DhcpRangeEnd string `protobuf:"bytes,4,opt,name=dhcp_range_end,json=dhcpRangeEnd,proto3" json:"dhcp_range_end,omitempty"`
	// DNS servers for containers
	DnsServers []string `protobuf:"bytes,5,rep,name=dns_servers,json=dnsServers,proto3" json:"dns_servers,omitempty"`
	// Enable IPv6
	EnableIpv6    bool `protobuf:"varint,6,opt,name=enable_ipv6,json=enableIpv6,proto3" json:"enable_ipv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_containarium_v1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{2}
}

func (x *NetworkConfig) GetBridgeName() string {
	if x != nil {
		return x.BridgeName
	}
	return ""
}

func (x *NetworkConfig) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

func (x *NetworkConfig) GetDhcpRangeStart() string {
	if x != nil {
		return x.DhcpRangeStart
	}
	return ""
}

func (x *NetworkConfig) GetDhcpRangeEnd() string {
	if x != nil {
		return x.DhcpRangeEnd
	}
	return ""
}

func (x *NetworkConfig) GetDnsServers() []string {
	if x != nil {
		return x.DnsServers
	}
	return nil
}

func (x *NetworkConfig) GetEnableIpv6() bool {
	if x != nil {
		return x.EnableIpv6
	}
	return false
}

// StorageConfig contains storage-related configuration
type StorageConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Storage pool name
	PoolName string `protobuf:"bytes,1,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"`
	// Storage driver (e.g., "dir", "zfs", "btrfs")
	Driver string `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"`
	// Storage pool path
	PoolPath string `protobuf:"bytes,3,opt,name=pool_path,json=poolPath,proto3" json:"pool_path,omitempty"`
	// Default disk quota for containers
	DefaultDiskQuota string `protobuf:"bytes,4,opt,name=default_disk_quota,json=defaultDiskQuota,proto3" json:"default_disk_quota,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StorageConfig) Reset() {
	*x = StorageConfig{}
	mi := &file_containarium_v1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageConfig) ProtoMessage() {}

func (x *StorageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageConfig.ProtoReflect.Descriptor instead.
func (*StorageConfig) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{3}
}

func (x *StorageConfig) GetPoolName() string {
	if x != nil {
		return x.PoolName
	}
	return ""
}

func (x *StorageConfig) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *StorageConfig) GetPoolPath() string {
	if x != nil {
		return x.PoolPath
	}
	return ""
}

func (x *StorageConfig) GetDefaultDiskQuota() string {
	if x != nil {
		return x.DefaultDiskQuota
	}
	return ""
}

// SecurityConfig contains security-related configuration
type SecurityConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Use unprivileged containers (recommended: true)
	UnprivilegedContainers bool `protobuf:"varint,1,opt,name=unprivileged_containers,json=unprivilegedContainers,proto3" json:"unprivileged_containers,omitempty"`
	// AppArmor profile to use (default: "default")
	ApparmorProfile string `protobuf:"bytes,2,opt,name=apparmor_profile,json=apparmorProfile,proto3" json:"apparmor_profile,omitempty"`
	// SELinux context (if using SELinux)
	SelinuxContext string `protobuf:"bytes,3,opt,name=selinux_context,json=selinuxContext,proto3" json:"selinux_context,omitempty"`
	// Enable seccomp filtering
	EnableSeccomp bool `protobuf:"varint,4,opt,name=enable_seccomp,json=enableSeccomp,proto3" json:"enable_seccomp,omitempty"`
	// Require SSH keys (don't allow password auth)
	RequireSshKeys bool `protobuf:"varint,5,opt,name=require_ssh_keys,json=requireSshKeys,proto3" json:"require_ssh_keys,omitempty"`
	// Minimum password length if passwords are allowed
	MinPasswordLength int32 `protobuf:"varint,6,opt,name=min_password_length,json=minPasswordLength,proto3" json:"min_password_length,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SecurityConfig) Reset() {
	*x = SecurityConfig{}
	mi := &file_containarium_v1_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityConfig) ProtoMessage() {}

func (x *SecurityConfig) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityConfig.ProtoReflect.Descriptor instead.
func (*SecurityConfig) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{4}
}

func (x *SecurityConfig) GetUnprivilegedContainers() bool {
	if x != nil {
		return x.UnprivilegedContainers
	}
	return false
}

func (x *SecurityConfig) GetApparmorProfile() string {
	if x != nil {
		return x.ApparmorProfile
	}
	return ""
}

func (x *SecurityConfig) GetSelinuxContext() string {
	if x != nil {
		return x.SelinuxContext
	}
	return ""
}

func (x *SecurityConfig) GetEnableSeccomp() bool {
	if x != nil {
		return x.EnableSeccomp
	}
	return false
}

func (x *SecurityConfig) GetRequireSshKeys() bool {
	if x != nil {
		return x.RequireSshKeys
	}
	return false
}

func (x *SecurityConfig) GetMinPasswordLength() int32 {
	if x != nil {
		return x.MinPasswordLength
	}
	return 0
}

// GetConfigRequest is the request to get current configuration
type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_containarium_v1_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{5}
}

// GetConfigResponse is the response from getting configuration
type GetConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current configuration
	Config        *Config `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_containarium_v1_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{6}
}

func (x *GetConfigResponse) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

// UpdateConfigRequest is the request to update configuration
type UpdateConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated configuration
	Config *Config `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// Fields to update (if empty, update all)
	UpdateMask    []string `protobuf:"bytes,2,rep,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_containarium_v1_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateConfigRequest) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UpdateConfigRequest) GetUpdateMask() []string {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// UpdateConfigResponse is the response from updating configuration
type UpdateConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success message
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Updated configuration
	Config        *Config `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	mi := &file_containarium_v1_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateConfigResponse) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

// SystemInfo contains information about the host system
type SystemInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Incus version
	IncusVersion string `protobuf:"bytes,1,opt,name=incus_version,json=incusVersion,proto3" json:"incus_version,omitempty"`
	// Operating system
	Os string `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	// Kernel version
	KernelVersion string `protobuf:"bytes,3,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	// Total CPU cores
	TotalCpus int32 `protobuf:"varint,4,opt,name=total_cpus,json=totalCpus,proto3" json:"total_cpus,omitempty"`
	// Total memory in bytes
	TotalMemoryBytes int64 `protobuf:"varint,5,opt,name=total_memory_bytes,json=totalMemoryBytes,proto3" json:"total_memory_bytes,omitempty"`
	// Available memory in bytes
	AvailableMemoryBytes int64 `protobuf:"varint,6,opt,name=available_memory_bytes,json=availableMemoryBytes,proto3" json:"available_memory_bytes,omitempty"`
	// Total disk space in bytes
	TotalDiskBytes int64 `protobuf:"varint,7,opt,name=total_disk_bytes,json=totalDiskBytes,proto3" json:"total_disk_bytes,omitempty"`
	// Available disk space in bytes
	AvailableDiskBytes int64 `protobuf:"varint,8,opt,name=available_disk_bytes,json=availableDiskBytes,proto3" json:"available_disk_bytes,omitempty"`
	// Number of containers running
	ContainersRunning int32 `protobuf:"varint,9,opt,name=containers_running,json=containersRunning,proto3" json:"containers_running,omitempty"`
	// Number of containers stopped
	ContainersStopped int32 `protobuf:"varint,10,opt,name=containers_stopped,json=containersStopped,proto3" json:"containers_stopped,omitempty"`
	// Total number of containers
	ContainersTotal int32 `protobuf:"varint,11,opt,name=containers_total,json=containersTotal,proto3" json:"containers_total,omitempty"`
	// Hostname of the system
	Hostname string `protobuf:"bytes,12,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Uptime in seconds
	UptimeSeconds int64 `protobuf:"varint,13,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// Container network CIDR (e.g., "10.100.0.0/24")
	NetworkCidr string `protobuf:"bytes,14,opt,name=network_cidr,json=networkCidr,proto3" json:"network_cidr,omitempty"`
	// CPU load average (1 minute)
	CpuLoad_1Min float64 `protobuf:"fixed64,15,opt,name=cpu_load_1min,json=cpuLoad1min,proto3" json:"cpu_load_1min,omitempty"`
	// CPU load average (5 minutes)
	CpuLoad_5Min float64 `protobuf:"fixed64,16,opt,name=cpu_load_5min,json=cpuLoad5min,proto3" json:"cpu_load_5min,omitempty"`
	// CPU load average (15 minutes)
	CpuLoad_15Min float64 `protobuf:"fixed64,17,opt,name=cpu_load_15min,json=cpuLoad15min,proto3" json:"cpu_load_15min,omitempty"`
	// GPU information
	Gpus []*GPUInfo `protobuf:"bytes,18,rep,name=gpus,proto3" json:"gpus,omitempty"`
	// Backend ID (e.g., "tunnel-fts-5900x-gpu") — set when returned from peer
	BackendId     string `protobuf:"bytes,19,opt,name=backend_id,json=backendId,proto3" json:"backend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_containarium_v1_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{9}
}

func (x *SystemInfo) GetIncusVersion() string {
	if x != nil {
		return x.IncusVersion
	}
	return ""
}

func (x *SystemInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SystemInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *SystemInfo) GetTotalCpus() int32 {
	if x != nil {
		return x.TotalCpus
	}
	return 0
}

func (x *SystemInfo) GetTotalMemoryBytes() int64 {
	if x != nil {
		return x.TotalMemoryBytes
	}
	return 0
}

func (x *SystemInfo) GetAvailableMemoryBytes() int64 {
	if x != nil {
		return x.AvailableMemoryBytes
	}
	return 0
}

func (x *SystemInfo) GetTotalDiskBytes() int64 {
	if x != nil {
		return x.TotalDiskBytes
	}
	return 0
}

func (x *SystemInfo) GetAvailableDiskBytes() int64 {
	if x != nil {
		return x.AvailableDiskBytes
	}
	return 0
}

func (x *SystemInfo) GetContainersRunning() int32 {
	if x != nil {
		return x.ContainersRunning
	}
	return 0
}

func (x *SystemInfo) GetContainersStopped() int32 {
	if x != nil {
		return x.ContainersStopped
	}
	return 0
}

func (x *SystemInfo) GetContainersTotal() int32 {
	if x != nil {
		return x.ContainersTotal
	}
	return 0
}

func (x *SystemInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SystemInfo) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *SystemInfo) GetNetworkCidr() string {
	if x != nil {
		return x.NetworkCidr
	}
	return ""
}

func (x *SystemInfo) GetCpuLoad_1Min() float64 {
	if x != nil {
		return x.CpuLoad_1Min
	}
	return 0
}

func (x *SystemInfo) GetCpuLoad_5Min() float64 {
	if x != nil {
		return x.CpuLoad_5Min
	}
	return 0
}

func (x *SystemInfo) GetCpuLoad_15Min() float64 {
	if x != nil {
		return x.CpuLoad_15Min
	}
	return 0
}

func (x *SystemInfo) GetGpus() []*GPUInfo {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *SystemInfo) GetBackendId() string {
	if x != nil {
		return x.BackendId
	}
	return ""
}

// GPUInfo represents a GPU device on the system
type GPUInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// GPU vendor
	Vendor GPUVendor `protobuf:"varint,1,opt,name=vendor,proto3,enum=containarium.v1.GPUVendor" json:"vendor,omitempty"`
	// GPU model (known models mapped to enum, or UNSPECIFIED for unknown)
	Model GPUModel `protobuf:"varint,2,opt,name=model,proto3,enum=containarium.v1.GPUModel" json:"model,omitempty"`
	// Raw model name string from the driver (for display when model is UNSPECIFIED)
	ModelName string `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// PCI address (e.g., "0000:0b:00.0")
	PciAddress string `protobuf:"bytes,4,opt,name=pci_address,json=pciAddress,proto3" json:"pci_address,omitempty"`
	// Driver version (e.g., "570.86.15")
	DriverVersion string `protobuf:"bytes,5,opt,name=driver_version,json=driverVersion,proto3" json:"driver_version,omitempty"`
	// CUDA version (e.g., "12.7") — NVIDIA only
	CudaVersion string `protobuf:"bytes,6,opt,name=cuda_version,json=cudaVersion,proto3" json:"cuda_version,omitempty"`
	// VRAM in bytes (when available)
	VramBytes     int64 `protobuf:"varint,7,opt,name=vram_bytes,json=vramBytes,proto3" json:"vram_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUInfo) Reset() {
	*x = GPUInfo{}
	mi := &file_containarium_v1_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUInfo) ProtoMessage() {}

func (x *GPUInfo) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUInfo.ProtoReflect.Descriptor instead.
func (*GPUInfo) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{10}
}

func (x *GPUInfo) GetVendor() GPUVendor {
	if x != nil {
		return x.Vendor
	}
	return GPUVendor_GPU_VENDOR_UNSPECIFIED
}

func (x *GPUInfo) GetModel() GPUModel {
	if x != nil {
		return x.Model
	}
	return GPUModel_GPU_MODEL_UNSPECIFIED
}

func (x *GPUInfo) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *GPUInfo) GetPciAddress() string {
	if x != nil {
		return x.PciAddress
	}
	return ""
}

func (x *GPUInfo) GetDriverVersion() string {
	if x != nil {
		return x.DriverVersion
	}
	return ""
}

func (x *GPUInfo) GetCudaVersion() string {
	if x != nil {
		return x.CudaVersion
	}
	return ""
}

func (x *GPUInfo) GetVramBytes() int64 {
	if x != nil {
		return x.VramBytes
	}
	return 0
}

// GetSystemInfoRequest is the request to get system information
type GetSystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemInfoRequest) Reset() {
	*x = GetSystemInfoRequest{}
	mi := &file_containarium_v1_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoRequest) ProtoMessage() {}

func (x *GetSystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{11}
}

// GetSystemInfoResponse is the response from getting system information
type GetSystemInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// System information (local/primary backend)
	Info *SystemInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	// System information from peer backends (tunnel-connected)
	Peers         []*SystemInfo `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemInfoResponse) Reset() {
	*x = GetSystemInfoResponse{}
	mi := &file_containarium_v1_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoResponse) ProtoMessage() {}

func (x *GetSystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{12}
}

func (x *GetSystemInfoResponse) GetInfo() *SystemInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *GetSystemInfoResponse) GetPeers() []*SystemInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

// BackendInfo contains information about a backend instance
type BackendInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique backend identifier (e.g., "gcp-spot", "tunnel-fts-5900x-gpu")
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Backend type
	Type BackendType `protobuf:"varint,2,opt,name=type,proto3,enum=containarium.v1.BackendType" json:"type,omitempty"`
	// Whether the backend is currently healthy
	Healthy bool `protobuf:"varint,3,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Priority (lower = preferred, GCP=0, tunnel=10)
	Priority      int32 `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendInfo) Reset() {
	*x = BackendInfo{}
	mi := &file_containarium_v1_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendInfo) ProtoMessage() {}

func (x *BackendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendInfo.ProtoReflect.Descriptor instead.
func (*BackendInfo) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{13}
}

func (x *BackendInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BackendInfo) GetType() BackendType {
	if x != nil {
		return x.Type
	}
	return BackendType_BACKEND_TYPE_UNSPECIFIED
}

func (x *BackendInfo) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *BackendInfo) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// ListBackendsRequest is the request to list available backends
type ListBackendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackendsRequest) Reset() {
	*x = ListBackendsRequest{}
	mi := &file_containarium_v1_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackendsRequest) ProtoMessage() {}

func (x *ListBackendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackendsRequest.ProtoReflect.Descriptor instead.
func (*ListBackendsRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{14}
}

// ListBackendsResponse is the response from listing backends
type ListBackendsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of available backends
	Backends      []*BackendInfo `protobuf:"bytes,1,rep,name=backends,proto3" json:"backends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackendsResponse) Reset() {
	*x = ListBackendsResponse{}
	mi := &file_containarium_v1_config_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackendsResponse) ProtoMessage() {}

func (x *ListBackendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackendsResponse.ProtoReflect.Descriptor instead.
func (*ListBackendsResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{15}
}

func (x *ListBackendsResponse) GetBackends() []*BackendInfo {
	if x != nil {
		return x.Backends
	}
	return nil
}

var File_containarium_v1_config_proto protoreflect.FileDescriptor

const file_containarium_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x1ccontainarium/v1/config.proto\x12\x0fcontainarium.v1\x1a\x1fcontainarium/v1/container.proto\"\x96\x03\n" +
	"\x06Config\x122\n" +
	"\x05incus\x18\x01 \x01(\v2\x1c.containarium.v1.IncusConfigR\x05incus\x12L\n" +
	"\x11default_resources\x18\x02 \x01(\v2\x1f.containarium.v1.ResourceLimitsR\x10defaultResources\x12#\n" +
	"\rdefault_image\x18\x03 \x01(\tR\fdefaultImage\x124\n" +
	"\x16default_docker_enabled\x18\x04 \x01(\bR\x14defaultDockerEnabled\x128\n" +
	"\anetwork\x18\x05 \x01(\v2\x1e.containarium.v1.NetworkConfigR\anetwork\x128\n" +
	"\astorage\x18\x06 \x01(\v2\x1e.containarium.v1.StorageConfigR\astorage\x12;\n" +
	"\bsecurity\x18\a \x01(\v2\x1f.containarium.v1.SecurityConfigR\bsecurity\"\x89\x01\n" +
	"\vIncusConfig\x12\x1f\n" +
	"\vsocket_path\x18\x01 \x01(\tR\n" +
	"socketPath\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x16\n" +
	"\x06remote\x18\x03 \x01(\tR\x06remote\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\"\xda\x01\n" +
	"\rNetworkConfig\x12\x1f\n" +
	"\vbridge_name\x18\x01 \x01(\tR\n" +
	"bridgeName\x12\x16\n" +
	"\x06subnet\x18\x02 \x01(\tR\x06subnet\x12(\n" +
	"\x10dhcp_range_start\x18\x03 \x01(\tR\x0edhcpRangeStart\x12$\n" +
	"\x0edhcp_range_end\x18\x04 \x01(\tR\fdhcpRangeEnd\x12\x1f\n" +
	"\vdns_servers\x18\x05 \x03(\tR\n" +
	"dnsServers\x12\x1f\n" +
	"\venable_ipv6\x18\x06 \x01(\bR\n" +
	"enableIpv6\"\x8f\x01\n" +
	"\rStorageConfig\x12\x1b\n" +
	"\tpool_name\x18\x01 \x01(\tR\bpoolName\x12\x16\n" +
	"\x06driver\x18\x02 \x01(\tR\x06driver\x12\x1b\n" +
	"\tpool_path\x18\x03 \x01(\tR\bpoolPath\x12,\n" +
	"\x12default_disk_quota\x18\x04 \x01(\tR\x10defaultDiskQuota\"\x9e\x02\n" +
	"\x0eSecurityConfig\x127\n" +
	"\x17unprivileged_containers\x18\x01 \x01(\bR\x16unprivilegedContainers\x12)\n" +
	"\x10apparmor_profile\x18\x02 \x01(\tR\x0fapparmorProfile\x12'\n" +
	"\x0fselinux_context\x18\x03 \x01(\tR\x0eselinuxContext\x12%\n" +
	"\x0eenable_seccomp\x18\x04 \x01(\bR\renableSeccomp\x12(\n" +
	"\x10require_ssh_keys\x18\x05 \x01(\bR\x0erequireSshKeys\x12.\n" +
	"\x13min_password_length\x18\x06 \x01(\x05R\x11minPasswordLength\"\x12\n" +
	"\x10GetConfigRequest\"D\n" +
	"\x11GetConfigResponse\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x17.containarium.v1.ConfigR\x06config\"g\n" +
	"\x13UpdateConfigRequest\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x17.containarium.v1.ConfigR\x06config\x12\x1f\n" +
	"\vupdate_mask\x18\x02 \x03(\tR\n" +
	"updateMask\"a\n" +
	"\x14UpdateConfigResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x17.containarium.v1.ConfigR\x06config\"\xf1\x05\n" +
	"\n" +
	"SystemInfo\x12#\n" +
	"\rincus_version\x18\x01 \x01(\tR\fincusVersion\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12%\n" +
	"\x0ekernel_version\x18\x03 \x01(\tR\rkernelVersion\x12\x1d\n" +
	"\n" +
	"total_cpus\x18\x04 \x01(\x05R\ttotalCpus\x12,\n" +
	"\x12total_memory_bytes\x18\x05 \x01(\x03R\x10totalMemoryBytes\x124\n" +
	"\x16available_memory_bytes\x18\x06 \x01(\x03R\x14availableMemoryBytes\x12(\n" +
	"\x10total_disk_bytes\x18\a \x01(\x03R\x0etotalDiskBytes\x120\n" +
	"\x14available_disk_bytes\x18\b \x01(\x03R\x12availableDiskBytes\x12-\n" +
	"\x12containers_running\x18\t \x01(\x05R\x11containersRunning\x12-\n" +
	"\x12containers_stopped\x18\n" +
	" \x01(\x05R\x11containersStopped\x12)\n" +
	"\x10containers_total\x18\v \x01(\x05R\x0fcontainersTotal\x12\x1a\n" +
	"\bhostname\x18\f \x01(\tR\bhostname\x12%\n" +
	"\x0euptime_seconds\x18\r \x01(\x03R\ruptimeSeconds\x12!\n" +
	"\fnetwork_cidr\x18\x0e \x01(\tR\vnetworkCidr\x12\"\n" +
	"\rcpu_load_1min\x18\x0f \x01(\x01R\vcpuLoad1min\x12\"\n" +
	"\rcpu_load_5min\x18\x10 \x01(\x01R\vcpuLoad5min\x12$\n" +
	"\x0ecpu_load_15min\x18\x11 \x01(\x01R\fcpuLoad15min\x12,\n" +
	"\x04gpus\x18\x12 \x03(\v2\x18.containarium.v1.GPUInfoR\x04gpus\x12\x1d\n" +
	"\n" +
	"backend_id\x18\x13 \x01(\tR\tbackendId\"\x97\x02\n" +
	"\aGPUInfo\x122\n" +
	"\x06vendor\x18\x01 \x01(\x0e2\x1a.containarium.v1.GPUVendorR\x06vendor\x12/\n" +
	"\x05model\x18\x02 \x01(\x0e2\x19.containarium.v1.GPUModelR\x05model\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x12\x1f\n" +
	"\vpci_address\x18\x04 \x01(\tR\n" +
	"pciAddress\x12%\n" +
	"\x0edriver_version\x18\x05 \x01(\tR\rdriverVersion\x12!\n" +
	"\fcuda_version\x18\x06 \x01(\tR\vcudaVersion\x12\x1d\n" +
	"\n" +
	"vram_bytes\x18\a \x01(\x03R\tvramBytes\"\x16\n" +
	"\x14GetSystemInfoRequest\"{\n" +
	"\x15GetSystemInfoResponse\x12/\n" +
	"\x04info\x18\x01 \x01(\v2\x1b.containarium.v1.SystemInfoR\x04info\x121\n" +
	"\x05peers\x18\x02 \x03(\v2\x1b.containarium.v1.SystemInfoR\x05peers\"\x85\x01\n" +
	"\vBackendInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.containarium.v1.BackendTypeR\x04type\x12\x18\n" +
	"\ahealthy\x18\x03 \x01(\bR\ahealthy\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\"\x15\n" +
	"\x13ListBackendsRequest\"P\n" +
	"\x14ListBackendsResponse\x128\n" +
	"\bbackends\x18\x01 \x03(\v2\x1c.containarium.v1.BackendInfoR\bbackends*h\n" +
	"\tGPUVendor\x12\x1a\n" +
	"\x16GPU_VENDOR_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11GPU_VENDOR_NVIDIA\x10\x01\x12\x12\n" +
	"\x0eGPU_VENDOR_AMD\x10\x02\x12\x14\n" +
	"\x10GPU_VENDOR_INTEL\x10\x03*\xe2\x05\n" +
	"\bGPUModel\x12\x19\n" +
	"\x15GPU_MODEL_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19GPU_MODEL_NVIDIA_RTX_4090\x10d\x12\x1d\n" +
	"\x19GPU_MODEL_NVIDIA_RTX_4080\x10e\x12 \n" +
	"\x1cGPU_MODEL_NVIDIA_RTX_4070_TI\x10f\x12\x1d\n" +
	"\x19GPU_MODEL_NVIDIA_RTX_4070\x10g\x12\x1d\n" +
	"\x19GPU_MODEL_NVIDIA_RTX_3090\x10h\x12\x1d\n" +
	"\x19GPU_MODEL_NVIDIA_RTX_3080\x10i\x12\x1d\n" +
	"\x19GPU_MODEL_NVIDIA_RTX_5090\x10j\x12\x1d\n" +
	"\x19GPU_MODEL_NVIDIA_RTX_5080\x10k\x12\x1a\n" +
	"\x15GPU_MODEL_NVIDIA_A100\x10\xc8\x01\x12\x19\n" +
	"\x14GPU_MODEL_NVIDIA_A10\x10\xc9\x01\x12\x1a\n" +
	"\x15GPU_MODEL_NVIDIA_A10G\x10\xca\x01\x12\x1a\n" +
	"\x15GPU_MODEL_NVIDIA_H100\x10\xcb\x01\x12\x1a\n" +
	"\x15GPU_MODEL_NVIDIA_H200\x10\xcc\x01\x12\x18\n" +
	"\x13GPU_MODEL_NVIDIA_L4\x10\xcd\x01\x12\x19\n" +
	"\x14GPU_MODEL_NVIDIA_L40\x10\xce\x01\x12\x1a\n" +
	"\x15GPU_MODEL_NVIDIA_L40S\x10\xcf\x01\x12\x18\n" +
	"\x13GPU_MODEL_NVIDIA_T4\x10\xd0\x01\x12\x1a\n" +
	"\x15GPU_MODEL_NVIDIA_V100\x10\xd1\x01\x12\x1a\n" +
	"\x15GPU_MODEL_NVIDIA_B200\x10\xd2\x01\x12\x19\n" +
	"\x14GPU_MODEL_AMD_MI300X\x10\xac\x02\x12\x19\n" +
	"\x14GPU_MODEL_AMD_MI250X\x10\xad\x02\x12\x1e\n" +
	"\x19GPU_MODEL_AMD_RX_7900_XTX\x10\xae\x02\x12\x1d\n" +
	"\x18GPU_MODEL_INTEL_MAX_1550\x10\x90\x03\x12\x1d\n" +
	"\x18GPU_MODEL_INTEL_ARC_A770\x10\x91\x03*Z\n" +
	"\vBackendType\x12\x1c\n" +
	"\x18BACKEND_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10BACKEND_TYPE_GCP\x10\x01\x12\x17\n" +
	"\x13BACKEND_TYPE_TUNNEL\x10\x02BKZIgithub.com/footprintai/containarium/pkg/pb/containarium/v1;containariumv1b\x06proto3"

var (
	file_containarium_v1_config_proto_rawDescOnce sync.Once
	file_containarium_v1_config_proto_rawDescData []byte
)

func file_containarium_v1_config_proto_rawDescGZIP() []byte {
	file_containarium_v1_config_proto_rawDescOnce.Do(func() {
		file_containarium_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_containarium_v1_config_proto_rawDesc), len(file_containarium_v1_config_proto_rawDesc)))
	})
	return file_containarium_v1_config_proto_rawDescData
}

var file_containarium_v1_config_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_containarium_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_containarium_v1_config_proto_goTypes = []any{
	(GPUVendor)(0),                // 0: containarium.v1.GPUVendor
	(GPUModel)(0),                 // 1: containarium.v1.GPUModel
	(BackendType)(0),              // 2: containarium.v1.BackendType
	(*Config)(nil),                // 3: containarium.v1.Config
	(*IncusConfig)(nil),           // 4: containarium.v1.IncusConfig
	(*NetworkConfig)(nil),         // 5: containarium.v1.NetworkConfig
	(*StorageConfig)(nil),         // 6: containarium.v1.StorageConfig
	(*SecurityConfig)(nil),        // 7: containarium.v1.SecurityConfig
	(*GetConfigRequest)(nil),      // 8: containarium.v1.GetConfigRequest
	(*GetConfigResponse)(nil),     // 9: containarium.v1.GetConfigResponse
	(*UpdateConfigRequest)(nil),   // 10: containarium.v1.UpdateConfigRequest
	(*UpdateConfigResponse)(nil),  // 11: containarium.v1.UpdateConfigResponse
	(*SystemInfo)(nil),            // 12: containarium.v1.SystemInfo
	(*GPUInfo)(nil),               // 13: containarium.v1.GPUInfo
	(*GetSystemInfoRequest)(nil),  // 14: containarium.v1.GetSystemInfoRequest
	(*GetSystemInfoResponse)(nil), // 15: containarium.v1.GetSystemInfoResponse
	(*BackendInfo)(nil),           // 16: containarium.v1.BackendInfo
	(*ListBackendsRequest)(nil),   // 17: containarium.v1.ListBackendsRequest
	(*ListBackendsResponse)(nil),  // 18: containarium.v1.ListBackendsResponse
	(*ResourceLimits)(nil),        // 19: containarium.v1.ResourceLimits
}
var file_containarium_v1_config_proto_depIdxs = []int32{
	4,  // 0: containarium.v1.Config.incus:type_name -> containarium.v1.IncusConfig
	19, // 1: containarium.v1.Config.default_resources:type_name -> containarium.v1.ResourceLimits
	5,  // 2: containarium.v1.Config.network:type_name -> containarium.v1.NetworkConfig
	6,  // 3: containarium.v1.Config.storage:type_name -> containarium.v1.StorageConfig
	7,  // 4: containarium.v1.Config.security:type_name -> containarium.v1.SecurityConfig
	3,  // 5: containarium.v1.GetConfigResponse.config:type_name -> containarium.v1.Config
	3,  // 6: containarium.v1.UpdateConfigRequest.config:type_name -> containarium.v1.Config
	3,  // 7: containarium.v1.UpdateConfigResponse.config:type_name -> containarium.v1.Config
	13, // 8: containarium.v1.SystemInfo.gpus:type_name -> containarium.v1.GPUInfo
	0,  // 9: containarium.v1.GPUInfo.vendor:type_name -> containarium.v1.GPUVendor
	1,  // 10: containarium.v1.GPUInfo.model:type_name -> containarium.v1.GPUModel
	12, // 11: containarium.v1.GetSystemInfoResponse.info:type_name -> containarium.v1.SystemInfo
	12, // 12: containarium.v1.GetSystemInfoResponse.peers:type_name -> containarium.v1.SystemInfo
	2,  // 13: containarium.v1.BackendInfo.type:type_name -> containarium.v1.BackendType
	16, // 14: containarium.v1.ListBackendsResponse.backends:type_name -> containarium.v1.BackendInfo
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_containarium_v1_config_proto_init() }
func file_containarium_v1_config_proto_init() {
	if File_containarium_v1_config_proto != nil {
		return
	}
	file_containarium_v1_container_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_containarium_v1_config_proto_rawDesc), len(file_containarium_v1_config_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_containarium_v1_config_proto_goTypes,
		DependencyIndexes: file_containarium_v1_config_proto_depIdxs,
		EnumInfos:         file_containarium_v1_config_proto_enumTypes,
		MessageInfos:      file_containarium_v1_config_proto_msgTypes,
	}.Build()
	File_containarium_v1_config_proto = out.File
	file_containarium_v1_config_proto_goTypes = nil
	file_containarium_v1_config_proto_depIdxs = nil
}
