// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: containarium/v1/config.proto

package containariumv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GPU vendor enum
type GPUVendor int32

const (
	GPUVendor_GPU_VENDOR_UNSPECIFIED GPUVendor = 0
	GPUVendor_GPU_VENDOR_NVIDIA      GPUVendor = 1
	GPUVendor_GPU_VENDOR_AMD         GPUVendor = 2
	GPUVendor_GPU_VENDOR_INTEL       GPUVendor = 3
)

// Enum value maps for GPUVendor.
var (
	GPUVendor_name = map[int32]string{
		0: "GPU_VENDOR_UNSPECIFIED",
		1: "GPU_VENDOR_NVIDIA",
		2: "GPU_VENDOR_AMD",
		3: "GPU_VENDOR_INTEL",
	}
	GPUVendor_value = map[string]int32{
		"GPU_VENDOR_UNSPECIFIED": 0,
		"GPU_VENDOR_NVIDIA":      1,
		"GPU_VENDOR_AMD":         2,
		"GPU_VENDOR_INTEL":       3,
	}
)

func (x GPUVendor) Enum() *GPUVendor {
	p := new(GPUVendor)
	*p = x
	return p
}

func (x GPUVendor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GPUVendor) Descriptor() protoreflect.EnumDescriptor {
	return file_containarium_v1_config_proto_enumTypes[0].Descriptor()
}

func (GPUVendor) Type() protoreflect.EnumType {
	return &file_containarium_v1_config_proto_enumTypes[0]
}

func (x GPUVendor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GPUVendor.Descriptor instead.
func (GPUVendor) EnumDescriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{0}
}

// GPU model enum (common datacenter and workstation GPUs)
type GPUModel int32

const (
	GPUModel_GPU_MODEL_UNSPECIFIED GPUModel = 0
	// NVIDIA Consumer
	GPUModel_GPU_MODEL_NVIDIA_RTX_4090    GPUModel = 100
	GPUModel_GPU_MODEL_NVIDIA_RTX_4080    GPUModel = 101
	GPUModel_GPU_MODEL_NVIDIA_RTX_4070_TI GPUModel = 102
	GPUModel_GPU_MODEL_NVIDIA_RTX_4070    GPUModel = 103
	GPUModel_GPU_MODEL_NVIDIA_RTX_3090    GPUModel = 104
	GPUModel_GPU_MODEL_NVIDIA_RTX_3080    GPUModel = 105
	GPUModel_GPU_MODEL_NVIDIA_RTX_5090    GPUModel = 106
	GPUModel_GPU_MODEL_NVIDIA_RTX_5080    GPUModel = 107
	// NVIDIA Datacenter
	GPUModel_GPU_MODEL_NVIDIA_A100 GPUModel = 200
	GPUModel_GPU_MODEL_NVIDIA_A10  GPUModel = 201
	GPUModel_GPU_MODEL_NVIDIA_A10G GPUModel = 202
	GPUModel_GPU_MODEL_NVIDIA_H100 GPUModel = 203
	GPUModel_GPU_MODEL_NVIDIA_H200 GPUModel = 204
	GPUModel_GPU_MODEL_NVIDIA_L4   GPUModel = 205
	GPUModel_GPU_MODEL_NVIDIA_L40  GPUModel = 206
	GPUModel_GPU_MODEL_NVIDIA_L40S GPUModel = 207
	GPUModel_GPU_MODEL_NVIDIA_T4   GPUModel = 208
	GPUModel_GPU_MODEL_NVIDIA_V100 GPUModel = 209
	GPUModel_GPU_MODEL_NVIDIA_B200 GPUModel = 210
	// AMD
	GPUModel_GPU_MODEL_AMD_MI300X      GPUModel = 300
	GPUModel_GPU_MODEL_AMD_MI250X      GPUModel = 301
	GPUModel_GPU_MODEL_AMD_RX_7900_XTX GPUModel = 302
	// Intel
	GPUModel_GPU_MODEL_INTEL_MAX_1550 GPUModel = 400
	GPUModel_GPU_MODEL_INTEL_ARC_A770 GPUModel = 401
)

// Enum value maps for GPUModel.
var (
	GPUModel_name = map[int32]string{
		0:   "GPU_MODEL_UNSPECIFIED",
		100: "GPU_MODEL_NVIDIA_RTX_4090",
		101: "GPU_MODEL_NVIDIA_RTX_4080",
		102: "GPU_MODEL_NVIDIA_RTX_4070_TI",
		103: "GPU_MODEL_NVIDIA_RTX_4070",
		104: "GPU_MODEL_NVIDIA_RTX_3090",
		105: "GPU_MODEL_NVIDIA_RTX_3080",
		106: "GPU_MODEL_NVIDIA_RTX_5090",
		107: "GPU_MODEL_NVIDIA_RTX_5080",
		200: "GPU_MODEL_NVIDIA_A100",
		201: "GPU_MODEL_NVIDIA_A10",
		202: "GPU_MODEL_NVIDIA_A10G",
		203: "GPU_MODEL_NVIDIA_H100",
		204: "GPU_MODEL_NVIDIA_H200",
		205: "GPU_MODEL_NVIDIA_L4",
		206: "GPU_MODEL_NVIDIA_L40",
		207: "GPU_MODEL_NVIDIA_L40S",
		208: "GPU_MODEL_NVIDIA_T4",
		209: "GPU_MODEL_NVIDIA_V100",
		210: "GPU_MODEL_NVIDIA_B200",
		300: "GPU_MODEL_AMD_MI300X",
		301: "GPU_MODEL_AMD_MI250X",
		302: "GPU_MODEL_AMD_RX_7900_XTX",
		400: "GPU_MODEL_INTEL_MAX_1550",
		401: "GPU_MODEL_INTEL_ARC_A770",
	}
	GPUModel_value = map[string]int32{
		"GPU_MODEL_UNSPECIFIED":        0,
		"GPU_MODEL_NVIDIA_RTX_4090":    100,
		"GPU_MODEL_NVIDIA_RTX_4080":    101,
		"GPU_MODEL_NVIDIA_RTX_4070_TI": 102,
		"GPU_MODEL_NVIDIA_RTX_4070":    103,
		"GPU_MODEL_NVIDIA_RTX_3090":    104,
		"GPU_MODEL_NVIDIA_RTX_3080":    105,
		"GPU_MODEL_NVIDIA_RTX_5090":    106,
		"GPU_MODEL_NVIDIA_RTX_5080":    107,
		"GPU_MODEL_NVIDIA_A100":        200,
		"GPU_MODEL_NVIDIA_A10":         201,
		"GPU_MODEL_NVIDIA_A10G":        202,
		"GPU_MODEL_NVIDIA_H100":        203,
		"GPU_MODEL_NVIDIA_H200":        204,
		"GPU_MODEL_NVIDIA_L4":          205,
		"GPU_MODEL_NVIDIA_L40":         206,
		"GPU_MODEL_NVIDIA_L40S":        207,
		"GPU_MODEL_NVIDIA_T4":          208,
		"GPU_MODEL_NVIDIA_V100":        209,
		"GPU_MODEL_NVIDIA_B200":        210,
		"GPU_MODEL_AMD_MI300X":         300,
		"GPU_MODEL_AMD_MI250X":         301,
		"GPU_MODEL_AMD_RX_7900_XTX":    302,
		"GPU_MODEL_INTEL_MAX_1550":     400,
		"GPU_MODEL_INTEL_ARC_A770":     401,
	}
)

func (x GPUModel) Enum() *GPUModel {
	p := new(GPUModel)
	*p = x
	return p
}

func (x GPUModel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GPUModel) Descriptor() protoreflect.EnumDescriptor {
	return file_containarium_v1_config_proto_enumTypes[1].Descriptor()
}

func (GPUModel) Type() protoreflect.EnumType {
	return &file_containarium_v1_config_proto_enumTypes[1]
}

func (x GPUModel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GPUModel.Descriptor instead.
func (GPUModel) EnumDescriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{1}
}

// NetworkPolicyMode controls whether a tenant's network policy is enforced or
// only observed. Phase A ships log_only; Phase B flips to enforce. See
// docs/security/NETWORK-ISOLATION-DESIGN.md (#315).
type NetworkPolicyMode int32

const (
	NetworkPolicyMode_NETWORK_POLICY_MODE_UNSPECIFIED NetworkPolicyMode = 0 // treated as LOG_ONLY in Phase A
	NetworkPolicyMode_NETWORK_POLICY_MODE_LOG_ONLY    NetworkPolicyMode = 1 // observe + audit denied flows; drop nothing
	NetworkPolicyMode_NETWORK_POLICY_MODE_ENFORCE     NetworkPolicyMode = 2 // actually drop denied flows
)

// Enum value maps for NetworkPolicyMode.
var (
	NetworkPolicyMode_name = map[int32]string{
		0: "NETWORK_POLICY_MODE_UNSPECIFIED",
		1: "NETWORK_POLICY_MODE_LOG_ONLY",
		2: "NETWORK_POLICY_MODE_ENFORCE",
	}
	NetworkPolicyMode_value = map[string]int32{
		"NETWORK_POLICY_MODE_UNSPECIFIED": 0,
		"NETWORK_POLICY_MODE_LOG_ONLY":    1,
		"NETWORK_POLICY_MODE_ENFORCE":     2,
	}
)

func (x NetworkPolicyMode) Enum() *NetworkPolicyMode {
	p := new(NetworkPolicyMode)
	*p = x
	return p
}

func (x NetworkPolicyMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkPolicyMode) Descriptor() protoreflect.EnumDescriptor {
	return file_containarium_v1_config_proto_enumTypes[2].Descriptor()
}

func (NetworkPolicyMode) Type() protoreflect.EnumType {
	return &file_containarium_v1_config_proto_enumTypes[2]
}

func (x NetworkPolicyMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkPolicyMode.Descriptor instead.
func (NetworkPolicyMode) EnumDescriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{2}
}

// BackendType represents the type of backend instance
type BackendType int32

const (
	BackendType_BACKEND_TYPE_UNSPECIFIED BackendType = 0
	BackendType_BACKEND_TYPE_GCP         BackendType = 1
	BackendType_BACKEND_TYPE_TUNNEL      BackendType = 2
)

// Enum value maps for BackendType.
var (
	BackendType_name = map[int32]string{
		0: "BACKEND_TYPE_UNSPECIFIED",
		1: "BACKEND_TYPE_GCP",
		2: "BACKEND_TYPE_TUNNEL",
	}
	BackendType_value = map[string]int32{
		"BACKEND_TYPE_UNSPECIFIED": 0,
		"BACKEND_TYPE_GCP":         1,
		"BACKEND_TYPE_TUNNEL":      2,
	}
)

func (x BackendType) Enum() *BackendType {
	p := new(BackendType)
	*p = x
	return p
}

func (x BackendType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackendType) Descriptor() protoreflect.EnumDescriptor {
	return file_containarium_v1_config_proto_enumTypes[3].Descriptor()
}

func (BackendType) Type() protoreflect.EnumType {
	return &file_containarium_v1_config_proto_enumTypes[3]
}

func (x BackendType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackendType.Descriptor instead.
func (BackendType) EnumDescriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{3}
}

type ValidateGPUResponse_GPUStatus int32

const (
	ValidateGPUResponse_GPU_STATUS_UNSPECIFIED ValidateGPUResponse_GPUStatus = 0
	ValidateGPUResponse_GPU_STATUS_OK          ValidateGPUResponse_GPUStatus = 1 // nvidia-smi saw the GPU inside the LXC
	ValidateGPUResponse_GPU_STATUS_UNAVAILABLE ValidateGPUResponse_GPUStatus = 2 // no GPU / passthrough not visible / setup failed
	ValidateGPUResponse_GPU_STATUS_DEGRADED    ValidateGPUResponse_GPUStatus = 3 // reserved (e.g. present but reporting errors)
)

// Enum value maps for ValidateGPUResponse_GPUStatus.
var (
	ValidateGPUResponse_GPUStatus_name = map[int32]string{
		0: "GPU_STATUS_UNSPECIFIED",
		1: "GPU_STATUS_OK",
		2: "GPU_STATUS_UNAVAILABLE",
		3: "GPU_STATUS_DEGRADED",
	}
	ValidateGPUResponse_GPUStatus_value = map[string]int32{
		"GPU_STATUS_UNSPECIFIED": 0,
		"GPU_STATUS_OK":          1,
		"GPU_STATUS_UNAVAILABLE": 2,
		"GPU_STATUS_DEGRADED":    3,
	}
)

func (x ValidateGPUResponse_GPUStatus) Enum() *ValidateGPUResponse_GPUStatus {
	p := new(ValidateGPUResponse_GPUStatus)
	*p = x
	return p
}

func (x ValidateGPUResponse_GPUStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidateGPUResponse_GPUStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_containarium_v1_config_proto_enumTypes[4].Descriptor()
}

func (ValidateGPUResponse_GPUStatus) Type() protoreflect.EnumType {
	return &file_containarium_v1_config_proto_enumTypes[4]
}

func (x ValidateGPUResponse_GPUStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidateGPUResponse_GPUStatus.Descriptor instead.
func (ValidateGPUResponse_GPUStatus) EnumDescriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{16, 0}
}

// Config represents the system-wide configuration for Containarium
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Incus configuration
	Incus *IncusConfig `protobuf:"bytes,1,opt,name=incus,proto3" json:"incus,omitempty"`
	// Default resource limits for new containers
	DefaultResources *ResourceLimits `protobuf:"bytes,2,opt,name=default_resources,json=defaultResources,proto3" json:"default_resources,omitempty"`
	// Default container image
	DefaultImage string `protobuf:"bytes,3,opt,name=default_image,json=defaultImage,proto3" json:"default_image,omitempty"`
	// Enable Docker support by default
	DefaultDockerEnabled bool `protobuf:"varint,4,opt,name=default_docker_enabled,json=defaultDockerEnabled,proto3" json:"default_docker_enabled,omitempty"`
	// Network configuration
	Network *NetworkConfig `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	// Storage configuration
	Storage *StorageConfig `protobuf:"bytes,6,opt,name=storage,proto3" json:"storage,omitempty"`
	// Security configuration
	Security *SecurityConfig `protobuf:"bytes,7,opt,name=security,proto3" json:"security,omitempty"`
	// Default OS type for new containers
	DefaultOsType OSType `protobuf:"varint,8,opt,name=default_os_type,json=defaultOsType,proto3,enum=containarium.v1.OSType" json:"default_os_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_containarium_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetIncus() *IncusConfig {
	if x != nil {
		return x.Incus
	}
	return nil
}

func (x *Config) GetDefaultResources() *ResourceLimits {
	if x != nil {
		return x.DefaultResources
	}
	return nil
}

func (x *Config) GetDefaultImage() string {
	if x != nil {
		return x.DefaultImage
	}
	return ""
}

func (x *Config) GetDefaultDockerEnabled() bool {
	if x != nil {
		return x.DefaultDockerEnabled
	}
	return false
}

func (x *Config) GetNetwork() *NetworkConfig {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *Config) GetStorage() *StorageConfig {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *Config) GetSecurity() *SecurityConfig {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *Config) GetDefaultOsType() OSType {
	if x != nil {
		return x.DefaultOsType
	}
	return OSType_OS_TYPE_UNSPECIFIED
}

// IncusConfig contains Incus-specific configuration
type IncusConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Incus socket path (default: /var/lib/incus/unix.socket)
	SocketPath string `protobuf:"bytes,1,opt,name=socket_path,json=socketPath,proto3" json:"socket_path,omitempty"`
	// Project name to use (default: default)
	Project string `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	// Remote name (default: local)
	Remote string `protobuf:"bytes,3,opt,name=remote,proto3" json:"remote,omitempty"`
	// Timeout for Incus operations in seconds
	TimeoutSeconds int32 `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IncusConfig) Reset() {
	*x = IncusConfig{}
	mi := &file_containarium_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncusConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncusConfig) ProtoMessage() {}

func (x *IncusConfig) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncusConfig.ProtoReflect.Descriptor instead.
func (*IncusConfig) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *IncusConfig) GetSocketPath() string {
	if x != nil {
		return x.SocketPath
	}
	return ""
}

func (x *IncusConfig) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *IncusConfig) GetRemote() string {
	if x != nil {
		return x.Remote
	}
	return ""
}

func (x *IncusConfig) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// NetworkConfig contains network-related configuration
type NetworkConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network bridge name (default: incusbr0)
	BridgeName string `protobuf:"bytes,1,opt,name=bridge_name,json=bridgeName,proto3" json:"bridge_name,omitempty"`
	// Subnet for container IPs (e.g., "10.0.3.0/24")
	Subnet string `protobuf:"bytes,2,opt,name=subnet,proto3" json:"subnet,omitempty"`
	// DHCP range start
	DhcpRangeStart string `protobuf:"bytes,3,opt,name=dhcp_range_start,json=dhcpRangeStart,proto3" json:"dhcp_range_start,omitempty"`
	// DHCP range end
	DhcpRangeEnd string `protobuf:"bytes,4,opt,name=dhcp_range_end,json=dhcpRangeEnd,proto3" json:"dhcp_range_end,omitempty"`
	// DNS servers for containers
	DnsServers []string `protobuf:"bytes,5,rep,name=dns_servers,json=dnsServers,proto3" json:"dns_servers,omitempty"`
	// Enable IPv6
	EnableIpv6    bool `protobuf:"varint,6,opt,name=enable_ipv6,json=enableIpv6,proto3" json:"enable_ipv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_containarium_v1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{2}
}

func (x *NetworkConfig) GetBridgeName() string {
	if x != nil {
		return x.BridgeName
	}
	return ""
}

func (x *NetworkConfig) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

func (x *NetworkConfig) GetDhcpRangeStart() string {
	if x != nil {
		return x.DhcpRangeStart
	}
	return ""
}

func (x *NetworkConfig) GetDhcpRangeEnd() string {
	if x != nil {
		return x.DhcpRangeEnd
	}
	return ""
}

func (x *NetworkConfig) GetDnsServers() []string {
	if x != nil {
		return x.DnsServers
	}
	return nil
}

func (x *NetworkConfig) GetEnableIpv6() bool {
	if x != nil {
		return x.EnableIpv6
	}
	return false
}

// StorageConfig contains storage-related configuration
type StorageConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Storage pool name
	PoolName string `protobuf:"bytes,1,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"`
	// Storage driver (e.g., "dir", "zfs", "btrfs")
	Driver string `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"`
	// Storage pool path
	PoolPath string `protobuf:"bytes,3,opt,name=pool_path,json=poolPath,proto3" json:"pool_path,omitempty"`
	// Default disk quota for containers
	DefaultDiskQuota string `protobuf:"bytes,4,opt,name=default_disk_quota,json=defaultDiskQuota,proto3" json:"default_disk_quota,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StorageConfig) Reset() {
	*x = StorageConfig{}
	mi := &file_containarium_v1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageConfig) ProtoMessage() {}

func (x *StorageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageConfig.ProtoReflect.Descriptor instead.
func (*StorageConfig) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{3}
}

func (x *StorageConfig) GetPoolName() string {
	if x != nil {
		return x.PoolName
	}
	return ""
}

func (x *StorageConfig) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *StorageConfig) GetPoolPath() string {
	if x != nil {
		return x.PoolPath
	}
	return ""
}

func (x *StorageConfig) GetDefaultDiskQuota() string {
	if x != nil {
		return x.DefaultDiskQuota
	}
	return ""
}

// SecurityConfig contains security-related configuration
type SecurityConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Use unprivileged containers (recommended: true)
	UnprivilegedContainers bool `protobuf:"varint,1,opt,name=unprivileged_containers,json=unprivilegedContainers,proto3" json:"unprivileged_containers,omitempty"`
	// AppArmor profile to use (default: "default")
	ApparmorProfile string `protobuf:"bytes,2,opt,name=apparmor_profile,json=apparmorProfile,proto3" json:"apparmor_profile,omitempty"`
	// SELinux context (if using SELinux)
	SelinuxContext string `protobuf:"bytes,3,opt,name=selinux_context,json=selinuxContext,proto3" json:"selinux_context,omitempty"`
	// Enable seccomp filtering
	EnableSeccomp bool `protobuf:"varint,4,opt,name=enable_seccomp,json=enableSeccomp,proto3" json:"enable_seccomp,omitempty"`
	// Require SSH keys (don't allow password auth)
	RequireSshKeys bool `protobuf:"varint,5,opt,name=require_ssh_keys,json=requireSshKeys,proto3" json:"require_ssh_keys,omitempty"`
	// Minimum password length if passwords are allowed
	MinPasswordLength int32 `protobuf:"varint,6,opt,name=min_password_length,json=minPasswordLength,proto3" json:"min_password_length,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SecurityConfig) Reset() {
	*x = SecurityConfig{}
	mi := &file_containarium_v1_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityConfig) ProtoMessage() {}

func (x *SecurityConfig) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityConfig.ProtoReflect.Descriptor instead.
func (*SecurityConfig) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{4}
}

func (x *SecurityConfig) GetUnprivilegedContainers() bool {
	if x != nil {
		return x.UnprivilegedContainers
	}
	return false
}

func (x *SecurityConfig) GetApparmorProfile() string {
	if x != nil {
		return x.ApparmorProfile
	}
	return ""
}

func (x *SecurityConfig) GetSelinuxContext() string {
	if x != nil {
		return x.SelinuxContext
	}
	return ""
}

func (x *SecurityConfig) GetEnableSeccomp() bool {
	if x != nil {
		return x.EnableSeccomp
	}
	return false
}

func (x *SecurityConfig) GetRequireSshKeys() bool {
	if x != nil {
		return x.RequireSshKeys
	}
	return false
}

func (x *SecurityConfig) GetMinPasswordLength() int32 {
	if x != nil {
		return x.MinPasswordLength
	}
	return 0
}

// GetConfigRequest is the request to get current configuration
type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_containarium_v1_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{5}
}

// GetConfigResponse is the response from getting configuration
type GetConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current configuration
	Config        *Config `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_containarium_v1_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{6}
}

func (x *GetConfigResponse) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

// UpdateConfigRequest is the request to update configuration
type UpdateConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated configuration
	Config *Config `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// Fields to update (if empty, update all)
	UpdateMask    []string `protobuf:"bytes,2,rep,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_containarium_v1_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateConfigRequest) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UpdateConfigRequest) GetUpdateMask() []string {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// UpdateConfigResponse is the response from updating configuration
type UpdateConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success message
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Updated configuration
	Config        *Config `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	mi := &file_containarium_v1_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateConfigResponse) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

// SystemInfo contains information about the host system
type SystemInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Incus version
	IncusVersion string `protobuf:"bytes,1,opt,name=incus_version,json=incusVersion,proto3" json:"incus_version,omitempty"`
	// Operating system
	Os string `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	// Kernel version
	KernelVersion string `protobuf:"bytes,3,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	// Total CPU cores
	TotalCpus int32 `protobuf:"varint,4,opt,name=total_cpus,json=totalCpus,proto3" json:"total_cpus,omitempty"`
	// Total memory in bytes
	TotalMemoryBytes int64 `protobuf:"varint,5,opt,name=total_memory_bytes,json=totalMemoryBytes,proto3" json:"total_memory_bytes,omitempty"`
	// Available memory in bytes
	AvailableMemoryBytes int64 `protobuf:"varint,6,opt,name=available_memory_bytes,json=availableMemoryBytes,proto3" json:"available_memory_bytes,omitempty"`
	// Total disk space in bytes
	TotalDiskBytes int64 `protobuf:"varint,7,opt,name=total_disk_bytes,json=totalDiskBytes,proto3" json:"total_disk_bytes,omitempty"`
	// Available disk space in bytes
	AvailableDiskBytes int64 `protobuf:"varint,8,opt,name=available_disk_bytes,json=availableDiskBytes,proto3" json:"available_disk_bytes,omitempty"`
	// Number of containers running
	ContainersRunning int32 `protobuf:"varint,9,opt,name=containers_running,json=containersRunning,proto3" json:"containers_running,omitempty"`
	// Number of containers stopped
	ContainersStopped int32 `protobuf:"varint,10,opt,name=containers_stopped,json=containersStopped,proto3" json:"containers_stopped,omitempty"`
	// Total number of containers
	ContainersTotal int32 `protobuf:"varint,11,opt,name=containers_total,json=containersTotal,proto3" json:"containers_total,omitempty"`
	// Hostname of the system
	Hostname string `protobuf:"bytes,12,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Uptime in seconds
	UptimeSeconds int64 `protobuf:"varint,13,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// Container network CIDR (e.g., "10.100.0.0/24")
	NetworkCidr string `protobuf:"bytes,14,opt,name=network_cidr,json=networkCidr,proto3" json:"network_cidr,omitempty"`
	// CPU load average (1 minute)
	CpuLoad_1Min float64 `protobuf:"fixed64,15,opt,name=cpu_load_1min,json=cpuLoad1min,proto3" json:"cpu_load_1min,omitempty"`
	// CPU load average (5 minutes)
	CpuLoad_5Min float64 `protobuf:"fixed64,16,opt,name=cpu_load_5min,json=cpuLoad5min,proto3" json:"cpu_load_5min,omitempty"`
	// CPU load average (15 minutes)
	CpuLoad_15Min float64 `protobuf:"fixed64,17,opt,name=cpu_load_15min,json=cpuLoad15min,proto3" json:"cpu_load_15min,omitempty"`
	// GPU information
	Gpus []*GPUInfo `protobuf:"bytes,18,rep,name=gpus,proto3" json:"gpus,omitempty"`
	// Backend ID (e.g., "tunnel-node-a-gpu") — set when returned from peer
	BackendId string `protobuf:"bytes,19,opt,name=backend_id,json=backendId,proto3" json:"backend_id,omitempty"`
	// OTLP collector endpoint (e.g., "http://10.0.3.5:4318") that
	// monitoring=true containers ship app telemetry to. Empty when the
	// core OTel collector isn't provisioned. Advertised here so a tenant
	// or agent can discover where to point OTEL_EXPORTER_OTLP_ENDPOINT —
	// in particular for docker-in-LXC apps that don't inherit the
	// env-stamped value. See #370.
	OtelCollectorEndpoint string `protobuf:"bytes,20,opt,name=otel_collector_endpoint,json=otelCollectorEndpoint,proto3" json:"otel_collector_endpoint,omitempty"`
	// Containarium daemon version of this backend (e.g. "0.21.0"), so the
	// fleet's running versions + drift are visible via get_system_info and
	// /v1/backends without SSHing each host. See #354.
	DaemonVersion string `protobuf:"bytes,21,opt,name=daemon_version,json=daemonVersion,proto3" json:"daemon_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_containarium_v1_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{9}
}

func (x *SystemInfo) GetIncusVersion() string {
	if x != nil {
		return x.IncusVersion
	}
	return ""
}

func (x *SystemInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SystemInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *SystemInfo) GetTotalCpus() int32 {
	if x != nil {
		return x.TotalCpus
	}
	return 0
}

func (x *SystemInfo) GetTotalMemoryBytes() int64 {
	if x != nil {
		return x.TotalMemoryBytes
	}
	return 0
}

func (x *SystemInfo) GetAvailableMemoryBytes() int64 {
	if x != nil {
		return x.AvailableMemoryBytes
	}
	return 0
}

func (x *SystemInfo) GetTotalDiskBytes() int64 {
	if x != nil {
		return x.TotalDiskBytes
	}
	return 0
}

func (x *SystemInfo) GetAvailableDiskBytes() int64 {
	if x != nil {
		return x.AvailableDiskBytes
	}
	return 0
}

func (x *SystemInfo) GetContainersRunning() int32 {
	if x != nil {
		return x.ContainersRunning
	}
	return 0
}

func (x *SystemInfo) GetContainersStopped() int32 {
	if x != nil {
		return x.ContainersStopped
	}
	return 0
}

func (x *SystemInfo) GetContainersTotal() int32 {
	if x != nil {
		return x.ContainersTotal
	}
	return 0
}

func (x *SystemInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SystemInfo) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *SystemInfo) GetNetworkCidr() string {
	if x != nil {
		return x.NetworkCidr
	}
	return ""
}

func (x *SystemInfo) GetCpuLoad_1Min() float64 {
	if x != nil {
		return x.CpuLoad_1Min
	}
	return 0
}

func (x *SystemInfo) GetCpuLoad_5Min() float64 {
	if x != nil {
		return x.CpuLoad_5Min
	}
	return 0
}

func (x *SystemInfo) GetCpuLoad_15Min() float64 {
	if x != nil {
		return x.CpuLoad_15Min
	}
	return 0
}

func (x *SystemInfo) GetGpus() []*GPUInfo {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *SystemInfo) GetBackendId() string {
	if x != nil {
		return x.BackendId
	}
	return ""
}

func (x *SystemInfo) GetOtelCollectorEndpoint() string {
	if x != nil {
		return x.OtelCollectorEndpoint
	}
	return ""
}

func (x *SystemInfo) GetDaemonVersion() string {
	if x != nil {
		return x.DaemonVersion
	}
	return ""
}

// GPUInfo represents a GPU device on the system
type GPUInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// GPU vendor
	Vendor GPUVendor `protobuf:"varint,1,opt,name=vendor,proto3,enum=containarium.v1.GPUVendor" json:"vendor,omitempty"`
	// GPU model (known models mapped to enum, or UNSPECIFIED for unknown)
	Model GPUModel `protobuf:"varint,2,opt,name=model,proto3,enum=containarium.v1.GPUModel" json:"model,omitempty"`
	// Raw model name string from the driver (for display when model is UNSPECIFIED)
	ModelName string `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// PCI address (e.g., "0000:0b:00.0")
	PciAddress string `protobuf:"bytes,4,opt,name=pci_address,json=pciAddress,proto3" json:"pci_address,omitempty"`
	// Driver version (e.g., "570.86.15")
	DriverVersion string `protobuf:"bytes,5,opt,name=driver_version,json=driverVersion,proto3" json:"driver_version,omitempty"`
	// CUDA version (e.g., "12.7") — NVIDIA only
	CudaVersion string `protobuf:"bytes,6,opt,name=cuda_version,json=cudaVersion,proto3" json:"cuda_version,omitempty"`
	// VRAM in bytes (when available)
	VramBytes     int64 `protobuf:"varint,7,opt,name=vram_bytes,json=vramBytes,proto3" json:"vram_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUInfo) Reset() {
	*x = GPUInfo{}
	mi := &file_containarium_v1_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUInfo) ProtoMessage() {}

func (x *GPUInfo) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUInfo.ProtoReflect.Descriptor instead.
func (*GPUInfo) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{10}
}

func (x *GPUInfo) GetVendor() GPUVendor {
	if x != nil {
		return x.Vendor
	}
	return GPUVendor_GPU_VENDOR_UNSPECIFIED
}

func (x *GPUInfo) GetModel() GPUModel {
	if x != nil {
		return x.Model
	}
	return GPUModel_GPU_MODEL_UNSPECIFIED
}

func (x *GPUInfo) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *GPUInfo) GetPciAddress() string {
	if x != nil {
		return x.PciAddress
	}
	return ""
}

func (x *GPUInfo) GetDriverVersion() string {
	if x != nil {
		return x.DriverVersion
	}
	return ""
}

func (x *GPUInfo) GetCudaVersion() string {
	if x != nil {
		return x.CudaVersion
	}
	return ""
}

func (x *GPUInfo) GetVramBytes() int64 {
	if x != nil {
		return x.VramBytes
	}
	return 0
}

// GetSystemInfoRequest is the request to get system information
type GetSystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemInfoRequest) Reset() {
	*x = GetSystemInfoRequest{}
	mi := &file_containarium_v1_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoRequest) ProtoMessage() {}

func (x *GetSystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{11}
}

// GetSystemInfoResponse is the response from getting system information
type GetSystemInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// System information (local/primary backend)
	Info *SystemInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	// System information from peer backends (tunnel-connected)
	Peers         []*SystemInfo `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemInfoResponse) Reset() {
	*x = GetSystemInfoResponse{}
	mi := &file_containarium_v1_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoResponse) ProtoMessage() {}

func (x *GetSystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{12}
}

func (x *GetSystemInfoResponse) GetInfo() *SystemInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *GetSystemInfoResponse) GetPeers() []*SystemInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

// GetLatestReleaseRequest is the request for the latest-release check.
type GetLatestReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestReleaseRequest) Reset() {
	*x = GetLatestReleaseRequest{}
	mi := &file_containarium_v1_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestReleaseRequest) ProtoMessage() {}

func (x *GetLatestReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestReleaseRequest.ProtoReflect.Descriptor instead.
func (*GetLatestReleaseRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{13}
}

// GetLatestReleaseResponse reports the latest published release vs the
// running daemon version. See #354.
type GetLatestReleaseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Latest release tag from GitHub (e.g. "v0.21.2"). Empty when the lookup
	// hasn't succeeded yet (e.g. rate-limited with no cached value).
	LatestRelease string `protobuf:"bytes,1,opt,name=latest_release,json=latestRelease,proto3" json:"latest_release,omitempty"`
	// This daemon's running version (e.g. "0.21.0").
	CurrentVersion string `protobuf:"bytes,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	// True when latest_release is a newer semver than current_version.
	UpdateAvailable bool `protobuf:"varint,3,opt,name=update_available,json=updateAvailable,proto3" json:"update_available,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetLatestReleaseResponse) Reset() {
	*x = GetLatestReleaseResponse{}
	mi := &file_containarium_v1_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestReleaseResponse) ProtoMessage() {}

func (x *GetLatestReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestReleaseResponse.ProtoReflect.Descriptor instead.
func (*GetLatestReleaseResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{14}
}

func (x *GetLatestReleaseResponse) GetLatestRelease() string {
	if x != nil {
		return x.LatestRelease
	}
	return ""
}

func (x *GetLatestReleaseResponse) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

func (x *GetLatestReleaseResponse) GetUpdateAvailable() bool {
	if x != nil {
		return x.UpdateAvailable
	}
	return false
}

// ValidateGPURequest asks a backend to prove GPU passthrough works from inside
// an LXC. See #316.
type ValidateGPURequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Backend to validate. Empty = the local/primary daemon's own host.
	BackendId string `protobuf:"bytes,1,opt,name=backend_id,json=backendId,proto3" json:"backend_id,omitempty"`
	// Specific GPU PCI address (e.g. "0000:01:00.0"). Empty = pass through all
	// GPUs. Prefer PCI over a DRM index — it's stable across kernel upgrades.
	Pci           string `protobuf:"bytes,2,opt,name=pci,proto3" json:"pci,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateGPURequest) Reset() {
	*x = ValidateGPURequest{}
	mi := &file_containarium_v1_config_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateGPURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateGPURequest) ProtoMessage() {}

func (x *ValidateGPURequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateGPURequest.ProtoReflect.Descriptor instead.
func (*ValidateGPURequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{15}
}

func (x *ValidateGPURequest) GetBackendId() string {
	if x != nil {
		return x.BackendId
	}
	return ""
}

func (x *ValidateGPURequest) GetPci() string {
	if x != nil {
		return x.Pci
	}
	return ""
}

// ValidateGPUResponse reports whether the GPU is usable from inside an LXC on
// the backend: the daemon launches a throwaway nvidia.runtime LXC, runs
// nvidia-smi inside, tears it down, and returns the parsed model + driver.
type ValidateGPUResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Status        ValidateGPUResponse_GPUStatus `protobuf:"varint,1,opt,name=status,proto3,enum=containarium.v1.ValidateGPUResponse_GPUStatus" json:"status,omitempty"`
	GpuModel      string                        `protobuf:"bytes,2,opt,name=gpu_model,json=gpuModel,proto3" json:"gpu_model,omitempty"`                // e.g. "NVIDIA GeForce RTX 3090"
	DriverVersion string                        `protobuf:"bytes,3,opt,name=driver_version,json=driverVersion,proto3" json:"driver_version,omitempty"` // e.g. "570.211.01"
	Detail        string                        `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`                                    // populated when status != OK
	BackendId     string                        `protobuf:"bytes,5,opt,name=backend_id,json=backendId,proto3" json:"backend_id,omitempty"`             // echoes the validated backend ("" = local)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateGPUResponse) Reset() {
	*x = ValidateGPUResponse{}
	mi := &file_containarium_v1_config_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateGPUResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateGPUResponse) ProtoMessage() {}

func (x *ValidateGPUResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateGPUResponse.ProtoReflect.Descriptor instead.
func (*ValidateGPUResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{16}
}

func (x *ValidateGPUResponse) GetStatus() ValidateGPUResponse_GPUStatus {
	if x != nil {
		return x.Status
	}
	return ValidateGPUResponse_GPU_STATUS_UNSPECIFIED
}

func (x *ValidateGPUResponse) GetGpuModel() string {
	if x != nil {
		return x.GpuModel
	}
	return ""
}

func (x *ValidateGPUResponse) GetDriverVersion() string {
	if x != nil {
		return x.DriverVersion
	}
	return ""
}

func (x *ValidateGPUResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ValidateGPUResponse) GetBackendId() string {
	if x != nil {
		return x.BackendId
	}
	return ""
}

// NetworkPolicy is a tenant's network-isolation policy, enforced at each of the
// tenant's container host-veth TC_INGRESS hooks (the sender side of every flow;
// see the Phase 0 findings in NETWORK-ISOLATION-DESIGN.md). #315.
type NetworkPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant this policy applies to (required).
	Tenant string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	// Allow container↔container traffic within the same tenant. When false, even
	// same-tenant peers can't reach each other.
	AllowIntraTenant bool `protobuf:"varint,2,opt,name=allow_intra_tenant,json=allowIntraTenant,proto3" json:"allow_intra_tenant,omitempty"`
	// Allowed egress destination CIDRs (e.g. "10.0.0.0/8", "1.2.3.4/32").
	EgressCidrs []string `protobuf:"bytes,3,rep,name=egress_cidrs,json=egressCidrs,proto3" json:"egress_cidrs,omitempty"`
	// Allowed egress domains (e.g. "api.github.com"); the daemon resolves these
	// to CIDRs on a refresh loop and folds them into the egress allow set.
	EgressDomains []string `protobuf:"bytes,4,rep,name=egress_domains,json=egressDomains,proto3" json:"egress_domains,omitempty"`
	// Enforcement mode. Unspecified is treated as LOG_ONLY in Phase A.
	Mode          NetworkPolicyMode `protobuf:"varint,5,opt,name=mode,proto3,enum=containarium.v1.NetworkPolicyMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicy) Reset() {
	*x = NetworkPolicy{}
	mi := &file_containarium_v1_config_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicy) ProtoMessage() {}

func (x *NetworkPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicy.ProtoReflect.Descriptor instead.
func (*NetworkPolicy) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{17}
}

func (x *NetworkPolicy) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *NetworkPolicy) GetAllowIntraTenant() bool {
	if x != nil {
		return x.AllowIntraTenant
	}
	return false
}

func (x *NetworkPolicy) GetEgressCidrs() []string {
	if x != nil {
		return x.EgressCidrs
	}
	return nil
}

func (x *NetworkPolicy) GetEgressDomains() []string {
	if x != nil {
		return x.EgressDomains
	}
	return nil
}

func (x *NetworkPolicy) GetMode() NetworkPolicyMode {
	if x != nil {
		return x.Mode
	}
	return NetworkPolicyMode_NETWORK_POLICY_MODE_UNSPECIFIED
}

type SetNetworkPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *NetworkPolicy         `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNetworkPolicyRequest) Reset() {
	*x = SetNetworkPolicyRequest{}
	mi := &file_containarium_v1_config_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNetworkPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNetworkPolicyRequest) ProtoMessage() {}

func (x *SetNetworkPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNetworkPolicyRequest.ProtoReflect.Descriptor instead.
func (*SetNetworkPolicyRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{18}
}

func (x *SetNetworkPolicyRequest) GetPolicy() *NetworkPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type SetNetworkPolicyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The stored policy (echoed back in its normalized form).
	Policy        *NetworkPolicy `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNetworkPolicyResponse) Reset() {
	*x = SetNetworkPolicyResponse{}
	mi := &file_containarium_v1_config_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNetworkPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNetworkPolicyResponse) ProtoMessage() {}

func (x *SetNetworkPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNetworkPolicyResponse.ProtoReflect.Descriptor instead.
func (*SetNetworkPolicyResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{19}
}

func (x *SetNetworkPolicyResponse) GetPolicy() *NetworkPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type GetNetworkPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkPolicyRequest) Reset() {
	*x = GetNetworkPolicyRequest{}
	mi := &file_containarium_v1_config_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkPolicyRequest) ProtoMessage() {}

func (x *GetNetworkPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetNetworkPolicyRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{20}
}

func (x *GetNetworkPolicyRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

type GetNetworkPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *NetworkPolicy         `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkPolicyResponse) Reset() {
	*x = GetNetworkPolicyResponse{}
	mi := &file_containarium_v1_config_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkPolicyResponse) ProtoMessage() {}

func (x *GetNetworkPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetNetworkPolicyResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{21}
}

func (x *GetNetworkPolicyResponse) GetPolicy() *NetworkPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type ListNetworkPoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworkPoliciesRequest) Reset() {
	*x = ListNetworkPoliciesRequest{}
	mi := &file_containarium_v1_config_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworkPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworkPoliciesRequest) ProtoMessage() {}

func (x *ListNetworkPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworkPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ListNetworkPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{22}
}

type ListNetworkPoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*NetworkPolicy       `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworkPoliciesResponse) Reset() {
	*x = ListNetworkPoliciesResponse{}
	mi := &file_containarium_v1_config_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworkPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworkPoliciesResponse) ProtoMessage() {}

func (x *ListNetworkPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworkPoliciesResponse.ProtoReflect.Descriptor instead.
func (*ListNetworkPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{23}
}

func (x *ListNetworkPoliciesResponse) GetPolicies() []*NetworkPolicy {
	if x != nil {
		return x.Policies
	}
	return nil
}

type DeleteNetworkPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNetworkPolicyRequest) Reset() {
	*x = DeleteNetworkPolicyRequest{}
	mi := &file_containarium_v1_config_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNetworkPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNetworkPolicyRequest) ProtoMessage() {}

func (x *DeleteNetworkPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNetworkPolicyRequest.ProtoReflect.Descriptor instead.
func (*DeleteNetworkPolicyRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteNetworkPolicyRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

type DeleteNetworkPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNetworkPolicyResponse) Reset() {
	*x = DeleteNetworkPolicyResponse{}
	mi := &file_containarium_v1_config_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNetworkPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNetworkPolicyResponse) ProtoMessage() {}

func (x *DeleteNetworkPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNetworkPolicyResponse.ProtoReflect.Descriptor instead.
func (*DeleteNetworkPolicyResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{25}
}

// BackendInfo contains information about a backend instance
type BackendInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique backend identifier (e.g., "gcp-spot", "tunnel-node-a-gpu")
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Backend type
	Type BackendType `protobuf:"varint,2,opt,name=type,proto3,enum=containarium.v1.BackendType" json:"type,omitempty"`
	// Whether the backend is currently healthy
	Healthy bool `protobuf:"varint,3,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Priority (lower = preferred, GCP=0, tunnel=10)
	Priority      int32 `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendInfo) Reset() {
	*x = BackendInfo{}
	mi := &file_containarium_v1_config_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendInfo) ProtoMessage() {}

func (x *BackendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendInfo.ProtoReflect.Descriptor instead.
func (*BackendInfo) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{26}
}

func (x *BackendInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BackendInfo) GetType() BackendType {
	if x != nil {
		return x.Type
	}
	return BackendType_BACKEND_TYPE_UNSPECIFIED
}

func (x *BackendInfo) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *BackendInfo) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// ListBackendsRequest is the request to list available backends
type ListBackendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackendsRequest) Reset() {
	*x = ListBackendsRequest{}
	mi := &file_containarium_v1_config_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackendsRequest) ProtoMessage() {}

func (x *ListBackendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackendsRequest.ProtoReflect.Descriptor instead.
func (*ListBackendsRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{27}
}

// ListBackendsResponse is the response from listing backends
type ListBackendsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of available backends
	Backends      []*BackendInfo `protobuf:"bytes,1,rep,name=backends,proto3" json:"backends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackendsResponse) Reset() {
	*x = ListBackendsResponse{}
	mi := &file_containarium_v1_config_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackendsResponse) ProtoMessage() {}

func (x *ListBackendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_config_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackendsResponse.ProtoReflect.Descriptor instead.
func (*ListBackendsResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_config_proto_rawDescGZIP(), []int{28}
}

func (x *ListBackendsResponse) GetBackends() []*BackendInfo {
	if x != nil {
		return x.Backends
	}
	return nil
}

var File_containarium_v1_config_proto protoreflect.FileDescriptor

const file_containarium_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x1ccontainarium/v1/config.proto\x12\x0fcontainarium.v1\x1a\x1fcontainarium/v1/container.proto\"\xd7\x03\n" +
	"\x06Config\x122\n" +
	"\x05incus\x18\x01 \x01(\v2\x1c.containarium.v1.IncusConfigR\x05incus\x12L\n" +
	"\x11default_resources\x18\x02 \x01(\v2\x1f.containarium.v1.ResourceLimitsR\x10defaultResources\x12#\n" +
	"\rdefault_image\x18\x03 \x01(\tR\fdefaultImage\x124\n" +
	"\x16default_docker_enabled\x18\x04 \x01(\bR\x14defaultDockerEnabled\x128\n" +
	"\anetwork\x18\x05 \x01(\v2\x1e.containarium.v1.NetworkConfigR\anetwork\x128\n" +
	"\astorage\x18\x06 \x01(\v2\x1e.containarium.v1.StorageConfigR\astorage\x12;\n" +
	"\bsecurity\x18\a \x01(\v2\x1f.containarium.v1.SecurityConfigR\bsecurity\x12?\n" +
	"\x0fdefault_os_type\x18\b \x01(\x0e2\x17.containarium.v1.OSTypeR\rdefaultOsType\"\x89\x01\n" +
	"\vIncusConfig\x12\x1f\n" +
	"\vsocket_path\x18\x01 \x01(\tR\n" +
	"socketPath\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x16\n" +
	"\x06remote\x18\x03 \x01(\tR\x06remote\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\"\xda\x01\n" +
	"\rNetworkConfig\x12\x1f\n" +
	"\vbridge_name\x18\x01 \x01(\tR\n" +
	"bridgeName\x12\x16\n" +
	"\x06subnet\x18\x02 \x01(\tR\x06subnet\x12(\n" +
	"\x10dhcp_range_start\x18\x03 \x01(\tR\x0edhcpRangeStart\x12$\n" +
	"\x0edhcp_range_end\x18\x04 \x01(\tR\fdhcpRangeEnd\x12\x1f\n" +
	"\vdns_servers\x18\x05 \x03(\tR\n" +
	"dnsServers\x12\x1f\n" +
	"\venable_ipv6\x18\x06 \x01(\bR\n" +
	"enableIpv6\"\x8f\x01\n" +
	"\rStorageConfig\x12\x1b\n" +
	"\tpool_name\x18\x01 \x01(\tR\bpoolName\x12\x16\n" +
	"\x06driver\x18\x02 \x01(\tR\x06driver\x12\x1b\n" +
	"\tpool_path\x18\x03 \x01(\tR\bpoolPath\x12,\n" +
	"\x12default_disk_quota\x18\x04 \x01(\tR\x10defaultDiskQuota\"\x9e\x02\n" +
	"\x0eSecurityConfig\x127\n" +
	"\x17unprivileged_containers\x18\x01 \x01(\bR\x16unprivilegedContainers\x12)\n" +
	"\x10apparmor_profile\x18\x02 \x01(\tR\x0fapparmorProfile\x12'\n" +
	"\x0fselinux_context\x18\x03 \x01(\tR\x0eselinuxContext\x12%\n" +
	"\x0eenable_seccomp\x18\x04 \x01(\bR\renableSeccomp\x12(\n" +
	"\x10require_ssh_keys\x18\x05 \x01(\bR\x0erequireSshKeys\x12.\n" +
	"\x13min_password_length\x18\x06 \x01(\x05R\x11minPasswordLength\"\x12\n" +
	"\x10GetConfigRequest\"D\n" +
	"\x11GetConfigResponse\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x17.containarium.v1.ConfigR\x06config\"g\n" +
	"\x13UpdateConfigRequest\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x17.containarium.v1.ConfigR\x06config\x12\x1f\n" +
	"\vupdate_mask\x18\x02 \x03(\tR\n" +
	"updateMask\"a\n" +
	"\x14UpdateConfigResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x17.containarium.v1.ConfigR\x06config\"\xd0\x06\n" +
	"\n" +
	"SystemInfo\x12#\n" +
	"\rincus_version\x18\x01 \x01(\tR\fincusVersion\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12%\n" +
	"\x0ekernel_version\x18\x03 \x01(\tR\rkernelVersion\x12\x1d\n" +
	"\n" +
	"total_cpus\x18\x04 \x01(\x05R\ttotalCpus\x12,\n" +
	"\x12total_memory_bytes\x18\x05 \x01(\x03R\x10totalMemoryBytes\x124\n" +
	"\x16available_memory_bytes\x18\x06 \x01(\x03R\x14availableMemoryBytes\x12(\n" +
	"\x10total_disk_bytes\x18\a \x01(\x03R\x0etotalDiskBytes\x120\n" +
	"\x14available_disk_bytes\x18\b \x01(\x03R\x12availableDiskBytes\x12-\n" +
	"\x12containers_running\x18\t \x01(\x05R\x11containersRunning\x12-\n" +
	"\x12containers_stopped\x18\n" +
	" \x01(\x05R\x11containersStopped\x12)\n" +
	"\x10containers_total\x18\v \x01(\x05R\x0fcontainersTotal\x12\x1a\n" +
	"\bhostname\x18\f \x01(\tR\bhostname\x12%\n" +
	"\x0euptime_seconds\x18\r \x01(\x03R\ruptimeSeconds\x12!\n" +
	"\fnetwork_cidr\x18\x0e \x01(\tR\vnetworkCidr\x12\"\n" +
	"\rcpu_load_1min\x18\x0f \x01(\x01R\vcpuLoad1min\x12\"\n" +
	"\rcpu_load_5min\x18\x10 \x01(\x01R\vcpuLoad5min\x12$\n" +
	"\x0ecpu_load_15min\x18\x11 \x01(\x01R\fcpuLoad15min\x12,\n" +
	"\x04gpus\x18\x12 \x03(\v2\x18.containarium.v1.GPUInfoR\x04gpus\x12\x1d\n" +
	"\n" +
	"backend_id\x18\x13 \x01(\tR\tbackendId\x126\n" +
	"\x17otel_collector_endpoint\x18\x14 \x01(\tR\x15otelCollectorEndpoint\x12%\n" +
	"\x0edaemon_version\x18\x15 \x01(\tR\rdaemonVersion\"\x97\x02\n" +
	"\aGPUInfo\x122\n" +
	"\x06vendor\x18\x01 \x01(\x0e2\x1a.containarium.v1.GPUVendorR\x06vendor\x12/\n" +
	"\x05model\x18\x02 \x01(\x0e2\x19.containarium.v1.GPUModelR\x05model\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x12\x1f\n" +
	"\vpci_address\x18\x04 \x01(\tR\n" +
	"pciAddress\x12%\n" +
	"\x0edriver_version\x18\x05 \x01(\tR\rdriverVersion\x12!\n" +
	"\fcuda_version\x18\x06 \x01(\tR\vcudaVersion\x12\x1d\n" +
	"\n" +
	"vram_bytes\x18\a \x01(\x03R\tvramBytes\"\x16\n" +
	"\x14GetSystemInfoRequest\"{\n" +
	"\x15GetSystemInfoResponse\x12/\n" +
	"\x04info\x18\x01 \x01(\v2\x1b.containarium.v1.SystemInfoR\x04info\x121\n" +
	"\x05peers\x18\x02 \x03(\v2\x1b.containarium.v1.SystemInfoR\x05peers\"\x19\n" +
	"\x17GetLatestReleaseRequest\"\x95\x01\n" +
	"\x18GetLatestReleaseResponse\x12%\n" +
	"\x0elatest_release\x18\x01 \x01(\tR\rlatestRelease\x12'\n" +
	"\x0fcurrent_version\x18\x02 \x01(\tR\x0ecurrentVersion\x12)\n" +
	"\x10update_available\x18\x03 \x01(\bR\x0fupdateAvailable\"E\n" +
	"\x12ValidateGPURequest\x12\x1d\n" +
	"\n" +
	"backend_id\x18\x01 \x01(\tR\tbackendId\x12\x10\n" +
	"\x03pci\x18\x02 \x01(\tR\x03pci\"\xc9\x02\n" +
	"\x13ValidateGPUResponse\x12F\n" +
	"\x06status\x18\x01 \x01(\x0e2..containarium.v1.ValidateGPUResponse.GPUStatusR\x06status\x12\x1b\n" +
	"\tgpu_model\x18\x02 \x01(\tR\bgpuModel\x12%\n" +
	"\x0edriver_version\x18\x03 \x01(\tR\rdriverVersion\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x1d\n" +
	"\n" +
	"backend_id\x18\x05 \x01(\tR\tbackendId\"o\n" +
	"\tGPUStatus\x12\x1a\n" +
	"\x16GPU_STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rGPU_STATUS_OK\x10\x01\x12\x1a\n" +
	"\x16GPU_STATUS_UNAVAILABLE\x10\x02\x12\x17\n" +
	"\x13GPU_STATUS_DEGRADED\x10\x03\"\xd7\x01\n" +
	"\rNetworkPolicy\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12,\n" +
	"\x12allow_intra_tenant\x18\x02 \x01(\bR\x10allowIntraTenant\x12!\n" +
	"\fegress_cidrs\x18\x03 \x03(\tR\vegressCidrs\x12%\n" +
	"\x0eegress_domains\x18\x04 \x03(\tR\regressDomains\x126\n" +
	"\x04mode\x18\x05 \x01(\x0e2\".containarium.v1.NetworkPolicyModeR\x04mode\"Q\n" +
	"\x17SetNetworkPolicyRequest\x126\n" +
	"\x06policy\x18\x01 \x01(\v2\x1e.containarium.v1.NetworkPolicyR\x06policy\"R\n" +
	"\x18SetNetworkPolicyResponse\x126\n" +
	"\x06policy\x18\x01 \x01(\v2\x1e.containarium.v1.NetworkPolicyR\x06policy\"1\n" +
	"\x17GetNetworkPolicyRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\"R\n" +
	"\x18GetNetworkPolicyResponse\x126\n" +
	"\x06policy\x18\x01 \x01(\v2\x1e.containarium.v1.NetworkPolicyR\x06policy\"\x1c\n" +
	"\x1aListNetworkPoliciesRequest\"Y\n" +
	"\x1bListNetworkPoliciesResponse\x12:\n" +
	"\bpolicies\x18\x01 \x03(\v2\x1e.containarium.v1.NetworkPolicyR\bpolicies\"4\n" +
	"\x1aDeleteNetworkPolicyRequest\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\"\x1d\n" +
	"\x1bDeleteNetworkPolicyResponse\"\x85\x01\n" +
	"\vBackendInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.containarium.v1.BackendTypeR\x04type\x12\x18\n" +
	"\ahealthy\x18\x03 \x01(\bR\ahealthy\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\"\x15\n" +
	"\x13ListBackendsRequest\"P\n" +
	"\x14ListBackendsResponse\x128\n" +
	"\bbackends\x18\x01 \x03(\v2\x1c.containarium.v1.BackendInfoR\bbackends*h\n" +
	"\tGPUVendor\x12\x1a\n" +
	"\x16GPU_VENDOR_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11GPU_VENDOR_NVIDIA\x10\x01\x12\x12\n" +
	"\x0eGPU_VENDOR_AMD\x10\x02\x12\x14\n" +
	"\x10GPU_VENDOR_INTEL\x10\x03*\xe2\x05\n" +
	"\bGPUModel\x12\x19\n" +
	"\x15GPU_MODEL_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19GPU_MODEL_NVIDIA_RTX_4090\x10d\x12\x1d\n" +
	"\x19GPU_MODEL_NVIDIA_RTX_4080\x10e\x12 \n" +
	"\x1cGPU_MODEL_NVIDIA_RTX_4070_TI\x10f\x12\x1d\n" +
	"\x19GPU_MODEL_NVIDIA_RTX_4070\x10g\x12\x1d\n" +
	"\x19GPU_MODEL_NVIDIA_RTX_3090\x10h\x12\x1d\n" +
	"\x19GPU_MODEL_NVIDIA_RTX_3080\x10i\x12\x1d\n" +
	"\x19GPU_MODEL_NVIDIA_RTX_5090\x10j\x12\x1d\n" +
	"\x19GPU_MODEL_NVIDIA_RTX_5080\x10k\x12\x1a\n" +
	"\x15GPU_MODEL_NVIDIA_A100\x10\xc8\x01\x12\x19\n" +
	"\x14GPU_MODEL_NVIDIA_A10\x10\xc9\x01\x12\x1a\n" +
	"\x15GPU_MODEL_NVIDIA_A10G\x10\xca\x01\x12\x1a\n" +
	"\x15GPU_MODEL_NVIDIA_H100\x10\xcb\x01\x12\x1a\n" +
	"\x15GPU_MODEL_NVIDIA_H200\x10\xcc\x01\x12\x18\n" +
	"\x13GPU_MODEL_NVIDIA_L4\x10\xcd\x01\x12\x19\n" +
	"\x14GPU_MODEL_NVIDIA_L40\x10\xce\x01\x12\x1a\n" +
	"\x15GPU_MODEL_NVIDIA_L40S\x10\xcf\x01\x12\x18\n" +
	"\x13GPU_MODEL_NVIDIA_T4\x10\xd0\x01\x12\x1a\n" +
	"\x15GPU_MODEL_NVIDIA_V100\x10\xd1\x01\x12\x1a\n" +
	"\x15GPU_MODEL_NVIDIA_B200\x10\xd2\x01\x12\x19\n" +
	"\x14GPU_MODEL_AMD_MI300X\x10\xac\x02\x12\x19\n" +
	"\x14GPU_MODEL_AMD_MI250X\x10\xad\x02\x12\x1e\n" +
	"\x19GPU_MODEL_AMD_RX_7900_XTX\x10\xae\x02\x12\x1d\n" +
	"\x18GPU_MODEL_INTEL_MAX_1550\x10\x90\x03\x12\x1d\n" +
	"\x18GPU_MODEL_INTEL_ARC_A770\x10\x91\x03*{\n" +
	"\x11NetworkPolicyMode\x12#\n" +
	"\x1fNETWORK_POLICY_MODE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cNETWORK_POLICY_MODE_LOG_ONLY\x10\x01\x12\x1f\n" +
	"\x1bNETWORK_POLICY_MODE_ENFORCE\x10\x02*Z\n" +
	"\vBackendType\x12\x1c\n" +
	"\x18BACKEND_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10BACKEND_TYPE_GCP\x10\x01\x12\x17\n" +
	"\x13BACKEND_TYPE_TUNNEL\x10\x02BKZIgithub.com/footprintai/containarium/pkg/pb/containarium/v1;containariumv1b\x06proto3"

var (
	file_containarium_v1_config_proto_rawDescOnce sync.Once
	file_containarium_v1_config_proto_rawDescData []byte
)

func file_containarium_v1_config_proto_rawDescGZIP() []byte {
	file_containarium_v1_config_proto_rawDescOnce.Do(func() {
		file_containarium_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_containarium_v1_config_proto_rawDesc), len(file_containarium_v1_config_proto_rawDesc)))
	})
	return file_containarium_v1_config_proto_rawDescData
}

var file_containarium_v1_config_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_containarium_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_containarium_v1_config_proto_goTypes = []any{
	(GPUVendor)(0),                      // 0: containarium.v1.GPUVendor
	(GPUModel)(0),                       // 1: containarium.v1.GPUModel
	(NetworkPolicyMode)(0),              // 2: containarium.v1.NetworkPolicyMode
	(BackendType)(0),                    // 3: containarium.v1.BackendType
	(ValidateGPUResponse_GPUStatus)(0),  // 4: containarium.v1.ValidateGPUResponse.GPUStatus
	(*Config)(nil),                      // 5: containarium.v1.Config
	(*IncusConfig)(nil),                 // 6: containarium.v1.IncusConfig
	(*NetworkConfig)(nil),               // 7: containarium.v1.NetworkConfig
	(*StorageConfig)(nil),               // 8: containarium.v1.StorageConfig
	(*SecurityConfig)(nil),              // 9: containarium.v1.SecurityConfig
	(*GetConfigRequest)(nil),            // 10: containarium.v1.GetConfigRequest
	(*GetConfigResponse)(nil),           // 11: containarium.v1.GetConfigResponse
	(*UpdateConfigRequest)(nil),         // 12: containarium.v1.UpdateConfigRequest
	(*UpdateConfigResponse)(nil),        // 13: containarium.v1.UpdateConfigResponse
	(*SystemInfo)(nil),                  // 14: containarium.v1.SystemInfo
	(*GPUInfo)(nil),                     // 15: containarium.v1.GPUInfo
	(*GetSystemInfoRequest)(nil),        // 16: containarium.v1.GetSystemInfoRequest
	(*GetSystemInfoResponse)(nil),       // 17: containarium.v1.GetSystemInfoResponse
	(*GetLatestReleaseRequest)(nil),     // 18: containarium.v1.GetLatestReleaseRequest
	(*GetLatestReleaseResponse)(nil),    // 19: containarium.v1.GetLatestReleaseResponse
	(*ValidateGPURequest)(nil),          // 20: containarium.v1.ValidateGPURequest
	(*ValidateGPUResponse)(nil),         // 21: containarium.v1.ValidateGPUResponse
	(*NetworkPolicy)(nil),               // 22: containarium.v1.NetworkPolicy
	(*SetNetworkPolicyRequest)(nil),     // 23: containarium.v1.SetNetworkPolicyRequest
	(*SetNetworkPolicyResponse)(nil),    // 24: containarium.v1.SetNetworkPolicyResponse
	(*GetNetworkPolicyRequest)(nil),     // 25: containarium.v1.GetNetworkPolicyRequest
	(*GetNetworkPolicyResponse)(nil),    // 26: containarium.v1.GetNetworkPolicyResponse
	(*ListNetworkPoliciesRequest)(nil),  // 27: containarium.v1.ListNetworkPoliciesRequest
	(*ListNetworkPoliciesResponse)(nil), // 28: containarium.v1.ListNetworkPoliciesResponse
	(*DeleteNetworkPolicyRequest)(nil),  // 29: containarium.v1.DeleteNetworkPolicyRequest
	(*DeleteNetworkPolicyResponse)(nil), // 30: containarium.v1.DeleteNetworkPolicyResponse
	(*BackendInfo)(nil),                 // 31: containarium.v1.BackendInfo
	(*ListBackendsRequest)(nil),         // 32: containarium.v1.ListBackendsRequest
	(*ListBackendsResponse)(nil),        // 33: containarium.v1.ListBackendsResponse
	(*ResourceLimits)(nil),              // 34: containarium.v1.ResourceLimits
	(OSType)(0),                         // 35: containarium.v1.OSType
}
var file_containarium_v1_config_proto_depIdxs = []int32{
	6,  // 0: containarium.v1.Config.incus:type_name -> containarium.v1.IncusConfig
	34, // 1: containarium.v1.Config.default_resources:type_name -> containarium.v1.ResourceLimits
	7,  // 2: containarium.v1.Config.network:type_name -> containarium.v1.NetworkConfig
	8,  // 3: containarium.v1.Config.storage:type_name -> containarium.v1.StorageConfig
	9,  // 4: containarium.v1.Config.security:type_name -> containarium.v1.SecurityConfig
	35, // 5: containarium.v1.Config.default_os_type:type_name -> containarium.v1.OSType
	5,  // 6: containarium.v1.GetConfigResponse.config:type_name -> containarium.v1.Config
	5,  // 7: containarium.v1.UpdateConfigRequest.config:type_name -> containarium.v1.Config
	5,  // 8: containarium.v1.UpdateConfigResponse.config:type_name -> containarium.v1.Config
	15, // 9: containarium.v1.SystemInfo.gpus:type_name -> containarium.v1.GPUInfo
	0,  // 10: containarium.v1.GPUInfo.vendor:type_name -> containarium.v1.GPUVendor
	1,  // 11: containarium.v1.GPUInfo.model:type_name -> containarium.v1.GPUModel
	14, // 12: containarium.v1.GetSystemInfoResponse.info:type_name -> containarium.v1.SystemInfo
	14, // 13: containarium.v1.GetSystemInfoResponse.peers:type_name -> containarium.v1.SystemInfo
	4,  // 14: containarium.v1.ValidateGPUResponse.status:type_name -> containarium.v1.ValidateGPUResponse.GPUStatus
	2,  // 15: containarium.v1.NetworkPolicy.mode:type_name -> containarium.v1.NetworkPolicyMode
	22, // 16: containarium.v1.SetNetworkPolicyRequest.policy:type_name -> containarium.v1.NetworkPolicy
	22, // 17: containarium.v1.SetNetworkPolicyResponse.policy:type_name -> containarium.v1.NetworkPolicy
	22, // 18: containarium.v1.GetNetworkPolicyResponse.policy:type_name -> containarium.v1.NetworkPolicy
	22, // 19: containarium.v1.ListNetworkPoliciesResponse.policies:type_name -> containarium.v1.NetworkPolicy
	3,  // 20: containarium.v1.BackendInfo.type:type_name -> containarium.v1.BackendType
	31, // 21: containarium.v1.ListBackendsResponse.backends:type_name -> containarium.v1.BackendInfo
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_containarium_v1_config_proto_init() }
func file_containarium_v1_config_proto_init() {
	if File_containarium_v1_config_proto != nil {
		return
	}
	file_containarium_v1_container_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_containarium_v1_config_proto_rawDesc), len(file_containarium_v1_config_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_containarium_v1_config_proto_goTypes,
		DependencyIndexes: file_containarium_v1_config_proto_depIdxs,
		EnumInfos:         file_containarium_v1_config_proto_enumTypes,
		MessageInfos:      file_containarium_v1_config_proto_msgTypes,
	}.Build()
	File_containarium_v1_config_proto = out.File
	file_containarium_v1_config_proto_goTypes = nil
	file_containarium_v1_config_proto_depIdxs = nil
}
