// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: containarium/v1/network_policy.proto

package containariumv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_containarium_v1_network_policy_proto protoreflect.FileDescriptor

const file_containarium_v1_network_policy_proto_rawDesc = "" +
	"\n" +
	"$containarium/v1/network_policy.proto\x12\x0fcontainarium.v1\x1a\x1ccontainarium/v1/config.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xd8\x11\n" +
	"\x14NetworkPolicyService\x12\x8d\x02\n" +
	"\x10SetNetworkPolicy\x12(.containarium.v1.SetNetworkPolicyRequest\x1a).containarium.v1.SetNetworkPolicyResponse\"\xa3\x01\x92A\x80\x01\n" +
	"\rNetworkPolicy\x12\x12Set network policy\x1a[Create or replace a tenant's network-isolation policy (validated + normalized). Admin-only.\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/network-policies\x12\xee\x01\n" +
	"\x10GetNetworkPolicy\x12(.containarium.v1.GetNetworkPolicyRequest\x1a).containarium.v1.GetNetworkPolicyResponse\"\x84\x01\x92A\\\n" +
	"\rNetworkPolicy\x12\x12Get network policy\x1a7Return a tenant's network-isolation policy. Admin-only.\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/network-policies/{tenant}\x12\xf3\x01\n" +
	"\x13ListNetworkPolicies\x12+.containarium.v1.ListNetworkPoliciesRequest\x1a,.containarium.v1.ListNetworkPoliciesResponse\"\x80\x01\x92Aa\n" +
	"\rNetworkPolicy\x12\x15List network policies\x1a9List every tenant's network-isolation policy. Admin-only.\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/network-policies\x12\x87\x02\n" +
	"\x13DeleteNetworkPolicy\x12+.containarium.v1.DeleteNetworkPolicyRequest\x1a,.containarium.v1.DeleteNetworkPolicyResponse\"\x94\x01\x92Al\n" +
	"\rNetworkPolicy\x12\x15Delete network policy\x1aDRemove a tenant's network-isolation policy (idempotent). Admin-only.\x82\xd3\xe4\x93\x02\x1f*\x1d/v1/network-policies/{tenant}\x12\xac\x02\n" +
	"\x1bPatchNetworkPolicyDenyRules\x123.containarium.v1.PatchNetworkPolicyDenyRulesRequest\x1a).containarium.v1.SetNetworkPolicyResponse\"\xac\x01\x92A\x7f\n" +
	"\rNetworkPolicy\x12\x1fPatch network-policy deny rules\x1aMAtomically add/remove a tenant's virtual-patch deny rules (#660). Admin-only.\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/network-policies/deny-rules\x12\xa9\x02\n" +
	"\x19SetNetworkPolicySignature\x121.containarium.v1.SetNetworkPolicySignatureRequest\x1a2.containarium.v1.SetNetworkPolicySignatureResponse\"\xa4\x01\x92Ay\n" +
	"\rNetworkPolicy\x12\x1cSet network-policy signature\x1aJCreate or replace a global cleartext exploit signature (#661). Admin-only.\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/network-policy-signatures\x12\xa5\x02\n" +
	"\x1bListNetworkPolicySignatures\x123.containarium.v1.ListNetworkPolicySignaturesRequest\x1a4.containarium.v1.ListNetworkPolicySignaturesResponse\"\x9a\x01\x92Ar\n" +
	"\rNetworkPolicy\x12\x1eList network-policy signatures\x1aAList every operator-managed exploit signature (#661). Admin-only.\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/network-policy-signatures\x12\xbb\x02\n" +
	"\x1cDeleteNetworkPolicySignature\x124.containarium.v1.DeleteNetworkPolicySignatureRequest\x1a5.containarium.v1.DeleteNetworkPolicySignatureResponse\"\xad\x01\x92A~\n" +
	"\rNetworkPolicy\x12\x1fDelete network-policy signature\x1aLRemove an operator-managed exploit signature (#661, idempotent). Admin-only.\x82\xd3\xe4\x93\x02&*$/v1/network-policy-signatures/{name}BKZIgithub.com/footprintai/containarium/pkg/pb/containarium/v1;containariumv1b\x06proto3"

var file_containarium_v1_network_policy_proto_goTypes = []any{
	(*SetNetworkPolicyRequest)(nil),              // 0: containarium.v1.SetNetworkPolicyRequest
	(*GetNetworkPolicyRequest)(nil),              // 1: containarium.v1.GetNetworkPolicyRequest
	(*ListNetworkPoliciesRequest)(nil),           // 2: containarium.v1.ListNetworkPoliciesRequest
	(*DeleteNetworkPolicyRequest)(nil),           // 3: containarium.v1.DeleteNetworkPolicyRequest
	(*PatchNetworkPolicyDenyRulesRequest)(nil),   // 4: containarium.v1.PatchNetworkPolicyDenyRulesRequest
	(*SetNetworkPolicySignatureRequest)(nil),     // 5: containarium.v1.SetNetworkPolicySignatureRequest
	(*ListNetworkPolicySignaturesRequest)(nil),   // 6: containarium.v1.ListNetworkPolicySignaturesRequest
	(*DeleteNetworkPolicySignatureRequest)(nil),  // 7: containarium.v1.DeleteNetworkPolicySignatureRequest
	(*SetNetworkPolicyResponse)(nil),             // 8: containarium.v1.SetNetworkPolicyResponse
	(*GetNetworkPolicyResponse)(nil),             // 9: containarium.v1.GetNetworkPolicyResponse
	(*ListNetworkPoliciesResponse)(nil),          // 10: containarium.v1.ListNetworkPoliciesResponse
	(*DeleteNetworkPolicyResponse)(nil),          // 11: containarium.v1.DeleteNetworkPolicyResponse
	(*SetNetworkPolicySignatureResponse)(nil),    // 12: containarium.v1.SetNetworkPolicySignatureResponse
	(*ListNetworkPolicySignaturesResponse)(nil),  // 13: containarium.v1.ListNetworkPolicySignaturesResponse
	(*DeleteNetworkPolicySignatureResponse)(nil), // 14: containarium.v1.DeleteNetworkPolicySignatureResponse
}
var file_containarium_v1_network_policy_proto_depIdxs = []int32{
	0,  // 0: containarium.v1.NetworkPolicyService.SetNetworkPolicy:input_type -> containarium.v1.SetNetworkPolicyRequest
	1,  // 1: containarium.v1.NetworkPolicyService.GetNetworkPolicy:input_type -> containarium.v1.GetNetworkPolicyRequest
	2,  // 2: containarium.v1.NetworkPolicyService.ListNetworkPolicies:input_type -> containarium.v1.ListNetworkPoliciesRequest
	3,  // 3: containarium.v1.NetworkPolicyService.DeleteNetworkPolicy:input_type -> containarium.v1.DeleteNetworkPolicyRequest
	4,  // 4: containarium.v1.NetworkPolicyService.PatchNetworkPolicyDenyRules:input_type -> containarium.v1.PatchNetworkPolicyDenyRulesRequest
	5,  // 5: containarium.v1.NetworkPolicyService.SetNetworkPolicySignature:input_type -> containarium.v1.SetNetworkPolicySignatureRequest
	6,  // 6: containarium.v1.NetworkPolicyService.ListNetworkPolicySignatures:input_type -> containarium.v1.ListNetworkPolicySignaturesRequest
	7,  // 7: containarium.v1.NetworkPolicyService.DeleteNetworkPolicySignature:input_type -> containarium.v1.DeleteNetworkPolicySignatureRequest
	8,  // 8: containarium.v1.NetworkPolicyService.SetNetworkPolicy:output_type -> containarium.v1.SetNetworkPolicyResponse
	9,  // 9: containarium.v1.NetworkPolicyService.GetNetworkPolicy:output_type -> containarium.v1.GetNetworkPolicyResponse
	10, // 10: containarium.v1.NetworkPolicyService.ListNetworkPolicies:output_type -> containarium.v1.ListNetworkPoliciesResponse
	11, // 11: containarium.v1.NetworkPolicyService.DeleteNetworkPolicy:output_type -> containarium.v1.DeleteNetworkPolicyResponse
	8,  // 12: containarium.v1.NetworkPolicyService.PatchNetworkPolicyDenyRules:output_type -> containarium.v1.SetNetworkPolicyResponse
	12, // 13: containarium.v1.NetworkPolicyService.SetNetworkPolicySignature:output_type -> containarium.v1.SetNetworkPolicySignatureResponse
	13, // 14: containarium.v1.NetworkPolicyService.ListNetworkPolicySignatures:output_type -> containarium.v1.ListNetworkPolicySignaturesResponse
	14, // 15: containarium.v1.NetworkPolicyService.DeleteNetworkPolicySignature:output_type -> containarium.v1.DeleteNetworkPolicySignatureResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_containarium_v1_network_policy_proto_init() }
func file_containarium_v1_network_policy_proto_init() {
	if File_containarium_v1_network_policy_proto != nil {
		return
	}
	file_containarium_v1_config_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_containarium_v1_network_policy_proto_rawDesc), len(file_containarium_v1_network_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_containarium_v1_network_policy_proto_goTypes,
		DependencyIndexes: file_containarium_v1_network_policy_proto_depIdxs,
	}.Build()
	File_containarium_v1_network_policy_proto = out.File
	file_containarium_v1_network_policy_proto_goTypes = nil
	file_containarium_v1_network_policy_proto_depIdxs = nil
}
