// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: containarium/v1/service.proto

package containariumv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_containarium_v1_service_proto protoreflect.FileDescriptor

const file_containarium_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1dcontainarium/v1/service.proto\x12\x0fcontainarium.v1\x1a\x1fcontainarium/v1/container.proto\x1a\x1ccontainarium/v1/config.proto\x1a\x19containarium/v1/app.proto\x1a\x1dcontainarium/v1/network.proto\x1a\x1bcontainarium/v1/alert.proto\x1a\x1dcontainarium/v1/secrets.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xac\x92\x01\n" +
	"\x10ContainerService\x12\xae\x02\n" +
	"\x0fCreateContainer\x12'.containarium.v1.CreateContainerRequest\x1a(.containarium.v1.CreateContainerResponse\"\xc7\x01\x92A\xaa\x01\n" +
	"\n" +
	"Containers\x12\x16Create a new container\x1a\x83\x01Creates a new LXC container with specified resources and configuration. The container will be started automatically after creation.\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/containers\x12\x9c\x02\n" +
	"\x0eListContainers\x12&.containarium.v1.ListContainersRequest\x1a'.containarium.v1.ListContainersResponse\"\xb8\x01\x92A\x9e\x01\n" +
	"\n" +
	"Containers\x12\x13List all containers\x1a{Returns a list of containers with optional filtering by state, username, or labels. Use query parameters to filter results.\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/containers\x12\x9e\x02\n" +
	"\fGetContainer\x12$.containarium.v1.GetContainerRequest\x1a%.containarium.v1.GetContainerResponse\"\xc0\x01\x92A\x9b\x01\n" +
	"\n" +
	"Containers\x12\x15Get container details\x1avReturns detailed information about a specific container including state, resources, network info, and current metrics.\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/containers/{username}\x12\xd6\x03\n" +
	"\x0eDebugContainer\x12&.containarium.v1.DebugContainerRequest\x1a'.containarium.v1.DebugContainerResponse\"\xf2\x02\x92A\xc7\x02\n" +
	"\n" +
	"Containers\x12\x1cDebug a container's SSH path\x1a\x9a\x02Inspects backend-local state for the container: container runtime state, host /etc/passwd entry, whether the shell wrapper exists, and recent sshd journal lines matching the username. Returns a structured diagnosis with likely_cause and ordered next_actions for the caller to apply.\x82\xd3\xe4\x93\x02!\x12\x1f/v1/containers/{username}/debug\x12\x8a\x02\n" +
	"\x0fDeleteContainer\x12'.containarium.v1.DeleteContainerRequest\x1a(.containarium.v1.DeleteContainerResponse\"\xa3\x01\x92A\x7f\n" +
	"\n" +
	"Containers\x12\x12Delete a container\x1a]Permanently deletes a container. Use force=true query parameter to delete running containers.\x82\xd3\xe4\x93\x02\x1b*\x19/v1/containers/{username}\x12\x89\x02\n" +
	"\x0eStartContainer\x12&.containarium.v1.StartContainerRequest\x1a'.containarium.v1.StartContainerResponse\"\xa5\x01\x92Ax\n" +
	"\x14Container Operations\x12\x11Start a container\x1aMStarts a stopped container. The container must exist and be in STOPPED state.\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/containers/{username}/start\x12\xb2\x02\n" +
	"\rStopContainer\x12%.containarium.v1.StopContainerRequest\x1a&.containarium.v1.StopContainerResponse\"\xd1\x01\x92A\xa4\x01\n" +
	"\x14Container Operations\x12\x10Stop a container\x1azGracefully stops a running container with optional timeout and force parameters. The container can be started again later.\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/containers/{username}/stop\x12\xc3\x02\n" +
	"\x0fResizeContainer\x12'.containarium.v1.ResizeContainerRequest\x1a(.containarium.v1.ResizeContainerResponse\"\xdc\x01\x92A\xad\x01\n" +
	"\x14Container Operations\x12\x1aResize container resources\x1ayDynamically adjusts CPU, memory, and disk resources without container restart. Disk can only be increased, not decreased.\x82\xd3\xe4\x93\x02%:\x01*\x1a /v1/containers/{username}/resize\x12\xc8\x03\n" +
	"\rMoveContainer\x12%.containarium.v1.MoveContainerRequest\x1a&.containarium.v1.MoveContainerResponse\"\xe7\x02\x92A\xba\x02\n" +
	"\x14Container Operations\x12 Migrate container to peer daemon\x1a\xff\x01Pre-copy snapshot-based migration to a peer daemon. Sub-second downtime on ZFS/btrfs storage with low write rate; up to minutes on dir-pool or active workloads. Caller must have incus remotes configured both directions between the source and target hosts.\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/containers/{username}/move\x12\xdc\x03\n" +
	"\x16AdoptMigratedContainer\x12..containarium.v1.AdoptMigratedContainerRequest\x1a/.containarium.v1.AdoptMigratedContainerResponse\"\xe0\x02\x92A\xb2\x02\n" +
	"\x14Container Operations\x12%Adopt a migrated container (internal)\x1a\xf2\x01Called by the source daemon during MoveContainer after the LXC has been Incus-copied to this host. Registers the container's host-side accounts and route record so it's fully under Containarium's control. Not intended for direct operator use.\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/containers/{username}/adopt\x12\xd6\x03\n" +
	"\x10ToggleMonitoring\x12(.containarium.v1.ToggleMonitoringRequest\x1a).containarium.v1.ToggleMonitoringResponse\"\xec\x02\x92A\xb9\x02\n" +
	"\x14Container Operations\x120Enable or disable OTel monitoring on a container\x1a\xee\x01Live-flip OTEL_EXPORTER_OTLP_ENDPOINT and related env vars on an existing container and restart it so the change reaches the app. Use this to retrofit monitoring onto containers created before --monitoring was wired into create_container.\x82\xd3\xe4\x93\x02):\x01*\"$/v1/containers/{username}/monitoring\x12\xb9\x03\n" +
	"\x0fToggleAutoSleep\x12'.containarium.v1.ToggleAutoSleepRequest\x1a(.containarium.v1.ToggleAutoSleepResponse\"\xd2\x02\x92A\x9f\x02\n" +
	"\x14Container Operations\x12+Enable or disable auto-sleep on a container\x1a\xd9\x01Writes the per-container auto-sleep opt-in metadata (Incus user.* keys). Does not itself stop the container — use stop_container for that. Phase 2 (the actual idle-tick) and Phase 3 (wake-on-HTTP) consume this flag.\x82\xd3\xe4\x93\x02):\x01*\"$/v1/containers/{username}/auto-sleep\x12\xec\x03\n" +
	"\x0fSetContainerTTL\x12'.containarium.v1.SetContainerTTLRequest\x1a(.containarium.v1.SetContainerTTLResponse\"\x85\x03\x92A\xdd\x02\n" +
	"\x14Container Operations\x12/Schedule or clear a container's auto-delete TTL\x1a\x93\x02Stamps the container with a wall-clock auto-delete time consumed by the daemon's TTL sweeper. duration_seconds=0 clears any existing TTL; > 0 sets it to now()+duration. Capped at 604800 (7 days). Used by the containarium-run GitHub Action to auto-clean failed-CI debug boxes.\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/containers/{name}/ttl\x12\xae\x04\n" +
	"\x18SetContainerDeletePolicy\x120.containarium.v1.SetContainerDeletePolicyRequest\x1a1.containarium.v1.SetContainerDeletePolicyResponse\"\xac\x03\x92A\xfa\x02\n" +
	"\x14Container Operations\x128Protect or unprotect a container from automated deletion\x1a\xa7\x02Sets the container's delete policy (#284). DELETE_POLICY_PROTECTED makes the ttlsweeper auto-reap and `containarium prune` skip the box (e.g. a persistent runner); DELETE_POLICY_UNSPECIFIED returns it to the default (eligible for both). A deliberate single-box delete always succeeds regardless.\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/containers/{name}/delete-policy\x12\xbd\x04\n" +
	"\x17SetContainerAttribution\x12/.containarium.v1.SetContainerAttributionRequest\x1a0.containarium.v1.SetContainerAttributionResponse\"\xbe\x03\x92A\x8e\x03\n" +
	"\x14Container Operations\x123Merge attribution labels onto an existing container\x1a\xc0\x02Sets the given labels on a live container's config, leaving other labels intact (cloud #746). Lets the hosted control plane stamp cloud attribution (cloud_org_id / cloud_container_id / managed_by) on a pre-existing box so its adopt flow can bring it under management (cloud #539). 404 when the container doesn't resolve.\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/containers/{name}/attribution\x12\x9a\x02\n" +
	"\tAddSSHKey\x12!.containarium.v1.AddSSHKeyRequest\x1a\".containarium.v1.AddSSHKeyResponse\"\xc5\x01\x92A\x94\x01\n" +
	"\x0eSSH Management\x12\vAdd SSH key\x1auAdds an SSH public key to a container's authorized_keys file, allowing SSH access with the corresponding private key.\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/containers/{username}/ssh-keys\x12\xce\x02\n" +
	"\fRemoveSSHKey\x12$.containarium.v1.RemoveSSHKeyRequest\x1a%.containarium.v1.RemoveSSHKeyResponse\"\xf0\x01\x92A\xb1\x01\n" +
	"\x0eSSH Management\x12\x0eRemove SSH key\x1a\x8e\x01Removes an SSH public key from a container's authorized_keys file, revoking SSH access for that key. The ssh_public_key should be URL-encoded.\x82\xd3\xe4\x93\x025*3/v1/containers/{username}/ssh-keys/{ssh_public_key}\x12\xdf\x02\n" +
	"\x0fAddCollaborator\x12'.containarium.v1.AddCollaboratorRequest\x1a(.containarium.v1.AddCollaboratorResponse\"\xf8\x01\x92A\xbc\x01\n" +
	"\rCollaborators\x12\x10Add collaborator\x1a\x98\x01Adds a collaborator to a container. The collaborator can SSH via ProxyJump and sudo su to the container owner with full session logging for audit trail.\x82\xd3\xe4\x93\x022:\x01*\"-/v1/containers/{owner_username}/collaborators\x12\xc8\x02\n" +
	"\x12RemoveCollaborator\x12*.containarium.v1.RemoveCollaboratorRequest\x1a+.containarium.v1.RemoveCollaboratorResponse\"\xd8\x01\x92A\x87\x01\n" +
	"\rCollaborators\x12\x13Remove collaborator\x1aaRemoves a collaborator's access to a container, deleting both jump server and container accounts.\x82\xd3\xe4\x93\x02G*E/v1/containers/{owner_username}/collaborators/{collaborator_username}\x12\xff\x01\n" +
	"\x11ListCollaborators\x12).containarium.v1.ListCollaboratorsRequest\x1a*.containarium.v1.ListCollaboratorsResponse\"\x92\x01\x92AZ\n" +
	"\rCollaborators\x12\x12List collaborators\x1a5Returns all collaborators with access to a container.\x82\xd3\xe4\x93\x02/\x12-/v1/containers/{owner_username}/collaborators\x12\xd2\x02\n" +
	"\n" +
	"GetMetrics\x12\".containarium.v1.GetMetricsRequest\x1a#.containarium.v1.GetMetricsResponse\"\xfa\x01\x92A\xc9\x01\n" +
	"\n" +
	"Monitoring\x12\x15Get container metrics\x1a\xa3\x01Returns runtime metrics (CPU, memory, disk, network usage) for containers. Specify username to get metrics for a specific container, or omit to get all containers.\x82\xd3\xe4\x93\x02'Z\x18\x12\x16/v1/metrics/{username}\x12\v/v1/metrics\x12\xe6\x02\n" +
	"\vCleanupDisk\x12#.containarium.v1.CleanupDiskRequest\x1a$.containarium.v1.CleanupDiskResponse\"\x8b\x02\x92A\xd6\x01\n" +
	"\x14Container Operations\x12\x1dClean up container disk space\x1a\x9e\x01Frees disk space inside a container by removing temporary files, package manager caches, and trimming journal logs. Useful when disk is full and resize fails.\x82\xd3\xe4\x93\x02+:\x01*\"&/v1/containers/{username}/cleanup-disk\x12\xae\x02\n" +
	"\fInstallStack\x12$.containarium.v1.InstallStackRequest\x1a%.containarium.v1.InstallStackResponse\"\xd0\x01\x92A\x9a\x01\n" +
	"\x14Container Operations\x12'Install a software stack on a container\x1aYInstalls a pre-configured software stack or base script on an existing running container.\x82\xd3\xe4\x93\x02,:\x01*\"'/v1/containers/{username}/install-stack\x12\xad\x02\n" +
	"\n" +
	"ListStacks\x12\".containarium.v1.ListStacksRequest\x1a#.containarium.v1.ListStacksResponse\"\xd5\x01\x92A\xbf\x01\n" +
	"\x14Container Operations\x12\x1eList available software stacks\x1a\x86\x01Returns all configured software stacks including their parameters (name, type, default, etc.) for rendering the Create Container form.\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/stacks\x12\x8b\x02\n" +
	"\rGetSystemInfo\x12%.containarium.v1.GetSystemInfoRequest\x1a&.containarium.v1.GetSystemInfoResponse\"\xaa\x01\x92A\x8f\x01\n" +
	"\x06System\x12\x16Get system information\x1amReturns information about the host system including Incus version, available resources, and container counts.\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/system/info\x12\xbd\x02\n" +
	"\fListBackends\x12$.containarium.v1.ListBackendsRequest\x1a%.containarium.v1.ListBackendsResponse\"\xdf\x01\x92A\xc7\x01\n" +
	"\x06System\x12\rList backends\x1a\xad\x01Lists every backend in the fleet (local daemon + tunnel peers) with health, version, OS, running container count, and GPU inventory. Admin-only — discloses fleet topology.\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/backends\x12\xfc\x02\n" +
	"\x11AdvertiseCapacity\x12).containarium.v1.AdvertiseCapacityRequest\x1a*.containarium.v1.AdvertiseCapacityResponse\"\x8f\x02\x92A\xeb\x01\n" +
	"\x06System\x12#Advertise spare scheduling capacity\x1a\xbb\x01Publishes this backend's spare scheduling headroom (spare CPU/memory/disk + host idle fraction) to the control plane, bounded by a local policy. Surfaced through ListBackends. Admin-only.\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/capacity/headroom\x12\xb8\x02\n" +
	"\x10WithdrawCapacity\x12(.containarium.v1.WithdrawCapacityRequest\x1a).containarium.v1.WithdrawCapacityResponse\"\xce\x01\x92A\xad\x01\n" +
	"\x06System\x12\"Withdraw spare scheduling capacity\x1a\x7fWithdraws this backend's headroom advertisement. Idempotent — succeeds even when nothing is currently advertised. Admin-only.\x82\xd3\xe4\x93\x02\x17*\x15/v1/capacity/headroom\x12\x9c\x02\n" +
	"\x13GetCapacityHeadroom\x12+.containarium.v1.GetCapacityHeadroomRequest\x1a,.containarium.v1.GetCapacityHeadroomResponse\"\xa9\x01\x92A\x88\x01\n" +
	"\x06System\x12\x1dGet spare scheduling capacity\x1a_Returns this backend's current headroom advertisement and recomputed spare figures. Admin-only.\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/capacity/headroom\x12\x88\x03\n" +
	"\x0eProfileBackend\x12&.containarium.v1.ProfileBackendRequest\x1a'.containarium.v1.ProfileBackendResponse\"\xa4\x02\x92A\xfd\x01\n" +
	"\x06System\x12'Profile a backend's hardware capability\x1a\xc9\x01Records a backend's capability profile (hardware class, GPU probe, bounded CPU/memory micro-benchmark, region) and reconciles measured vs self-reported class. Surfaced through ListBackends. Admin-only.\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/capabilities/profile\x12\xd5\x02\n" +
	"\x14GetCapabilityProfile\x12,.containarium.v1.GetCapabilityProfileRequest\x1a-.containarium.v1.GetCapabilityProfileResponse\"\xdf\x01\x92A\xbb\x01\n" +
	"\x06System\x12\"Get a backend's capability profile\x1a\x8c\x01Returns a backend's last-recorded capability profile (hardware class, GPU probe, micro-benchmark, region) without re-running it. Admin-only.\x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/capabilities/profile\x12\xc0\x03\n" +
	"\x12GetSelfMeasurement\x12*.containarium.v1.GetSelfMeasurementRequest\x1a+.containarium.v1.GetSelfMeasurementResponse\"\xd0\x02\x92A\xa6\x02\n" +
	"\x06System\x121Get a backend's signed integrity self-measurement\x1a\xe8\x01Computes and signs a fresh integrity self-measurement (daemon binary digest, loaded in-kernel program object digests, policy/config-state digest) with the node's identity key. The daemon also emits this on its heartbeat. Admin-only.\x82\xd3\xe4\x93\x02 \x12\x1e/v1/integrity/self-measurement\x12\xb4\x02\n" +
	"\x10GetLatestRelease\x12(.containarium.v1.GetLatestReleaseRequest\x1a).containarium.v1.GetLatestReleaseResponse\"\xca\x01\x92A\xab\x01\n" +
	"\x06System\x12\x12Get latest release\x1a\x8c\x01Returns the latest Containarium release tag from GitHub (cached) alongside this daemon's running version and whether an update is available.\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/releases/latest\x12\xb9\x02\n" +
	"\vValidateGPU\x12#.containarium.v1.ValidateGPURequest\x1a$.containarium.v1.ValidateGPUResponse\"\xde\x01\x92A\xbf\x01\n" +
	"\x06System\x12\x18Validate GPU passthrough\x1a\x9a\x01Launches a throwaway nvidia.runtime LXC on the backend, runs nvidia-smi inside, and returns whether the GPU is usable (status, model, driver). Admin-only.\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/validate-gpu\x12\xae\x03\n" +
	"\x0eTriggerUpgrade\x12&.containarium.v1.TriggerUpgradeRequest\x1a'.containarium.v1.TriggerUpgradeResponse\"\xca\x02\x92A\xa7\x02\n" +
	"\x06System\x12#Trigger daemon upgrade on a backend\x1a\xf7\x01Upgrades a backend's daemon to the binary the sentinel currently serves, immediately instead of on the periodic tick. SHA-verified and smoke-tested before an atomic swap; the daemon restarts. Admin-only. Returns an upgrade_id for GetUpgradeStatus.\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/backends/upgrade\x12\x85\x03\n" +
	"\x10GetUpgradeStatus\x12(.containarium.v1.GetUpgradeStatusRequest\x1a).containarium.v1.GetUpgradeStatusResponse\"\x9b\x02\x92A\xf6\x01\n" +
	"\x06System\x12\x13Poll upgrade status\x1a\xd6\x01Returns the status of an upgrade started by TriggerUpgrade. Note: a local self-upgrade restarts the daemon and drops job state, returning 'unknown' afterward; compare the backend version in ListBackends to confirm.\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/upgrades/{upgrade_id}\x12\xb7\x02\n" +
	"\x11GetMonitoringInfo\x12).containarium.v1.GetMonitoringInfoRequest\x1a*.containarium.v1.GetMonitoringInfoResponse\"\xca\x01\x92A\xa9\x01\n" +
	"\n" +
	"Monitoring\x12\x1aGet monitoring information\x1a\x7fReturns monitoring configuration including Grafana and VictoriaMetrics URLs. Used by the web UI to embed the Grafana dashboard.\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/system/monitoring\x12\xe5\x04\n" +
	"\x10SetMetricsExport\x12(.containarium.v1.SetMetricsExportRequest\x1a).containarium.v1.SetMetricsExportResponse\"\xfb\x03\x92A\xd3\x03\n" +
	"\n" +
	"Monitoring\x12-Enable or disable cloud-native metrics export\x1a\x95\x03Opt-in export of host/container infra metrics to the host cloud's native monitoring (GCP Cloud Monitoring in the MVP). Enabling probes Application Default Credentials (monitoring-write scope) before persisting anything; a host with no resolvable ADC fails with FAILED_PRECONDITION and an IAM remediation hint. Disabling stops emission within one export interval. AWS is reserved and returns UNIMPLEMENTED.\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/system/metrics-export\x12\xf6\x02\n" +
	"\x10GetMetricsExport\x12(.containarium.v1.GetMetricsExportRequest\x1a).containarium.v1.GetMetricsExportResponse\"\x8c\x02\x92A\xe7\x01\n" +
	"\n" +
	"Monitoring\x12&Get cloud-native metrics export status\x1a\xb0\x01Returns whether cloud-native metrics export is enabled, the configured provider, the export interval, and last-known health (populated once the collector lands in #1070/#1071).\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/system/metrics-export\x12\x87\x02\n" +
	"\x0fCreateAlertRule\x12'.containarium.v1.CreateAlertRuleRequest\x1a(.containarium.v1.CreateAlertRuleResponse\"\xa0\x01\x92A\x87\x01\n" +
	"\x06Alerts\x12\x11Create alert rule\x1ajCreates a new custom alert rule. The rule is persisted in PostgreSQL and synced to vmalert for evaluation.\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/alerts\x12\xca\x01\n" +
	"\x0eListAlertRules\x12&.containarium.v1.ListAlertRulesRequest\x1a'.containarium.v1.ListAlertRulesResponse\"g\x92AR\n" +
	"\x06Alerts\x12\x10List alert rules\x1a6Returns all custom alert rules stored in the database.\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/alerts\x12\xb7\x01\n" +
	"\fGetAlertRule\x12$.containarium.v1.GetAlertRuleRequest\x1a%.containarium.v1.GetAlertRuleResponse\"Z\x92A@\n" +
	"\x06Alerts\x12\x0eGet alert rule\x1a&Returns a single alert rule by its ID.\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/alerts/{id}\x12\xed\x01\n" +
	"\x0fUpdateAlertRule\x12'.containarium.v1.UpdateAlertRuleRequest\x1a(.containarium.v1.UpdateAlertRuleResponse\"\x86\x01\x92Ai\n" +
	"\x06Alerts\x12\x11Update alert rule\x1aLUpdates an existing alert rule. Changes are synced to vmalert automatically.\x82\xd3\xe4\x93\x02\x14:\x01*\x1a\x0f/v1/alerts/{id}\x12\xf2\x01\n" +
	"\x0fDeleteAlertRule\x12'.containarium.v1.DeleteAlertRuleRequest\x1a(.containarium.v1.DeleteAlertRuleResponse\"\x8b\x01\x92Aq\n" +
	"\x06Alerts\x12\x11Delete alert rule\x1aTDeletes an alert rule by ID. The rule is removed from both the database and vmalert.\x82\xd3\xe4\x93\x02\x11*\x0f/v1/alerts/{id}\x12\x9b\x02\n" +
	"\x0fGetAlertingInfo\x12'.containarium.v1.GetAlertingInfoRequest\x1a(.containarium.v1.GetAlertingInfoResponse\"\xb4\x01\x92A\x95\x01\n" +
	"\x06Alerts\x12\x18Get alerting information\x1aqReturns alerting system status including vmalert and Alertmanager health, webhook configuration, and rule counts.\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/system/alerting\x12\xc0\x02\n" +
	"\x15ListDefaultAlertRules\x12-.containarium.v1.ListDefaultAlertRulesRequest\x1a..containarium.v1.ListDefaultAlertRulesResponse\"\xc7\x01\x92A\xa8\x01\n" +
	"\x06Alerts\x12\x18List default alert rules\x1a\x83\x01Returns the built-in default alert rules for system and container monitoring. These rules are always active and cannot be modified.\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/alerts/defaults\x12\xb7\x02\n" +
	"\x14UpdateAlertingConfig\x12,.containarium.v1.UpdateAlertingConfigRequest\x1a-.containarium.v1.UpdateAlertingConfigResponse\"\xc1\x01\x92A\x9f\x01\n" +
	"\x06Alerts\x12\x1dUpdate alerting configuration\x1avUpdates the alerting system configuration, such as the webhook URL for notifications. Changes take effect immediately.\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/v1/system/alerting\x12\xfe\x01\n" +
	"\vTestWebhook\x12#.containarium.v1.TestWebhookRequest\x1a$.containarium.v1.TestWebhookResponse\"\xa3\x01\x92A}\n" +
	"\x06Alerts\x12\fTest webhook\x1aeSends a test alert notification to the configured webhook URL with current system status information.\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/system/alerting/test\x12\xb0\x02\n" +
	"\x15ListWebhookDeliveries\x12-.containarium.v1.ListWebhookDeliveriesRequest\x1a..containarium.v1.ListWebhookDeliveriesResponse\"\xb7\x01\x92A\x8d\x01\n" +
	"\x06Alerts\x12\x17List webhook deliveries\x1ajReturns the history of webhook delivery attempts including success/failure status, HTTP codes, and timing.\x82\xd3\xe4\x93\x02 \x12\x1e/v1/system/alerting/deliveries\x12\xf9\x02\n" +
	"\tSetSecret\x12!.containarium.v1.SetSecretRequest\x1a\".containarium.v1.SetSecretResponse\"\xa4\x02\x92A\x8a\x02\n" +
	"\aSecrets\x12 Create or update a tenant secret\x1a\xdc\x01Encrypts the value with the daemon's master key and stores it in Postgres. Idempotent: same (username, name) bumps version. The value is never logged. Name must match ^[A-Z_][A-Z0-9_]*$ up to 128 chars; value max 64 KiB.\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/secrets\x12\xa0\x02\n" +
	"\tGetSecret\x12!.containarium.v1.GetSecretRequest\x1a\".containarium.v1.GetSecretResponse\"\xcb\x01\x92A\xa2\x01\n" +
	"\aSecrets\x12\x1bRead a single tenant secret\x1azReturns the decrypted plaintext value. Audit-logged. Caller's responsibility to keep the value safe once it's on the wire.\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/secrets/{username}/{name}\x12\x93\x02\n" +
	"\vListSecrets\x12#.containarium.v1.ListSecretsRequest\x1a$.containarium.v1.ListSecretsResponse\"\xb8\x01\x92A\x96\x01\n" +
	"\aSecrets\x12#List tenant secrets (metadata only)\x1afReturns name/version/timestamp tuples. Values are only readable via GetSecret per-name (audit-logged).\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/secrets/{username}\x12\xbd\x02\n" +
	"\fDeleteSecret\x12$.containarium.v1.DeleteSecretRequest\x1a%.containarium.v1.DeleteSecretResponse\"\xdf\x01\x92A\xb6\x01\n" +
	"\aSecrets\x12\x16Delete a tenant secret\x1a\x92\x01Removes the secret from Postgres. Does NOT cascade to env-var stamps on running containers — call RefreshSecrets to re-stamp without restarting.\x82\xd3\xe4\x93\x02\x1f*\x1d/v1/secrets/{username}/{name}\x12\x90\x03\n" +
	"\x0eRefreshSecrets\x12&.containarium.v1.RefreshSecretsRequest\x1a'.containarium.v1.RefreshSecretsResponse\"\xac\x02\x92A\xff\x01\n" +
	"\aSecrets\x12(Re-stamp tenant secrets into the LXC env\x1a\xc9\x01Reads all of the tenant's secrets from the DB, decrypts, and updates the LXC's environment.<NAME> config keys to match. Running processes keep their old env (POSIX); new execs see the refreshed values.\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/secrets/{username}/refreshB\xa4\x04\x92A\xd5\x03\x12\xc4\x02\n" +
	"\x10Containarium API\x12\xa0\x01Container management API for LXC-based development environments. Provides both gRPC and REST interfaces for managing containers, SSH keys, and system resources.\";\n" +
	"\fContainarium\x12+https://github.com/footprintai/containarium*K\n" +
	"\n" +
	"Apache 2.0\x12=https://github.com/footprintai/containarium/blob/main/LICENSE2\x031.0*\x02\x02\x012\x10application/json:\x10application/jsonZV\n" +
	"T\n" +
	"\x06bearer\x12J\b\x02\x125Bearer token authentication. Format: 'Bearer <token>'\x1a\rAuthorization \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00ZIgithub.com/footprintai/containarium/pkg/pb/containarium/v1;containariumv1b\x06proto3"

var file_containarium_v1_service_proto_goTypes = []any{
	(*CreateContainerRequest)(nil),           // 0: containarium.v1.CreateContainerRequest
	(*ListContainersRequest)(nil),            // 1: containarium.v1.ListContainersRequest
	(*GetContainerRequest)(nil),              // 2: containarium.v1.GetContainerRequest
	(*DebugContainerRequest)(nil),            // 3: containarium.v1.DebugContainerRequest
	(*DeleteContainerRequest)(nil),           // 4: containarium.v1.DeleteContainerRequest
	(*StartContainerRequest)(nil),            // 5: containarium.v1.StartContainerRequest
	(*StopContainerRequest)(nil),             // 6: containarium.v1.StopContainerRequest
	(*ResizeContainerRequest)(nil),           // 7: containarium.v1.ResizeContainerRequest
	(*MoveContainerRequest)(nil),             // 8: containarium.v1.MoveContainerRequest
	(*AdoptMigratedContainerRequest)(nil),    // 9: containarium.v1.AdoptMigratedContainerRequest
	(*ToggleMonitoringRequest)(nil),          // 10: containarium.v1.ToggleMonitoringRequest
	(*ToggleAutoSleepRequest)(nil),           // 11: containarium.v1.ToggleAutoSleepRequest
	(*SetContainerTTLRequest)(nil),           // 12: containarium.v1.SetContainerTTLRequest
	(*SetContainerDeletePolicyRequest)(nil),  // 13: containarium.v1.SetContainerDeletePolicyRequest
	(*SetContainerAttributionRequest)(nil),   // 14: containarium.v1.SetContainerAttributionRequest
	(*AddSSHKeyRequest)(nil),                 // 15: containarium.v1.AddSSHKeyRequest
	(*RemoveSSHKeyRequest)(nil),              // 16: containarium.v1.RemoveSSHKeyRequest
	(*AddCollaboratorRequest)(nil),           // 17: containarium.v1.AddCollaboratorRequest
	(*RemoveCollaboratorRequest)(nil),        // 18: containarium.v1.RemoveCollaboratorRequest
	(*ListCollaboratorsRequest)(nil),         // 19: containarium.v1.ListCollaboratorsRequest
	(*GetMetricsRequest)(nil),                // 20: containarium.v1.GetMetricsRequest
	(*CleanupDiskRequest)(nil),               // 21: containarium.v1.CleanupDiskRequest
	(*InstallStackRequest)(nil),              // 22: containarium.v1.InstallStackRequest
	(*ListStacksRequest)(nil),                // 23: containarium.v1.ListStacksRequest
	(*GetSystemInfoRequest)(nil),             // 24: containarium.v1.GetSystemInfoRequest
	(*ListBackendsRequest)(nil),              // 25: containarium.v1.ListBackendsRequest
	(*AdvertiseCapacityRequest)(nil),         // 26: containarium.v1.AdvertiseCapacityRequest
	(*WithdrawCapacityRequest)(nil),          // 27: containarium.v1.WithdrawCapacityRequest
	(*GetCapacityHeadroomRequest)(nil),       // 28: containarium.v1.GetCapacityHeadroomRequest
	(*ProfileBackendRequest)(nil),            // 29: containarium.v1.ProfileBackendRequest
	(*GetCapabilityProfileRequest)(nil),      // 30: containarium.v1.GetCapabilityProfileRequest
	(*GetSelfMeasurementRequest)(nil),        // 31: containarium.v1.GetSelfMeasurementRequest
	(*GetLatestReleaseRequest)(nil),          // 32: containarium.v1.GetLatestReleaseRequest
	(*ValidateGPURequest)(nil),               // 33: containarium.v1.ValidateGPURequest
	(*TriggerUpgradeRequest)(nil),            // 34: containarium.v1.TriggerUpgradeRequest
	(*GetUpgradeStatusRequest)(nil),          // 35: containarium.v1.GetUpgradeStatusRequest
	(*GetMonitoringInfoRequest)(nil),         // 36: containarium.v1.GetMonitoringInfoRequest
	(*SetMetricsExportRequest)(nil),          // 37: containarium.v1.SetMetricsExportRequest
	(*GetMetricsExportRequest)(nil),          // 38: containarium.v1.GetMetricsExportRequest
	(*CreateAlertRuleRequest)(nil),           // 39: containarium.v1.CreateAlertRuleRequest
	(*ListAlertRulesRequest)(nil),            // 40: containarium.v1.ListAlertRulesRequest
	(*GetAlertRuleRequest)(nil),              // 41: containarium.v1.GetAlertRuleRequest
	(*UpdateAlertRuleRequest)(nil),           // 42: containarium.v1.UpdateAlertRuleRequest
	(*DeleteAlertRuleRequest)(nil),           // 43: containarium.v1.DeleteAlertRuleRequest
	(*GetAlertingInfoRequest)(nil),           // 44: containarium.v1.GetAlertingInfoRequest
	(*ListDefaultAlertRulesRequest)(nil),     // 45: containarium.v1.ListDefaultAlertRulesRequest
	(*UpdateAlertingConfigRequest)(nil),      // 46: containarium.v1.UpdateAlertingConfigRequest
	(*TestWebhookRequest)(nil),               // 47: containarium.v1.TestWebhookRequest
	(*ListWebhookDeliveriesRequest)(nil),     // 48: containarium.v1.ListWebhookDeliveriesRequest
	(*SetSecretRequest)(nil),                 // 49: containarium.v1.SetSecretRequest
	(*GetSecretRequest)(nil),                 // 50: containarium.v1.GetSecretRequest
	(*ListSecretsRequest)(nil),               // 51: containarium.v1.ListSecretsRequest
	(*DeleteSecretRequest)(nil),              // 52: containarium.v1.DeleteSecretRequest
	(*RefreshSecretsRequest)(nil),            // 53: containarium.v1.RefreshSecretsRequest
	(*CreateContainerResponse)(nil),          // 54: containarium.v1.CreateContainerResponse
	(*ListContainersResponse)(nil),           // 55: containarium.v1.ListContainersResponse
	(*GetContainerResponse)(nil),             // 56: containarium.v1.GetContainerResponse
	(*DebugContainerResponse)(nil),           // 57: containarium.v1.DebugContainerResponse
	(*DeleteContainerResponse)(nil),          // 58: containarium.v1.DeleteContainerResponse
	(*StartContainerResponse)(nil),           // 59: containarium.v1.StartContainerResponse
	(*StopContainerResponse)(nil),            // 60: containarium.v1.StopContainerResponse
	(*ResizeContainerResponse)(nil),          // 61: containarium.v1.ResizeContainerResponse
	(*MoveContainerResponse)(nil),            // 62: containarium.v1.MoveContainerResponse
	(*AdoptMigratedContainerResponse)(nil),   // 63: containarium.v1.AdoptMigratedContainerResponse
	(*ToggleMonitoringResponse)(nil),         // 64: containarium.v1.ToggleMonitoringResponse
	(*ToggleAutoSleepResponse)(nil),          // 65: containarium.v1.ToggleAutoSleepResponse
	(*SetContainerTTLResponse)(nil),          // 66: containarium.v1.SetContainerTTLResponse
	(*SetContainerDeletePolicyResponse)(nil), // 67: containarium.v1.SetContainerDeletePolicyResponse
	(*SetContainerAttributionResponse)(nil),  // 68: containarium.v1.SetContainerAttributionResponse
	(*AddSSHKeyResponse)(nil),                // 69: containarium.v1.AddSSHKeyResponse
	(*RemoveSSHKeyResponse)(nil),             // 70: containarium.v1.RemoveSSHKeyResponse
	(*AddCollaboratorResponse)(nil),          // 71: containarium.v1.AddCollaboratorResponse
	(*RemoveCollaboratorResponse)(nil),       // 72: containarium.v1.RemoveCollaboratorResponse
	(*ListCollaboratorsResponse)(nil),        // 73: containarium.v1.ListCollaboratorsResponse
	(*GetMetricsResponse)(nil),               // 74: containarium.v1.GetMetricsResponse
	(*CleanupDiskResponse)(nil),              // 75: containarium.v1.CleanupDiskResponse
	(*InstallStackResponse)(nil),             // 76: containarium.v1.InstallStackResponse
	(*ListStacksResponse)(nil),               // 77: containarium.v1.ListStacksResponse
	(*GetSystemInfoResponse)(nil),            // 78: containarium.v1.GetSystemInfoResponse
	(*ListBackendsResponse)(nil),             // 79: containarium.v1.ListBackendsResponse
	(*AdvertiseCapacityResponse)(nil),        // 80: containarium.v1.AdvertiseCapacityResponse
	(*WithdrawCapacityResponse)(nil),         // 81: containarium.v1.WithdrawCapacityResponse
	(*GetCapacityHeadroomResponse)(nil),      // 82: containarium.v1.GetCapacityHeadroomResponse
	(*ProfileBackendResponse)(nil),           // 83: containarium.v1.ProfileBackendResponse
	(*GetCapabilityProfileResponse)(nil),     // 84: containarium.v1.GetCapabilityProfileResponse
	(*GetSelfMeasurementResponse)(nil),       // 85: containarium.v1.GetSelfMeasurementResponse
	(*GetLatestReleaseResponse)(nil),         // 86: containarium.v1.GetLatestReleaseResponse
	(*ValidateGPUResponse)(nil),              // 87: containarium.v1.ValidateGPUResponse
	(*TriggerUpgradeResponse)(nil),           // 88: containarium.v1.TriggerUpgradeResponse
	(*GetUpgradeStatusResponse)(nil),         // 89: containarium.v1.GetUpgradeStatusResponse
	(*GetMonitoringInfoResponse)(nil),        // 90: containarium.v1.GetMonitoringInfoResponse
	(*SetMetricsExportResponse)(nil),         // 91: containarium.v1.SetMetricsExportResponse
	(*GetMetricsExportResponse)(nil),         // 92: containarium.v1.GetMetricsExportResponse
	(*CreateAlertRuleResponse)(nil),          // 93: containarium.v1.CreateAlertRuleResponse
	(*ListAlertRulesResponse)(nil),           // 94: containarium.v1.ListAlertRulesResponse
	(*GetAlertRuleResponse)(nil),             // 95: containarium.v1.GetAlertRuleResponse
	(*UpdateAlertRuleResponse)(nil),          // 96: containarium.v1.UpdateAlertRuleResponse
	(*DeleteAlertRuleResponse)(nil),          // 97: containarium.v1.DeleteAlertRuleResponse
	(*GetAlertingInfoResponse)(nil),          // 98: containarium.v1.GetAlertingInfoResponse
	(*ListDefaultAlertRulesResponse)(nil),    // 99: containarium.v1.ListDefaultAlertRulesResponse
	(*UpdateAlertingConfigResponse)(nil),     // 100: containarium.v1.UpdateAlertingConfigResponse
	(*TestWebhookResponse)(nil),              // 101: containarium.v1.TestWebhookResponse
	(*ListWebhookDeliveriesResponse)(nil),    // 102: containarium.v1.ListWebhookDeliveriesResponse
	(*SetSecretResponse)(nil),                // 103: containarium.v1.SetSecretResponse
	(*GetSecretResponse)(nil),                // 104: containarium.v1.GetSecretResponse
	(*ListSecretsResponse)(nil),              // 105: containarium.v1.ListSecretsResponse
	(*DeleteSecretResponse)(nil),             // 106: containarium.v1.DeleteSecretResponse
	(*RefreshSecretsResponse)(nil),           // 107: containarium.v1.RefreshSecretsResponse
}
var file_containarium_v1_service_proto_depIdxs = []int32{
	0,   // 0: containarium.v1.ContainerService.CreateContainer:input_type -> containarium.v1.CreateContainerRequest
	1,   // 1: containarium.v1.ContainerService.ListContainers:input_type -> containarium.v1.ListContainersRequest
	2,   // 2: containarium.v1.ContainerService.GetContainer:input_type -> containarium.v1.GetContainerRequest
	3,   // 3: containarium.v1.ContainerService.DebugContainer:input_type -> containarium.v1.DebugContainerRequest
	4,   // 4: containarium.v1.ContainerService.DeleteContainer:input_type -> containarium.v1.DeleteContainerRequest
	5,   // 5: containarium.v1.ContainerService.StartContainer:input_type -> containarium.v1.StartContainerRequest
	6,   // 6: containarium.v1.ContainerService.StopContainer:input_type -> containarium.v1.StopContainerRequest
	7,   // 7: containarium.v1.ContainerService.ResizeContainer:input_type -> containarium.v1.ResizeContainerRequest
	8,   // 8: containarium.v1.ContainerService.MoveContainer:input_type -> containarium.v1.MoveContainerRequest
	9,   // 9: containarium.v1.ContainerService.AdoptMigratedContainer:input_type -> containarium.v1.AdoptMigratedContainerRequest
	10,  // 10: containarium.v1.ContainerService.ToggleMonitoring:input_type -> containarium.v1.ToggleMonitoringRequest
	11,  // 11: containarium.v1.ContainerService.ToggleAutoSleep:input_type -> containarium.v1.ToggleAutoSleepRequest
	12,  // 12: containarium.v1.ContainerService.SetContainerTTL:input_type -> containarium.v1.SetContainerTTLRequest
	13,  // 13: containarium.v1.ContainerService.SetContainerDeletePolicy:input_type -> containarium.v1.SetContainerDeletePolicyRequest
	14,  // 14: containarium.v1.ContainerService.SetContainerAttribution:input_type -> containarium.v1.SetContainerAttributionRequest
	15,  // 15: containarium.v1.ContainerService.AddSSHKey:input_type -> containarium.v1.AddSSHKeyRequest
	16,  // 16: containarium.v1.ContainerService.RemoveSSHKey:input_type -> containarium.v1.RemoveSSHKeyRequest
	17,  // 17: containarium.v1.ContainerService.AddCollaborator:input_type -> containarium.v1.AddCollaboratorRequest
	18,  // 18: containarium.v1.ContainerService.RemoveCollaborator:input_type -> containarium.v1.RemoveCollaboratorRequest
	19,  // 19: containarium.v1.ContainerService.ListCollaborators:input_type -> containarium.v1.ListCollaboratorsRequest
	20,  // 20: containarium.v1.ContainerService.GetMetrics:input_type -> containarium.v1.GetMetricsRequest
	21,  // 21: containarium.v1.ContainerService.CleanupDisk:input_type -> containarium.v1.CleanupDiskRequest
	22,  // 22: containarium.v1.ContainerService.InstallStack:input_type -> containarium.v1.InstallStackRequest
	23,  // 23: containarium.v1.ContainerService.ListStacks:input_type -> containarium.v1.ListStacksRequest
	24,  // 24: containarium.v1.ContainerService.GetSystemInfo:input_type -> containarium.v1.GetSystemInfoRequest
	25,  // 25: containarium.v1.ContainerService.ListBackends:input_type -> containarium.v1.ListBackendsRequest
	26,  // 26: containarium.v1.ContainerService.AdvertiseCapacity:input_type -> containarium.v1.AdvertiseCapacityRequest
	27,  // 27: containarium.v1.ContainerService.WithdrawCapacity:input_type -> containarium.v1.WithdrawCapacityRequest
	28,  // 28: containarium.v1.ContainerService.GetCapacityHeadroom:input_type -> containarium.v1.GetCapacityHeadroomRequest
	29,  // 29: containarium.v1.ContainerService.ProfileBackend:input_type -> containarium.v1.ProfileBackendRequest
	30,  // 30: containarium.v1.ContainerService.GetCapabilityProfile:input_type -> containarium.v1.GetCapabilityProfileRequest
	31,  // 31: containarium.v1.ContainerService.GetSelfMeasurement:input_type -> containarium.v1.GetSelfMeasurementRequest
	32,  // 32: containarium.v1.ContainerService.GetLatestRelease:input_type -> containarium.v1.GetLatestReleaseRequest
	33,  // 33: containarium.v1.ContainerService.ValidateGPU:input_type -> containarium.v1.ValidateGPURequest
	34,  // 34: containarium.v1.ContainerService.TriggerUpgrade:input_type -> containarium.v1.TriggerUpgradeRequest
	35,  // 35: containarium.v1.ContainerService.GetUpgradeStatus:input_type -> containarium.v1.GetUpgradeStatusRequest
	36,  // 36: containarium.v1.ContainerService.GetMonitoringInfo:input_type -> containarium.v1.GetMonitoringInfoRequest
	37,  // 37: containarium.v1.ContainerService.SetMetricsExport:input_type -> containarium.v1.SetMetricsExportRequest
	38,  // 38: containarium.v1.ContainerService.GetMetricsExport:input_type -> containarium.v1.GetMetricsExportRequest
	39,  // 39: containarium.v1.ContainerService.CreateAlertRule:input_type -> containarium.v1.CreateAlertRuleRequest
	40,  // 40: containarium.v1.ContainerService.ListAlertRules:input_type -> containarium.v1.ListAlertRulesRequest
	41,  // 41: containarium.v1.ContainerService.GetAlertRule:input_type -> containarium.v1.GetAlertRuleRequest
	42,  // 42: containarium.v1.ContainerService.UpdateAlertRule:input_type -> containarium.v1.UpdateAlertRuleRequest
	43,  // 43: containarium.v1.ContainerService.DeleteAlertRule:input_type -> containarium.v1.DeleteAlertRuleRequest
	44,  // 44: containarium.v1.ContainerService.GetAlertingInfo:input_type -> containarium.v1.GetAlertingInfoRequest
	45,  // 45: containarium.v1.ContainerService.ListDefaultAlertRules:input_type -> containarium.v1.ListDefaultAlertRulesRequest
	46,  // 46: containarium.v1.ContainerService.UpdateAlertingConfig:input_type -> containarium.v1.UpdateAlertingConfigRequest
	47,  // 47: containarium.v1.ContainerService.TestWebhook:input_type -> containarium.v1.TestWebhookRequest
	48,  // 48: containarium.v1.ContainerService.ListWebhookDeliveries:input_type -> containarium.v1.ListWebhookDeliveriesRequest
	49,  // 49: containarium.v1.ContainerService.SetSecret:input_type -> containarium.v1.SetSecretRequest
	50,  // 50: containarium.v1.ContainerService.GetSecret:input_type -> containarium.v1.GetSecretRequest
	51,  // 51: containarium.v1.ContainerService.ListSecrets:input_type -> containarium.v1.ListSecretsRequest
	52,  // 52: containarium.v1.ContainerService.DeleteSecret:input_type -> containarium.v1.DeleteSecretRequest
	53,  // 53: containarium.v1.ContainerService.RefreshSecrets:input_type -> containarium.v1.RefreshSecretsRequest
	54,  // 54: containarium.v1.ContainerService.CreateContainer:output_type -> containarium.v1.CreateContainerResponse
	55,  // 55: containarium.v1.ContainerService.ListContainers:output_type -> containarium.v1.ListContainersResponse
	56,  // 56: containarium.v1.ContainerService.GetContainer:output_type -> containarium.v1.GetContainerResponse
	57,  // 57: containarium.v1.ContainerService.DebugContainer:output_type -> containarium.v1.DebugContainerResponse
	58,  // 58: containarium.v1.ContainerService.DeleteContainer:output_type -> containarium.v1.DeleteContainerResponse
	59,  // 59: containarium.v1.ContainerService.StartContainer:output_type -> containarium.v1.StartContainerResponse
	60,  // 60: containarium.v1.ContainerService.StopContainer:output_type -> containarium.v1.StopContainerResponse
	61,  // 61: containarium.v1.ContainerService.ResizeContainer:output_type -> containarium.v1.ResizeContainerResponse
	62,  // 62: containarium.v1.ContainerService.MoveContainer:output_type -> containarium.v1.MoveContainerResponse
	63,  // 63: containarium.v1.ContainerService.AdoptMigratedContainer:output_type -> containarium.v1.AdoptMigratedContainerResponse
	64,  // 64: containarium.v1.ContainerService.ToggleMonitoring:output_type -> containarium.v1.ToggleMonitoringResponse
	65,  // 65: containarium.v1.ContainerService.ToggleAutoSleep:output_type -> containarium.v1.ToggleAutoSleepResponse
	66,  // 66: containarium.v1.ContainerService.SetContainerTTL:output_type -> containarium.v1.SetContainerTTLResponse
	67,  // 67: containarium.v1.ContainerService.SetContainerDeletePolicy:output_type -> containarium.v1.SetContainerDeletePolicyResponse
	68,  // 68: containarium.v1.ContainerService.SetContainerAttribution:output_type -> containarium.v1.SetContainerAttributionResponse
	69,  // 69: containarium.v1.ContainerService.AddSSHKey:output_type -> containarium.v1.AddSSHKeyResponse
	70,  // 70: containarium.v1.ContainerService.RemoveSSHKey:output_type -> containarium.v1.RemoveSSHKeyResponse
	71,  // 71: containarium.v1.ContainerService.AddCollaborator:output_type -> containarium.v1.AddCollaboratorResponse
	72,  // 72: containarium.v1.ContainerService.RemoveCollaborator:output_type -> containarium.v1.RemoveCollaboratorResponse
	73,  // 73: containarium.v1.ContainerService.ListCollaborators:output_type -> containarium.v1.ListCollaboratorsResponse
	74,  // 74: containarium.v1.ContainerService.GetMetrics:output_type -> containarium.v1.GetMetricsResponse
	75,  // 75: containarium.v1.ContainerService.CleanupDisk:output_type -> containarium.v1.CleanupDiskResponse
	76,  // 76: containarium.v1.ContainerService.InstallStack:output_type -> containarium.v1.InstallStackResponse
	77,  // 77: containarium.v1.ContainerService.ListStacks:output_type -> containarium.v1.ListStacksResponse
	78,  // 78: containarium.v1.ContainerService.GetSystemInfo:output_type -> containarium.v1.GetSystemInfoResponse
	79,  // 79: containarium.v1.ContainerService.ListBackends:output_type -> containarium.v1.ListBackendsResponse
	80,  // 80: containarium.v1.ContainerService.AdvertiseCapacity:output_type -> containarium.v1.AdvertiseCapacityResponse
	81,  // 81: containarium.v1.ContainerService.WithdrawCapacity:output_type -> containarium.v1.WithdrawCapacityResponse
	82,  // 82: containarium.v1.ContainerService.GetCapacityHeadroom:output_type -> containarium.v1.GetCapacityHeadroomResponse
	83,  // 83: containarium.v1.ContainerService.ProfileBackend:output_type -> containarium.v1.ProfileBackendResponse
	84,  // 84: containarium.v1.ContainerService.GetCapabilityProfile:output_type -> containarium.v1.GetCapabilityProfileResponse
	85,  // 85: containarium.v1.ContainerService.GetSelfMeasurement:output_type -> containarium.v1.GetSelfMeasurementResponse
	86,  // 86: containarium.v1.ContainerService.GetLatestRelease:output_type -> containarium.v1.GetLatestReleaseResponse
	87,  // 87: containarium.v1.ContainerService.ValidateGPU:output_type -> containarium.v1.ValidateGPUResponse
	88,  // 88: containarium.v1.ContainerService.TriggerUpgrade:output_type -> containarium.v1.TriggerUpgradeResponse
	89,  // 89: containarium.v1.ContainerService.GetUpgradeStatus:output_type -> containarium.v1.GetUpgradeStatusResponse
	90,  // 90: containarium.v1.ContainerService.GetMonitoringInfo:output_type -> containarium.v1.GetMonitoringInfoResponse
	91,  // 91: containarium.v1.ContainerService.SetMetricsExport:output_type -> containarium.v1.SetMetricsExportResponse
	92,  // 92: containarium.v1.ContainerService.GetMetricsExport:output_type -> containarium.v1.GetMetricsExportResponse
	93,  // 93: containarium.v1.ContainerService.CreateAlertRule:output_type -> containarium.v1.CreateAlertRuleResponse
	94,  // 94: containarium.v1.ContainerService.ListAlertRules:output_type -> containarium.v1.ListAlertRulesResponse
	95,  // 95: containarium.v1.ContainerService.GetAlertRule:output_type -> containarium.v1.GetAlertRuleResponse
	96,  // 96: containarium.v1.ContainerService.UpdateAlertRule:output_type -> containarium.v1.UpdateAlertRuleResponse
	97,  // 97: containarium.v1.ContainerService.DeleteAlertRule:output_type -> containarium.v1.DeleteAlertRuleResponse
	98,  // 98: containarium.v1.ContainerService.GetAlertingInfo:output_type -> containarium.v1.GetAlertingInfoResponse
	99,  // 99: containarium.v1.ContainerService.ListDefaultAlertRules:output_type -> containarium.v1.ListDefaultAlertRulesResponse
	100, // 100: containarium.v1.ContainerService.UpdateAlertingConfig:output_type -> containarium.v1.UpdateAlertingConfigResponse
	101, // 101: containarium.v1.ContainerService.TestWebhook:output_type -> containarium.v1.TestWebhookResponse
	102, // 102: containarium.v1.ContainerService.ListWebhookDeliveries:output_type -> containarium.v1.ListWebhookDeliveriesResponse
	103, // 103: containarium.v1.ContainerService.SetSecret:output_type -> containarium.v1.SetSecretResponse
	104, // 104: containarium.v1.ContainerService.GetSecret:output_type -> containarium.v1.GetSecretResponse
	105, // 105: containarium.v1.ContainerService.ListSecrets:output_type -> containarium.v1.ListSecretsResponse
	106, // 106: containarium.v1.ContainerService.DeleteSecret:output_type -> containarium.v1.DeleteSecretResponse
	107, // 107: containarium.v1.ContainerService.RefreshSecrets:output_type -> containarium.v1.RefreshSecretsResponse
	54,  // [54:108] is the sub-list for method output_type
	0,   // [0:54] is the sub-list for method input_type
	0,   // [0:0] is the sub-list for extension type_name
	0,   // [0:0] is the sub-list for extension extendee
	0,   // [0:0] is the sub-list for field type_name
}

func init() { file_containarium_v1_service_proto_init() }
func file_containarium_v1_service_proto_init() {
	if File_containarium_v1_service_proto != nil {
		return
	}
	file_containarium_v1_container_proto_init()
	file_containarium_v1_config_proto_init()
	file_containarium_v1_app_proto_init()
	file_containarium_v1_network_proto_init()
	file_containarium_v1_alert_proto_init()
	file_containarium_v1_secrets_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_containarium_v1_service_proto_rawDesc), len(file_containarium_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_containarium_v1_service_proto_goTypes,
		DependencyIndexes: file_containarium_v1_service_proto_depIdxs,
	}.Build()
	File_containarium_v1_service_proto = out.File
	file_containarium_v1_service_proto_goTypes = nil
	file_containarium_v1_service_proto_depIdxs = nil
}
