// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: containarium/v1/service.proto

package containariumv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_containarium_v1_service_proto protoreflect.FileDescriptor

const file_containarium_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1dcontainarium/v1/service.proto\x12\x0fcontainarium.v1\x1a\x1fcontainarium/v1/container.proto\x1a\x1ccontainarium/v1/config.proto2\xc9\a\n" +
	"\x10ContainerService\x12d\n" +
	"\x0fCreateContainer\x12'.containarium.v1.CreateContainerRequest\x1a(.containarium.v1.CreateContainerResponse\x12a\n" +
	"\x0eListContainers\x12&.containarium.v1.ListContainersRequest\x1a'.containarium.v1.ListContainersResponse\x12[\n" +
	"\fGetContainer\x12$.containarium.v1.GetContainerRequest\x1a%.containarium.v1.GetContainerResponse\x12d\n" +
	"\x0fDeleteContainer\x12'.containarium.v1.DeleteContainerRequest\x1a(.containarium.v1.DeleteContainerResponse\x12a\n" +
	"\x0eStartContainer\x12&.containarium.v1.StartContainerRequest\x1a'.containarium.v1.StartContainerResponse\x12^\n" +
	"\rStopContainer\x12%.containarium.v1.StopContainerRequest\x1a&.containarium.v1.StopContainerResponse\x12R\n" +
	"\tAddSSHKey\x12!.containarium.v1.AddSSHKeyRequest\x1a\".containarium.v1.AddSSHKeyResponse\x12[\n" +
	"\fRemoveSSHKey\x12$.containarium.v1.RemoveSSHKeyRequest\x1a%.containarium.v1.RemoveSSHKeyResponse\x12U\n" +
	"\n" +
	"GetMetrics\x12\".containarium.v1.GetMetricsRequest\x1a#.containarium.v1.GetMetricsResponse\x12^\n" +
	"\rGetSystemInfo\x12%.containarium.v1.GetSystemInfoRequest\x1a&.containarium.v1.GetSystemInfoResponseB\xcb\x01\n" +
	"\x13com.containarium.v1B\fServiceProtoP\x01ZIgithub.com/footprintai/containarium/pkg/pb/containarium/v1;containariumv1\xa2\x02\x03CXX\xaa\x02\x0fContainarium.V1\xca\x02\x0fContainarium\\V1\xe2\x02\x1bContainarium\\V1\\GPBMetadata\xea\x02\x10Containarium::V1b\x06proto3"

var file_containarium_v1_service_proto_goTypes = []any{
	(*CreateContainerRequest)(nil),  // 0: containarium.v1.CreateContainerRequest
	(*ListContainersRequest)(nil),   // 1: containarium.v1.ListContainersRequest
	(*GetContainerRequest)(nil),     // 2: containarium.v1.GetContainerRequest
	(*DeleteContainerRequest)(nil),  // 3: containarium.v1.DeleteContainerRequest
	(*StartContainerRequest)(nil),   // 4: containarium.v1.StartContainerRequest
	(*StopContainerRequest)(nil),    // 5: containarium.v1.StopContainerRequest
	(*AddSSHKeyRequest)(nil),        // 6: containarium.v1.AddSSHKeyRequest
	(*RemoveSSHKeyRequest)(nil),     // 7: containarium.v1.RemoveSSHKeyRequest
	(*GetMetricsRequest)(nil),       // 8: containarium.v1.GetMetricsRequest
	(*GetSystemInfoRequest)(nil),    // 9: containarium.v1.GetSystemInfoRequest
	(*CreateContainerResponse)(nil), // 10: containarium.v1.CreateContainerResponse
	(*ListContainersResponse)(nil),  // 11: containarium.v1.ListContainersResponse
	(*GetContainerResponse)(nil),    // 12: containarium.v1.GetContainerResponse
	(*DeleteContainerResponse)(nil), // 13: containarium.v1.DeleteContainerResponse
	(*StartContainerResponse)(nil),  // 14: containarium.v1.StartContainerResponse
	(*StopContainerResponse)(nil),   // 15: containarium.v1.StopContainerResponse
	(*AddSSHKeyResponse)(nil),       // 16: containarium.v1.AddSSHKeyResponse
	(*RemoveSSHKeyResponse)(nil),    // 17: containarium.v1.RemoveSSHKeyResponse
	(*GetMetricsResponse)(nil),      // 18: containarium.v1.GetMetricsResponse
	(*GetSystemInfoResponse)(nil),   // 19: containarium.v1.GetSystemInfoResponse
}
var file_containarium_v1_service_proto_depIdxs = []int32{
	0,  // 0: containarium.v1.ContainerService.CreateContainer:input_type -> containarium.v1.CreateContainerRequest
	1,  // 1: containarium.v1.ContainerService.ListContainers:input_type -> containarium.v1.ListContainersRequest
	2,  // 2: containarium.v1.ContainerService.GetContainer:input_type -> containarium.v1.GetContainerRequest
	3,  // 3: containarium.v1.ContainerService.DeleteContainer:input_type -> containarium.v1.DeleteContainerRequest
	4,  // 4: containarium.v1.ContainerService.StartContainer:input_type -> containarium.v1.StartContainerRequest
	5,  // 5: containarium.v1.ContainerService.StopContainer:input_type -> containarium.v1.StopContainerRequest
	6,  // 6: containarium.v1.ContainerService.AddSSHKey:input_type -> containarium.v1.AddSSHKeyRequest
	7,  // 7: containarium.v1.ContainerService.RemoveSSHKey:input_type -> containarium.v1.RemoveSSHKeyRequest
	8,  // 8: containarium.v1.ContainerService.GetMetrics:input_type -> containarium.v1.GetMetricsRequest
	9,  // 9: containarium.v1.ContainerService.GetSystemInfo:input_type -> containarium.v1.GetSystemInfoRequest
	10, // 10: containarium.v1.ContainerService.CreateContainer:output_type -> containarium.v1.CreateContainerResponse
	11, // 11: containarium.v1.ContainerService.ListContainers:output_type -> containarium.v1.ListContainersResponse
	12, // 12: containarium.v1.ContainerService.GetContainer:output_type -> containarium.v1.GetContainerResponse
	13, // 13: containarium.v1.ContainerService.DeleteContainer:output_type -> containarium.v1.DeleteContainerResponse
	14, // 14: containarium.v1.ContainerService.StartContainer:output_type -> containarium.v1.StartContainerResponse
	15, // 15: containarium.v1.ContainerService.StopContainer:output_type -> containarium.v1.StopContainerResponse
	16, // 16: containarium.v1.ContainerService.AddSSHKey:output_type -> containarium.v1.AddSSHKeyResponse
	17, // 17: containarium.v1.ContainerService.RemoveSSHKey:output_type -> containarium.v1.RemoveSSHKeyResponse
	18, // 18: containarium.v1.ContainerService.GetMetrics:output_type -> containarium.v1.GetMetricsResponse
	19, // 19: containarium.v1.ContainerService.GetSystemInfo:output_type -> containarium.v1.GetSystemInfoResponse
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_containarium_v1_service_proto_init() }
func file_containarium_v1_service_proto_init() {
	if File_containarium_v1_service_proto != nil {
		return
	}
	file_containarium_v1_container_proto_init()
	file_containarium_v1_config_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_containarium_v1_service_proto_rawDesc), len(file_containarium_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_containarium_v1_service_proto_goTypes,
		DependencyIndexes: file_containarium_v1_service_proto_depIdxs,
	}.Build()
	File_containarium_v1_service_proto = out.File
	file_containarium_v1_service_proto_goTypes = nil
	file_containarium_v1_service_proto_depIdxs = nil
}
