// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: containarium/v1/tokens.proto

package containariumv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RevokeTokenRequest names a token to invalidate.
type RevokeTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The `jti` claim of the token to revoke. Required.
	// Operators get the jti either from the audit trail
	// (every authenticated request logs its jti) or by
	// decoding the token they want to kill.
	Jti string `protobuf:"bytes,1,opt,name=jti,proto3" json:"jti,omitempty"`
	// Optional free-form reason recorded in the revocation
	// table for forensics. Examples: "user_logout",
	// "compromise_2026_05_20", "operator_revoke".
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// Optional expiry hint — when the token's exp claim is.
	// Used as the cleanup horizon for the row. If omitted,
	// the daemon falls back to the configured max token
	// lifetime so the row eventually prunes itself.
	ExpiresAt     string `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_containarium_v1_tokens_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_tokens_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_tokens_proto_rawDescGZIP(), []int{0}
}

func (x *RevokeTokenRequest) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

func (x *RevokeTokenRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RevokeTokenRequest) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type RevokeTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when a new revocation row was inserted; false when
	// the jti was already revoked (idempotent — the existing
	// revocation reason is preserved).
	NewlyRevoked bool `protobuf:"varint,1,opt,name=newly_revoked,json=newlyRevoked,proto3" json:"newly_revoked,omitempty"`
	// Human-readable confirmation, intended for CLI output.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenResponse) Reset() {
	*x = RevokeTokenResponse{}
	mi := &file_containarium_v1_tokens_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenResponse) ProtoMessage() {}

func (x *RevokeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_tokens_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_tokens_proto_rawDescGZIP(), []int{1}
}

func (x *RevokeTokenResponse) GetNewlyRevoked() bool {
	if x != nil {
		return x.NewlyRevoked
	}
	return false
}

func (x *RevokeTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Phase 1.6 part B — exchange a refresh token for a new
// (access, refresh) pair. Rotates the refresh token:
// the prior jti is revoked on success, so each refresh
// token is single-use. Replay = denied + audit signal.
type RefreshTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The current refresh token. Must validate via
	// ValidateRefreshToken (signature + iss + aud + exp +
	// tt == "refresh") AND not be in the revocation list.
	RefreshToken  string `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_containarium_v1_tokens_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_tokens_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_tokens_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New short-lived access token, ready to use as
	// Authorization: Bearer.
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// New refresh token. Save this — the one you just sent
	// in is now revoked and cannot be exchanged again.
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	// Unix-seconds expiry of the access token, for clients
	// that want to refresh proactively before exp.
	AccessTokenExpiresAt int64 `protobuf:"varint,3,opt,name=access_token_expires_at,json=accessTokenExpiresAt,proto3" json:"access_token_expires_at,omitempty"`
	// Unix-seconds expiry of the refresh token.
	RefreshTokenExpiresAt int64 `protobuf:"varint,4,opt,name=refresh_token_expires_at,json=refreshTokenExpiresAt,proto3" json:"refresh_token_expires_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_containarium_v1_tokens_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_tokens_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_tokens_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetAccessTokenExpiresAt() int64 {
	if x != nil {
		return x.AccessTokenExpiresAt
	}
	return 0
}

func (x *RefreshTokenResponse) GetRefreshTokenExpiresAt() int64 {
	if x != nil {
		return x.RefreshTokenExpiresAt
	}
	return 0
}

// Revocation is one row of the revocation list, surfaced
// by the admin listing path. The plaintext token itself is
// not in the table — only the jti is.
type Revocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The jti claim of the revoked token.
	Jti string `protobuf:"bytes,1,opt,name=jti,proto3" json:"jti,omitempty"`
	// RFC3339 timestamp of the token's original `exp` claim.
	// Used as the cleanup horizon (rows past this can no
	// longer authenticate anyway, so the daemon prunes
	// them eventually).
	ExpiresAt string `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// RFC3339 timestamp of when the revocation row was
	// first inserted. Operators correlating an incident
	// window use this column.
	RevokedAt string `protobuf:"bytes,3,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	// Free-form reason recorded at revoke time (e.g.
	// "operator_revoke", "refresh_rotation", "leak_2026_X").
	Reason        string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Revocation) Reset() {
	*x = Revocation{}
	mi := &file_containarium_v1_tokens_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Revocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Revocation) ProtoMessage() {}

func (x *Revocation) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_tokens_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Revocation.ProtoReflect.Descriptor instead.
func (*Revocation) Descriptor() ([]byte, []int) {
	return file_containarium_v1_tokens_proto_rawDescGZIP(), []int{4}
}

func (x *Revocation) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

func (x *Revocation) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *Revocation) GetRevokedAt() string {
	if x != nil {
		return x.RevokedAt
	}
	return ""
}

func (x *Revocation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ListRevokedTokensRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Max rows to return. 0 → 100 default. Server caps at
	// 1000.
	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// When true, include rows whose expires_at has already
	// passed (default false — most operators only care
	// about active revocations).
	IncludeExpired bool `protobuf:"varint,2,opt,name=include_expired,json=includeExpired,proto3" json:"include_expired,omitempty"`
	// Narrow by jti prefix. Empty disables. Useful when an
	// operator only remembers part of a leaked jti.
	JtiPrefix     string `protobuf:"bytes,3,opt,name=jti_prefix,json=jtiPrefix,proto3" json:"jti_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRevokedTokensRequest) Reset() {
	*x = ListRevokedTokensRequest{}
	mi := &file_containarium_v1_tokens_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRevokedTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRevokedTokensRequest) ProtoMessage() {}

func (x *ListRevokedTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_tokens_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRevokedTokensRequest.ProtoReflect.Descriptor instead.
func (*ListRevokedTokensRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_tokens_proto_rawDescGZIP(), []int{5}
}

func (x *ListRevokedTokensRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRevokedTokensRequest) GetIncludeExpired() bool {
	if x != nil {
		return x.IncludeExpired
	}
	return false
}

func (x *ListRevokedTokensRequest) GetJtiPrefix() string {
	if x != nil {
		return x.JtiPrefix
	}
	return ""
}

type ListRevokedTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revocations   []*Revocation          `protobuf:"bytes,1,rep,name=revocations,proto3" json:"revocations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRevokedTokensResponse) Reset() {
	*x = ListRevokedTokensResponse{}
	mi := &file_containarium_v1_tokens_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRevokedTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRevokedTokensResponse) ProtoMessage() {}

func (x *ListRevokedTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_tokens_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRevokedTokensResponse.ProtoReflect.Descriptor instead.
func (*ListRevokedTokensResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_tokens_proto_rawDescGZIP(), []int{6}
}

func (x *ListRevokedTokensResponse) GetRevocations() []*Revocation {
	if x != nil {
		return x.Revocations
	}
	return nil
}

var File_containarium_v1_tokens_proto protoreflect.FileDescriptor

const file_containarium_v1_tokens_proto_rawDesc = "" +
	"\n" +
	"\x1ccontainarium/v1/tokens.proto\x12\x0fcontainarium.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"]\n" +
	"\x12RevokeTokenRequest\x12\x10\n" +
	"\x03jti\x18\x01 \x01(\tR\x03jti\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\"T\n" +
	"\x13RevokeTokenResponse\x12#\n" +
	"\rnewly_revoked\x18\x01 \x01(\bR\fnewlyRevoked\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\xce\x01\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x125\n" +
	"\x17access_token_expires_at\x18\x03 \x01(\x03R\x14accessTokenExpiresAt\x127\n" +
	"\x18refresh_token_expires_at\x18\x04 \x01(\x03R\x15refreshTokenExpiresAt\"t\n" +
	"\n" +
	"Revocation\x12\x10\n" +
	"\x03jti\x18\x01 \x01(\tR\x03jti\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\x12\x1d\n" +
	"\n" +
	"revoked_at\x18\x03 \x01(\tR\trevokedAt\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"x\n" +
	"\x18ListRevokedTokensRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12'\n" +
	"\x0finclude_expired\x18\x02 \x01(\bR\x0eincludeExpired\x12\x1d\n" +
	"\n" +
	"jti_prefix\x18\x03 \x01(\tR\tjtiPrefix\"Z\n" +
	"\x19ListRevokedTokensResponse\x12=\n" +
	"\vrevocations\x18\x01 \x03(\v2\x1b.containarium.v1.RevocationR\vrevocations2\xff\t\n" +
	"\rTokensService\x12\x85\x03\n" +
	"\vRevokeToken\x12#.containarium.v1.RevokeTokenRequest\x1a$.containarium.v1.RevokeTokenResponse\"\xaa\x02\x92A\x8a\x02\n" +
	"\x06Tokens\x12\x17Revoke a JWT by its jti\x1a\xe6\x01Adds the token's jti to the revocation list. The token will be rejected on the next request that tries to use it. Admin-only. Idempotent — revoking an already-revoked jti is a no-op (the original revocation reason is preserved).\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/tokens/revoke\x12\xf0\x03\n" +
	"\fRefreshToken\x12$.containarium.v1.RefreshTokenRequest\x1a%.containarium.v1.RefreshTokenResponse\"\x92\x03\x92A\xf1\x02\n" +
	"\x06Tokens\x129Exchange a refresh token for a new (access, refresh) pair\x1a\xab\x02Validates the refresh token (signature + exp + tt='refresh' + not revoked), mints a new short-lived access token, mints a new long-lived refresh token, and revokes the input refresh token's jti. Refresh tokens are single-use; the new refresh token must be stored by the client for the next exchange.\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/tokens/refresh\x12\xf2\x02\n" +
	"\x11ListRevokedTokens\x12).containarium.v1.ListRevokedTokensRequest\x1a*.containarium.v1.ListRevokedTokensResponse\"\x85\x02\x92A\xe7\x01\n" +
	"\x06Tokens\x12\x1dList active token revocations\x1a\xbd\x01Returns revocation rows ordered most-recent-first. Default scope is non-expired revocations only; pass include_expired=true for forensic enumeration. Admin-only with the tokens:write scope.\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/tokens/revokedBKZIgithub.com/footprintai/containarium/pkg/pb/containarium/v1;containariumv1b\x06proto3"

var (
	file_containarium_v1_tokens_proto_rawDescOnce sync.Once
	file_containarium_v1_tokens_proto_rawDescData []byte
)

func file_containarium_v1_tokens_proto_rawDescGZIP() []byte {
	file_containarium_v1_tokens_proto_rawDescOnce.Do(func() {
		file_containarium_v1_tokens_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_containarium_v1_tokens_proto_rawDesc), len(file_containarium_v1_tokens_proto_rawDesc)))
	})
	return file_containarium_v1_tokens_proto_rawDescData
}

var file_containarium_v1_tokens_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_containarium_v1_tokens_proto_goTypes = []any{
	(*RevokeTokenRequest)(nil),        // 0: containarium.v1.RevokeTokenRequest
	(*RevokeTokenResponse)(nil),       // 1: containarium.v1.RevokeTokenResponse
	(*RefreshTokenRequest)(nil),       // 2: containarium.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),      // 3: containarium.v1.RefreshTokenResponse
	(*Revocation)(nil),                // 4: containarium.v1.Revocation
	(*ListRevokedTokensRequest)(nil),  // 5: containarium.v1.ListRevokedTokensRequest
	(*ListRevokedTokensResponse)(nil), // 6: containarium.v1.ListRevokedTokensResponse
}
var file_containarium_v1_tokens_proto_depIdxs = []int32{
	4, // 0: containarium.v1.ListRevokedTokensResponse.revocations:type_name -> containarium.v1.Revocation
	0, // 1: containarium.v1.TokensService.RevokeToken:input_type -> containarium.v1.RevokeTokenRequest
	2, // 2: containarium.v1.TokensService.RefreshToken:input_type -> containarium.v1.RefreshTokenRequest
	5, // 3: containarium.v1.TokensService.ListRevokedTokens:input_type -> containarium.v1.ListRevokedTokensRequest
	1, // 4: containarium.v1.TokensService.RevokeToken:output_type -> containarium.v1.RevokeTokenResponse
	3, // 5: containarium.v1.TokensService.RefreshToken:output_type -> containarium.v1.RefreshTokenResponse
	6, // 6: containarium.v1.TokensService.ListRevokedTokens:output_type -> containarium.v1.ListRevokedTokensResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_containarium_v1_tokens_proto_init() }
func file_containarium_v1_tokens_proto_init() {
	if File_containarium_v1_tokens_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_containarium_v1_tokens_proto_rawDesc), len(file_containarium_v1_tokens_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_containarium_v1_tokens_proto_goTypes,
		DependencyIndexes: file_containarium_v1_tokens_proto_depIdxs,
		MessageInfos:      file_containarium_v1_tokens_proto_msgTypes,
	}.Build()
	File_containarium_v1_tokens_proto = out.File
	file_containarium_v1_tokens_proto_goTypes = nil
	file_containarium_v1_tokens_proto_depIdxs = nil
}
