// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: containarium/v1/tokens.proto

package containariumv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RevokeTokenRequest names a token to invalidate.
type RevokeTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The `jti` claim of the token to revoke. Required.
	// Operators get the jti either from the audit trail
	// (every authenticated request logs its jti) or by
	// decoding the token they want to kill.
	Jti string `protobuf:"bytes,1,opt,name=jti,proto3" json:"jti,omitempty"`
	// Optional free-form reason recorded in the revocation
	// table for forensics. Examples: "user_logout",
	// "compromise_2026_05_20", "operator_revoke".
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// Optional expiry hint — when the token's exp claim is.
	// Used as the cleanup horizon for the row. If omitted,
	// the daemon falls back to the configured max token
	// lifetime so the row eventually prunes itself.
	ExpiresAt     string `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_containarium_v1_tokens_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_tokens_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_containarium_v1_tokens_proto_rawDescGZIP(), []int{0}
}

func (x *RevokeTokenRequest) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

func (x *RevokeTokenRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RevokeTokenRequest) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type RevokeTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when a new revocation row was inserted; false when
	// the jti was already revoked (idempotent — the existing
	// revocation reason is preserved).
	NewlyRevoked bool `protobuf:"varint,1,opt,name=newly_revoked,json=newlyRevoked,proto3" json:"newly_revoked,omitempty"`
	// Human-readable confirmation, intended for CLI output.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenResponse) Reset() {
	*x = RevokeTokenResponse{}
	mi := &file_containarium_v1_tokens_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenResponse) ProtoMessage() {}

func (x *RevokeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containarium_v1_tokens_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return file_containarium_v1_tokens_proto_rawDescGZIP(), []int{1}
}

func (x *RevokeTokenResponse) GetNewlyRevoked() bool {
	if x != nil {
		return x.NewlyRevoked
	}
	return false
}

func (x *RevokeTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_containarium_v1_tokens_proto protoreflect.FileDescriptor

const file_containarium_v1_tokens_proto_rawDesc = "" +
	"\n" +
	"\x1ccontainarium/v1/tokens.proto\x12\x0fcontainarium.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"]\n" +
	"\x12RevokeTokenRequest\x12\x10\n" +
	"\x03jti\x18\x01 \x01(\tR\x03jti\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\"T\n" +
	"\x13RevokeTokenResponse\x12#\n" +
	"\rnewly_revoked\x18\x01 \x01(\bR\fnewlyRevoked\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x97\x03\n" +
	"\rTokensService\x12\x85\x03\n" +
	"\vRevokeToken\x12#.containarium.v1.RevokeTokenRequest\x1a$.containarium.v1.RevokeTokenResponse\"\xaa\x02\x92A\x8a\x02\n" +
	"\x06Tokens\x12\x17Revoke a JWT by its jti\x1a\xe6\x01Adds the token's jti to the revocation list. The token will be rejected on the next request that tries to use it. Admin-only. Idempotent — revoking an already-revoked jti is a no-op (the original revocation reason is preserved).\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/tokens/revokeBKZIgithub.com/footprintai/containarium/pkg/pb/containarium/v1;containariumv1b\x06proto3"

var (
	file_containarium_v1_tokens_proto_rawDescOnce sync.Once
	file_containarium_v1_tokens_proto_rawDescData []byte
)

func file_containarium_v1_tokens_proto_rawDescGZIP() []byte {
	file_containarium_v1_tokens_proto_rawDescOnce.Do(func() {
		file_containarium_v1_tokens_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_containarium_v1_tokens_proto_rawDesc), len(file_containarium_v1_tokens_proto_rawDesc)))
	})
	return file_containarium_v1_tokens_proto_rawDescData
}

var file_containarium_v1_tokens_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_containarium_v1_tokens_proto_goTypes = []any{
	(*RevokeTokenRequest)(nil),  // 0: containarium.v1.RevokeTokenRequest
	(*RevokeTokenResponse)(nil), // 1: containarium.v1.RevokeTokenResponse
}
var file_containarium_v1_tokens_proto_depIdxs = []int32{
	0, // 0: containarium.v1.TokensService.RevokeToken:input_type -> containarium.v1.RevokeTokenRequest
	1, // 1: containarium.v1.TokensService.RevokeToken:output_type -> containarium.v1.RevokeTokenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_containarium_v1_tokens_proto_init() }
func file_containarium_v1_tokens_proto_init() {
	if File_containarium_v1_tokens_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_containarium_v1_tokens_proto_rawDesc), len(file_containarium_v1_tokens_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_containarium_v1_tokens_proto_goTypes,
		DependencyIndexes: file_containarium_v1_tokens_proto_depIdxs,
		MessageInfos:      file_containarium_v1_tokens_proto_msgTypes,
	}.Build()
	File_containarium_v1_tokens_proto = out.File
	file_containarium_v1_tokens_proto_goTypes = nil
	file_containarium_v1_tokens_proto_depIdxs = nil
}
