// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: containarium/v1/zap.proto

package containariumv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ZapService_TriggerZapScan_FullMethodName     = "/containarium.v1.ZapService/TriggerZapScan"
	ZapService_ListZapScanRuns_FullMethodName    = "/containarium.v1.ZapService/ListZapScanRuns"
	ZapService_ListZapAlerts_FullMethodName      = "/containarium.v1.ZapService/ListZapAlerts"
	ZapService_GetZapAlertSummary_FullMethodName = "/containarium.v1.ZapService/GetZapAlertSummary"
	ZapService_SuppressZapAlert_FullMethodName   = "/containarium.v1.ZapService/SuppressZapAlert"
	ZapService_GetZapConfig_FullMethodName       = "/containarium.v1.ZapService/GetZapConfig"
	ZapService_GetZapReport_FullMethodName       = "/containarium.v1.ZapService/GetZapReport"
	ZapService_InstallZap_FullMethodName         = "/containarium.v1.ZapService/InstallZap"
)

// ZapServiceClient is the client API for ZapService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ZapService provides OWASP ZAP web application security scanning
type ZapServiceClient interface {
	// TriggerZapScan triggers an on-demand ZAP scan across all exposed endpoints
	TriggerZapScan(ctx context.Context, in *TriggerZapScanRequest, opts ...grpc.CallOption) (*TriggerZapScanResponse, error)
	// ListZapScanRuns returns recent ZAP scan runs
	ListZapScanRuns(ctx context.Context, in *ListZapScanRunsRequest, opts ...grpc.CallOption) (*ListZapScanRunsResponse, error)
	// ListZapAlerts returns ZAP alerts with optional filtering
	ListZapAlerts(ctx context.Context, in *ListZapAlertsRequest, opts ...grpc.CallOption) (*ListZapAlertsResponse, error)
	// GetZapAlertSummary returns aggregate alert statistics
	GetZapAlertSummary(ctx context.Context, in *GetZapAlertSummaryRequest, opts ...grpc.CallOption) (*GetZapAlertSummaryResponse, error)
	// SuppressZapAlert marks an alert as suppressed
	SuppressZapAlert(ctx context.Context, in *SuppressZapAlertRequest, opts ...grpc.CallOption) (*SuppressZapAlertResponse, error)
	// GetZapConfig returns the current ZAP configuration
	GetZapConfig(ctx context.Context, in *GetZapConfigRequest, opts ...grpc.CallOption) (*GetZapConfigResponse, error)
	// GetZapReport downloads a scan report in the specified format
	GetZapReport(ctx context.Context, in *GetZapReportRequest, opts ...grpc.CallOption) (*GetZapReportResponse, error)
	// InstallZap downloads and installs OWASP ZAP
	InstallZap(ctx context.Context, in *InstallZapRequest, opts ...grpc.CallOption) (*InstallZapResponse, error)
}

type zapServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewZapServiceClient(cc grpc.ClientConnInterface) ZapServiceClient {
	return &zapServiceClient{cc}
}

func (c *zapServiceClient) TriggerZapScan(ctx context.Context, in *TriggerZapScanRequest, opts ...grpc.CallOption) (*TriggerZapScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerZapScanResponse)
	err := c.cc.Invoke(ctx, ZapService_TriggerZapScan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zapServiceClient) ListZapScanRuns(ctx context.Context, in *ListZapScanRunsRequest, opts ...grpc.CallOption) (*ListZapScanRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListZapScanRunsResponse)
	err := c.cc.Invoke(ctx, ZapService_ListZapScanRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zapServiceClient) ListZapAlerts(ctx context.Context, in *ListZapAlertsRequest, opts ...grpc.CallOption) (*ListZapAlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListZapAlertsResponse)
	err := c.cc.Invoke(ctx, ZapService_ListZapAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zapServiceClient) GetZapAlertSummary(ctx context.Context, in *GetZapAlertSummaryRequest, opts ...grpc.CallOption) (*GetZapAlertSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetZapAlertSummaryResponse)
	err := c.cc.Invoke(ctx, ZapService_GetZapAlertSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zapServiceClient) SuppressZapAlert(ctx context.Context, in *SuppressZapAlertRequest, opts ...grpc.CallOption) (*SuppressZapAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuppressZapAlertResponse)
	err := c.cc.Invoke(ctx, ZapService_SuppressZapAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zapServiceClient) GetZapConfig(ctx context.Context, in *GetZapConfigRequest, opts ...grpc.CallOption) (*GetZapConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetZapConfigResponse)
	err := c.cc.Invoke(ctx, ZapService_GetZapConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zapServiceClient) GetZapReport(ctx context.Context, in *GetZapReportRequest, opts ...grpc.CallOption) (*GetZapReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetZapReportResponse)
	err := c.cc.Invoke(ctx, ZapService_GetZapReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zapServiceClient) InstallZap(ctx context.Context, in *InstallZapRequest, opts ...grpc.CallOption) (*InstallZapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallZapResponse)
	err := c.cc.Invoke(ctx, ZapService_InstallZap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZapServiceServer is the server API for ZapService service.
// All implementations must embed UnimplementedZapServiceServer
// for forward compatibility.
//
// ZapService provides OWASP ZAP web application security scanning
type ZapServiceServer interface {
	// TriggerZapScan triggers an on-demand ZAP scan across all exposed endpoints
	TriggerZapScan(context.Context, *TriggerZapScanRequest) (*TriggerZapScanResponse, error)
	// ListZapScanRuns returns recent ZAP scan runs
	ListZapScanRuns(context.Context, *ListZapScanRunsRequest) (*ListZapScanRunsResponse, error)
	// ListZapAlerts returns ZAP alerts with optional filtering
	ListZapAlerts(context.Context, *ListZapAlertsRequest) (*ListZapAlertsResponse, error)
	// GetZapAlertSummary returns aggregate alert statistics
	GetZapAlertSummary(context.Context, *GetZapAlertSummaryRequest) (*GetZapAlertSummaryResponse, error)
	// SuppressZapAlert marks an alert as suppressed
	SuppressZapAlert(context.Context, *SuppressZapAlertRequest) (*SuppressZapAlertResponse, error)
	// GetZapConfig returns the current ZAP configuration
	GetZapConfig(context.Context, *GetZapConfigRequest) (*GetZapConfigResponse, error)
	// GetZapReport downloads a scan report in the specified format
	GetZapReport(context.Context, *GetZapReportRequest) (*GetZapReportResponse, error)
	// InstallZap downloads and installs OWASP ZAP
	InstallZap(context.Context, *InstallZapRequest) (*InstallZapResponse, error)
	mustEmbedUnimplementedZapServiceServer()
}

// UnimplementedZapServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZapServiceServer struct{}

func (UnimplementedZapServiceServer) TriggerZapScan(context.Context, *TriggerZapScanRequest) (*TriggerZapScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerZapScan not implemented")
}
func (UnimplementedZapServiceServer) ListZapScanRuns(context.Context, *ListZapScanRunsRequest) (*ListZapScanRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListZapScanRuns not implemented")
}
func (UnimplementedZapServiceServer) ListZapAlerts(context.Context, *ListZapAlertsRequest) (*ListZapAlertsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListZapAlerts not implemented")
}
func (UnimplementedZapServiceServer) GetZapAlertSummary(context.Context, *GetZapAlertSummaryRequest) (*GetZapAlertSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetZapAlertSummary not implemented")
}
func (UnimplementedZapServiceServer) SuppressZapAlert(context.Context, *SuppressZapAlertRequest) (*SuppressZapAlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SuppressZapAlert not implemented")
}
func (UnimplementedZapServiceServer) GetZapConfig(context.Context, *GetZapConfigRequest) (*GetZapConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetZapConfig not implemented")
}
func (UnimplementedZapServiceServer) GetZapReport(context.Context, *GetZapReportRequest) (*GetZapReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetZapReport not implemented")
}
func (UnimplementedZapServiceServer) InstallZap(context.Context, *InstallZapRequest) (*InstallZapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallZap not implemented")
}
func (UnimplementedZapServiceServer) mustEmbedUnimplementedZapServiceServer() {}
func (UnimplementedZapServiceServer) testEmbeddedByValue()                    {}

// UnsafeZapServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZapServiceServer will
// result in compilation errors.
type UnsafeZapServiceServer interface {
	mustEmbedUnimplementedZapServiceServer()
}

func RegisterZapServiceServer(s grpc.ServiceRegistrar, srv ZapServiceServer) {
	// If the following call panics, it indicates UnimplementedZapServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ZapService_ServiceDesc, srv)
}

func _ZapService_TriggerZapScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerZapScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZapServiceServer).TriggerZapScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZapService_TriggerZapScan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZapServiceServer).TriggerZapScan(ctx, req.(*TriggerZapScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZapService_ListZapScanRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListZapScanRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZapServiceServer).ListZapScanRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZapService_ListZapScanRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZapServiceServer).ListZapScanRuns(ctx, req.(*ListZapScanRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZapService_ListZapAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListZapAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZapServiceServer).ListZapAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZapService_ListZapAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZapServiceServer).ListZapAlerts(ctx, req.(*ListZapAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZapService_GetZapAlertSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetZapAlertSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZapServiceServer).GetZapAlertSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZapService_GetZapAlertSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZapServiceServer).GetZapAlertSummary(ctx, req.(*GetZapAlertSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZapService_SuppressZapAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuppressZapAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZapServiceServer).SuppressZapAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZapService_SuppressZapAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZapServiceServer).SuppressZapAlert(ctx, req.(*SuppressZapAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZapService_GetZapConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetZapConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZapServiceServer).GetZapConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZapService_GetZapConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZapServiceServer).GetZapConfig(ctx, req.(*GetZapConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZapService_GetZapReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetZapReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZapServiceServer).GetZapReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZapService_GetZapReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZapServiceServer).GetZapReport(ctx, req.(*GetZapReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZapService_InstallZap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallZapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZapServiceServer).InstallZap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZapService_InstallZap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZapServiceServer).InstallZap(ctx, req.(*InstallZapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZapService_ServiceDesc is the grpc.ServiceDesc for ZapService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZapService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "containarium.v1.ZapService",
	HandlerType: (*ZapServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TriggerZapScan",
			Handler:    _ZapService_TriggerZapScan_Handler,
		},
		{
			MethodName: "ListZapScanRuns",
			Handler:    _ZapService_ListZapScanRuns_Handler,
		},
		{
			MethodName: "ListZapAlerts",
			Handler:    _ZapService_ListZapAlerts_Handler,
		},
		{
			MethodName: "GetZapAlertSummary",
			Handler:    _ZapService_GetZapAlertSummary_Handler,
		},
		{
			MethodName: "SuppressZapAlert",
			Handler:    _ZapService_SuppressZapAlert_Handler,
		},
		{
			MethodName: "GetZapConfig",
			Handler:    _ZapService_GetZapConfig_Handler,
		},
		{
			MethodName: "GetZapReport",
			Handler:    _ZapService_GetZapReport_Handler,
		},
		{
			MethodName: "InstallZap",
			Handler:    _ZapService_InstallZap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "containarium/v1/zap.proto",
}
